### ISSUE TITLE
How does PGStrom extension work?

### ISSUE THREAD

**Issue by jimwu88** [heterodb/pg-strom#244]
I am just trying to understand how PGStrom extension work. When I run the test query below without "create extension pg_strom", the query plan is still "explained" based on PGStrom? How does PostgreSQL know when to send a query to PGstrom or just use it's own SQL engine? 

testdb=# EXPLAIN  
SELECT cat, avg(ax) FROM t0 NATURAL JOIN t1 NATURAL JOIN t2 GROUP BY cat;
NOTICE:  schema "pgstrom" was not found
HINT:  Try to run: CREATE EXTENSION pg_strom
##                                       QUERY PLAN                                       

 HashAggregate  (cost=3349749.08..3349749.40 rows=26 width=12)
   Group Key: t0.cat
   ->  Custom Scan (GpuJoin) on t0  (cost=12325.86..2851751.79 rows=99599458 width=12)
         GPU Projection: t0.cat, t1.ax
         Depth 1: GpuHashJoin, HashKeys: (t0.aid)
                  JoinQuals: (t0.aid = t1.aid)
                  Nrows (in/out: 99.60%), KDS-Hash (size: 13.47MB, nbatches: 1)
         Depth 2: GpuHashJoin, HashKeys: (t0.bid)
                  JoinQuals: (t0.bid = t2.bid)
                  Nrows (in/out: 100.00%), KDS-Hash (size: 13.47MB, nbatches: 1)
         ->  Seq Scan on t1  (cost=0.00..1935.00 rows=100000 width=12)
         ->  Seq Scan on t2  (cost=0.00..1935.00 rows=100000 width=4)
(12 rows)

**Comment by kaigai** [comment]
Although you didn't run ```CREATE EXTENSION pg_strom```, I expect you configured ```shared_preload_libraries```.
```CREATE EXTENSION``` defines some SQL functions including the ones needed by GpuPreAgg, thus, your query plan does not have GpuPreAgg to process GROUP BY.
On the other hands, GpuScan and GpuJoin actually don't depend on these SQL objects, so it can construct GPU accelerated version of Join/Scan.
