### ISSUE TITLE
Revisit OpenCL support

### ISSUE THREAD

**Issue by rdeleonp** [heterodb/pg-strom#245]
Could you revisit the OpenCL implementation in the current landscape (2016)?

Maybe things have improved.

Worst case, ignore *ntel and focus on AMD/Nvidia.

**Comment by rdeleonp** [comment]
GPUOpen is being pushed a lot: http://gpuopen.com/

**Comment by rdeleonp** [comment]
HIP : C++ Heterogeneous-Compute Interface for Portability
http://gpuopen.com/compute-product/hip-convert-cuda-to-portable-c-code/

**Comment by rdeleonp** [comment]
From the link: "To further reduce the learning curve when moving from Cuda to HIP, we developed the hipify tool to automate your application’s core conversion."

**Comment by kaigai** [comment]
I have to go through the shortest way to provide a working, (minimum) valuable and stable software for users; prior to the project dead.
We already built many stuff on CUDA, and have been evaluated with not a small use cases.
If we would move to other infrastructure, it clearly make the day of "v1.0" delayed.

I can understand the demand, however, it is unavailable to accept at this moment.

**Comment by rdeleonp** [comment]
I completely understand.

Hopefully after v1.0 releases.

Just reporting the information for future reference:

HIP : C++ Heterogeneous-Compute Interface for Portability:
http://gpuopen.com/compute-product/hip-convert-cuda-to-portable-c-code/

From the link:
"To further reduce the learning curve when moving from Cuda to HIP, we developed the hipify tool to automate your application’s core conversion."

Thanks for your time.

**Comment by kaigai** [comment]
https://github.com/heterodb/pg-strom/wiki/003:-Development-Roadmap#features-we-shall-not-support
