### ISSUE TITLE
TPC-DS, TPC-H testing ?

### ISSUE THREAD

**Issue by ghost** [heterodb/pg-strom#249]
Have tpc-ds or tpc-h tests been created/run yet ? I'm just getting started with pgstrom and am looking to run those tests for some comparisons.

**Comment by kaigai** [comment]
I and my colleague internally did the tpc-ds test about a year before, but not well summarized and published yet.
Due to lack of optimizer's creativity, we have to adjust some queries to complete within reasonable time. And, Q78 gets OOM Killer with SF=100 on both of PostgreSQL and PG-Strom cases.

**Comment by dimon777** [comment]
I'd suggest add TPC-DS test into repository. It doesn't have to be 100% valid and exceptional on performance. It is important to have it since it allows tangible comparisons with other platforms and indicative of platform readiness for the enterprise. Thanks.

**Comment by kaigai** [comment]
I run TPC-DS in the past (so much different internal implementation from the today's one).
  https://www.slideshare.net/kaigai/tpcdspostgresql

TPC-DS has more than 100 queries, thus not easy to provide tangible results for people.

We usually run star-schema benchmark which is similar to IoT class workloads.

And, TPC-H/DBT-3 may be better for comparison. Likely, it needs Semi-/Anti-Join support on GPU side to pull out better performance, so I put these features in the development roadmap.
https://github.com/heterodb/pg-strom/wiki/003:-Development-Roadmap#idea-of-new-features

Thanks,

**Comment by dimon777** [comment]
Thanks for the links. Do you have English version of the presentation? Sorry I for my inability to read (Japanese?)

**Comment by kaigai** [comment]
Sorry, I was a presentation at Japan PostgreSQL Users Group Conference.

In short, it says
- 95% of time were consumed by SCAN, JOIN and GROUP BY. (p.24)
- Correlated subquery is evil, especially, in PostgreSQL.
    - Oracle could rewrite more efficient query execution plan, so manual optimization is still needed.
- Nested-Loop is evil, especially, in case when large tables join.

Not only the portion where PG-Strom can accelerate, here are many action items around PostgreSQL.

**Comment by dimon777** [comment]
Thank you for translation. And thumbs up for the integration plan with Citus to scale out!
