### ISSUE TITLE
Any plans for additional data types?

### ISSUE THREAD

**Issue by cartomike** [heterodb/pg-strom#264]
Do you have any plans to support additional data types?  Like "uuid" for instance...

**Comment by kaigai** [comment]
It depends on user's request and wideness of the use-scenario.

In my mind, ```inet``` and ```macaddr``` have priority.
It seems to me ```uuid``` data type requires small number of functions and operators to support, so it may be fair enough to add.

What kind of use scenario in your mind for ```uuid``` data type with PG-Strom?

**Comment by cartomike** [comment]
Looking at Big Data and Linked Data environments.  Use of uuid (PK/FK) is used to maintain unique ids for entities across multiple systems.  Lots of records - lots of relationships...

**Comment by kaigai** [comment]
OK, it looks to me fair enough.
I'll do add ```uuid``` data type support but for the master branch, because I don't want to enhance the STABLE_v1 branch any more.

**Comment by kaigai** [comment]
```uuid``` datatype support shall be included in the list of v2.0 features.

**Comment by kaigai** [comment]
uuid support was added at 3d23b214bdaf2157622d482d0722669e94f4e390
