### ISSUE TITLE
Testquery.sql Error

### ISSUE THREAD

**Issue by cyk0521** [heterodb/pg-strom#279]
PG-strom works well on my sata ssd (Samsung SSD 840 PRO 512GB), but it doesn't work on nvme ssd (Intel DC P3600 SSD 400GB).
I followed basic instructions in the wiki page like belows,

`initdb -D /mnt/testvol_nvme2/pg_strom/dbdata`
`pg_ctl -D /mnt/testvol_nvme2/pg_strom/dbdata start`

and then, I modified postgresql.conf file exactly same to the wiki page.
after that, 

`psql`
`CREATE EXTENSION pg_strom;`
`\i pg_strom/test/testdb.sql; `
`\i pg_strom/test/testquery.sql; `

then, I got an error message while processing the final query:
`EXPLAIN ANALYZE SELECT cat, count(*) FROM t0 NATURAL JOIN t1 NATURAL JOIN t2 WHERE sqrt((ax-20)^2 + (bx-30)^2) < 10 GROUP BY cat;`

`
Error message: 
TRAP: FailedAssertion("!(!entry->bin_image)", File: "src/cuda_program.c", Line: 836)
psql:pg_strom/test/testquery.sql:37: NOTICE:  sockfd=68 closed
LOG:  worker process: PG-Strom GPU/CUDA Server [0] (PID 20295) was terminated by signal 6: Aborted
LOG:  terminating any other active server processes
`

How to fix this problem?

Environment: 
OS: CentOS Linux release 7.3.1611, linux 3.10.0-514.el7.x86_64
Postgres 9.6.3, PG-strom master branch version (June 27, 2017)
xfs or ext4 (both filesystems have same error)
GPU: Tesla P100  (GPU Memory: 16GB), CUDA 8.0

**Comment by kaigai** [comment]
Likely, it is a bug around asynchronous code build.
Once a worker picked up a GPU program not built yet, it has to be detached from the pending list of GPU source programs.

Sorry, please wait for a few weeks. I found same problem during the recent code refactoring, however, not merged to the master branch yet. (Some other problems still exit.)
