### ISSUE TITLE
Mobile GPU (GT???M)

### ISSUE THREAD

**Issue by yss126** [heterodb/pg-strom#296]
Hi all,

I had a look at GPU Availability Matrix and I could not see any Mobile GPU for example GT 750M.
Does PG-Strom not support mobile GPUs?
Thank you.

**Comment by skywalkerytx** [comment]
https://developer.nvidia.com/cuda-gpus

you can find a full list here about your GPU's compute capabilities.

as you can see, GT 750M is cc=3.0 which < minimum requirement cc3.5

**Comment by kaigai** [comment]
As long as mobile GPUs has computing capability 3.5 or later, it may be **runnable**.
However, mobile GPUs shares host memory, thus, its performance is much lesser than discrete GPUs.
So, I don't recommend mobile GPUs for PG-Strom, and we have no special handling to support mobile GPUs. (One potential optimization may be omit of DMA send/recv if integrated GPUs. Not implemented yet.)
