### ISSUE TITLE
FATAL:  could not load library "/usr/lib/postgres-xc/pg_strom.so": /usr/lib/postgres-xc/pg_strom.so: undefined symbol: set_join_pathlist_hook

### ISSUE THREAD

**Issue by sw1p3r** [heterodb/pg-strom#300]
Hi,

i'm installing pg_strom and i using GTX 1060 + cuda 8.0 

when i starts pg_strom using pg_ctl -D /ssd1/db/ -Z coordinator start 

it returns : 

FATAL:  could not load library "/usr/lib/postgres-xc/pg_strom.so": /usr/lib/postgres-xc/pg_strom.so: undefined symbol: set_join_pathlist_hook

i have tried the solution in : 
https://github.com/heterodb/pg-strom/issues/217

but the problem is not solved...

could you help me?

other setting that i use : 
shared_preload_libraries = '$libdir/pg_strom'

**Comment by kaigai** [comment]
Likely, you didn't use proper version of PostgreSQL.
It looks to me PostgreSQL-XC has not been maintained for a long time, thus, its base version is neither 9.5 nor 9.6.
The ```set_join_pathlist_hook``` was newly defined at PostgreSQL 9.5.

**Comment by sw1p3r** [comment]
so all i need to solve the problem is only using the supported version of PostgreSQL like version 9.3?

**Comment by kaigai** [comment]
PostgreSQL 9.5 + STABLE_v1 branch, or PostgreSQL 9.6 + master branch (still in active development).

PostgreSQL 9.4 or prior are not workable.
