### ISSUE TITLE
Error: codegen: failed to lookup device function: lower(text)

### ISSUE THREAD

**Issue by etgbccc** [heterodb/pg-strom#306]
My query has some lower() and concat functions

The query works perfectly in normal postgresql but I received the errors:
Error: codegen: failed to lookup device function: lower(text)
Error: codegen: failed to lookup device function: concat("any")

It seems that pg_strom is unable to generate code properlyfor text functions in aggregate functions?

Thanks.

Regards

**Comment by kaigai** [comment]
Could you provide me the problematic query?
Likely, it is a bug because PG-Strom does not support these functions, so GPU version of execution shall not be chosen instead of the error reporting.

**Comment by etgbccc** [comment]
Hi, my setup is using M4000.

My query is rather complex...it looks like this 

Thanks.

select a.price_date,a.c0 from (select price_date,b.c0 from (select price_date,max(price) filter (where m.price_symbol_id=(select price_symbol_id from tbl_price_symbol where lower(price_symbol) = 'fed_usd_aud') and lower(price_field) = 'daily') as c0 from ((select price_symbol_id,price_date,price_time,price_field,price from tbl_price_curveseries where price_symbol_id in (select s.price_symbol_id from (select tbl_price_symbol.price_symbol_id, sum(case when tbl_permission_group.active=true then 1 else 0 end) as countofactive, sum(case when (tbl_user.user_name='etgbccc' and tbl_user.company_id in (select tbl_company_permission.company_id_from from (tbl_user left join tbl_company on tbl_company.company_id = tbl_user.company_id) left join tbl_company_permission on tbl_company.company_id = tbl_company_permission.company_id_to where tbl_user.user_name='abc')) then 1 else 0 end) as countofuser from (((tbl_price_symbol left join tbl_permission on (case when lower(tbl_permission.permission_type)='curve' then lower(tbl_price_symbol.price_curve) = lower(tbl_permission.permission_symbol) else (case when lower(tbl_permission.permission_type)='series' then lower(tbl_price_symbol.price_symbol) = lower(tbl_permission.permission_symbol) else lower(tbl_price_symbol.price_path) like concat('%',lower(tbl_permission.permission_symbol)) end) end)) left join tbl_permission_group on tbl_permission.permission_group_id = tbl_permission_group.permission_group_id) left join tbl_user_permission on tbl_permission_group.permission_group_id = tbl_user_permission.permission_group_id) left join tbl_user on tbl_user_permission.user_id = tbl_user.user_id group by tbl_price_symbol.price_symbol_id) as s where (s.countofactive = 0 or s.countofuser!=0) and s.price_symbol_id in (select price_symbol_id from tbl_price_symbol where lower(price_symbol) in('fed_usd_aud'))))) as m where ((price_date between '2017-02-01 00:00:00.000000' and '2017-01-31 00:00:00.000000')) group by price_date order by price_date) as b) as a where a.c0 is not null

**Comment by kaigai** [comment]
`lower(text)` is not supported, and `concat(text, text)` can work only if output length is estimatable.
