### ISSUE TITLE
Error on CREATE EXTENSION pg_strom;

### ISSUE THREAD

**Issue by Alexis6307** [heterodb/pg-strom#329]
Hi all,
I'm trying to deploy pg_strom in a new test machine and I'm getting an error when I set the shared_preload_libraries int postresql.conf. Here I will tell my system specifications and steps I follow, maybe I make a mistake in the install/config process.

Hardware:
-CPU Intel G4400
-RAM 4GB.
-SSD 16 GB.
-GPU Nvidia GTX 970.
-Motherboard MSI Z170A M5.

My software environment is easy to replicate:
-CentOs 7 minimal install.

Once I install the OS I follow this steps (from [HeteroDB manual](http://heterodb.com/install.html#install)).

1. Install gcc, make, git, bison, flex, epel-release, nano, readline-devel, wget, kernel-devel & dkms.
2. Disable nouveau & run dracut.
3. Download & install [Nvidia Cuda](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=CentOS&target_version=7&target_type=rpmnetwork) rpm network installer.
4. Added config to solve the problem about linkage of NVRTC that is used by PG-Strom.
5. Download and install Postgresql from [sources](https://ftp.postgresql.org/pub/source/v9.6.6/postgresql-9.6.6.tar.gz) version 9.6.6. with `--prefix=/usr/local/pgsql`.
6. Added `/usr/local/pgsql/bin` to $PATH.
7. Run `pg_config --pgxs`.
8. `git clone https://github.com/pg-strom/devel.git pg_strom` & install.
9. `initdb -D testdb` & `pg_ctl -D testdb start`.
10. At this point all works well, so run `createdb test` too.
11. edit testdb/postgresql.conf to add `shared_preload_libraries = '$libdir/pg_strom'`, shared_buffer and work_mem.
12. Restart and `pg_ctl -D testdb start` again.

Here comes the crash:
```
[test@localhost pg_strom]$ pg_ctl -D testdb start
server starting
[test@localhost pg_strom]$ FATAL:  could not load library "/usr/local/pgsql/lib/pg_strom.so": /usr/local/pgsql/lib/pg_strom.so: undefined symbol: MemoryContextCheck
LOG:  database system is shut down
```

Am I losing any step? Any help will be appreciated.

**Comment by kaigai** [comment]
See #328. It is same issue, and already solved.

Please note that GTX970 is based on Maxwell architecture.
It is no longer supported.

**Comment by Alexis6307** [comment]
Oops, I thought #328  is more related to postgresql version. I have tried to use the more stable & compatible version of postgres & pg_strom to get it working. Well, so... we only can wait for the fix?
Thanks.

**Comment by Alexis6307** [comment]
Since when is the Maxwell architecture not supported? Following your guide GTX970 is supported....
[GPU Availability Matrix](https://github.com/heterodb/pg-strom/wiki/GPU-Availability-Matrix)

**Comment by kaigai** [comment]
That is based on v1. The branch you working on is upcoming v2.0....

I'll update the availability matrix soon later.
In short, the recent PG-Strom requires Pascal or Volta architecture.
Because they newly support demand paging on GPU device memory, applications (including PG-Strom) can simplify the code to handle memory over-consumption scenario.
For example, once we allocate 10GB device memory on Pascal/Volta, physical pages shall be allocated on demand, as like modern operating system doing. So, if workload consumed only 1GB of 10GB, least amount of resources are actually consumed.
On the other hands, Maxwell or prior architecture allocates 10GB pages on allocation time. It makes application complicated and buggy.

**Comment by kaigai** [comment]
GPU Availability Matrix gets updated.

**Comment by JavierGonzalez** [comment]
Thank you, master.

**Comment by Alexis6307** [comment]
We change GPU and use PostgreSQL 9.6.6 with PGstrom devel version and it works fine ;)
