### ISSUE TITLE
GTX 1060 6GB unrecommended, Why?

### ISSUE THREAD

**Issue by thebf** [heterodb/pg-strom#332]
Is the performance gains not significant or is there some expected issues?
Would it be sufficient for getting familiarized with the extension in a test-environment?

**Comment by kaigai** [comment]
We simply mark GPU model which has (1) less than about 2000cores or (2) less than 200GB/s memory band as **not recommended**. Amount of GPU memory might be a third factor.
It looks me 1280cores and 6GB RAM are a bit smaller than our expectation, may cause unexpected trouble.

**Comment by jspinella** [comment]
@thebf Have you been successful with the GTX 1060 6GB? I'm about to give it a shot myself, just found this after seeing the team has it as "unrecommended"

**Comment by kaigai** [comment]
Because it has relatively smaller number of CUDA cores (= 1280), and memory bandwidth is less than 200GB/s.
We usually use Tesla P40 for development, so it may cause unexpected performance problems.
