### ISSUE TITLE
GROUP BY not working 

### ISSUE THREAD

**Issue by t6166as** [heterodb/pg-strom#333]
I am trying to do a very simple group by statement on a table. I keep getting these errors and query does not move forward. 

Best regards, 

Abhishek

stromtest=# explain select sum(tripinseconds), avg(tripinseconds), company from strom.taxiride where company is not null group by 3 order by 1 desc;
ERROR:  Bug? type (character varying) has no device equality function

ERROR:  Bug? device type 'text' has indirect/varlena definition but no extra-size parameter at expression of: {RELABELTYPE :arg {VAR :varno 1 :varattno 17 :vartype 1043 :vartypmod 104 :varcollid 100 :varlevelsup 0 :varnoold 1 :varoattno 17 :location 17} :resulttype 25 :resulttypmod -1 :resultcollid 100 :relabelformat 1 :location 24}

**Comment by kaigai** [comment]
Could you provide the following results on your database?
```
\d+ company 
\l
```
I guess we don't implement equality-comparison function for ```varchar(N)``` data type, even if PG-Strom's internal catalog marks it is supported.
Usually, it shall be dealt with ```texteq``` function because they have identical internal format.

**Comment by kaigai** [comment]
Hmm... It looks to me GpuPreAgg logic needs to inject type cast (actually, just relabel) when it generates device code for grouping key comparison.

**Comment by kaigai** [comment]
I believe the latest revision (b3029a128f7edd349fdd2f979bfb23f9bef0bd66) works with device function invocation which takes binary compatible arguments.
