### ISSUE TITLE
Performance-related questions

### ISSUE THREAD

**Issue by Alexis6307** [heterodb/pg-strom#334]
Hi master,

We are under research with this amazing technology, we already have run queries with pg-strom enabled. So now we are trying to increase performance and enhance the GPU power in the DB and we have the next questions: 

1. When we build PostgreSQL from source, the parameter "num of parallels", it is related to CPU cores or GPU cores?

2. In case it's related to CPU cores, where we can set the potential of GPU will be used? In our tests, we can see the GPU is using 150MB only, with a GTX 1080 ti.

3. In queries with "group by" statement, PostgreSQL server crashed with PGStrom enabled, but without PGStrom it works... what can be the issue?

Thanks a lot.

**Comment by kaigai** [comment]
1. Which options do you mean "num of parallels"? In general, PostgreSQL does not pay attention for GPU.

2. ``env CUDA_VISIBLE_DEVICES=``` can restrict GPUs visible from applications in general. However, current PG-Strom use all GPUs in round robin rules.

3. Please try to reproduce the problem in the latest revision. If possible, show me the query and call trace from the crash dump.

**Comment by Alexis6307** [comment]
La consulta se estrelló por un mal postgresql. conf.
