### ISSUE TITLE
Using cuda in custom functions

### ISSUE THREAD

**Issue by twojenski** [heterodb/pg-strom#339]
Hello 
What a wonderful piece of work!  Congrats!

I'm hoping to accelerate the execution of string search function, so I wrote a my own string function based on STATIC_FUNCTION(cl_int) text_compare and wrapped it as per example in postgres function.

My hardware set is:
CPU:   Dual  - Xenon E5606 @ 2.13GHz
GPU:   GeForce GTX 1070
HDD:  SATA SSD  OCZ-TRION150  

My SQL statement is an INSERT/INTO/SELECT  and Selects ~50K records with ~100 columns invoking my custom function.

My hope was to off-load the inner workings of my string function from CPU to the GPU, however the GPU SQL that I'm running is considerably MUCH MUCH slower than with the GPU (normal postgres) version of the function.

Is writing specialized string functions to be executed in the SELECT clause, that run on the GPU suggested/recommended?  Could the calling the calling overhead cause this problem?

Regards

Tek

**Comment by kaigai** [comment]
Probably, the feature which you want is on the roadmap after the v2.0.

Custom PL/CUDA function with some restrictions can fit auto-generated GPU code from the SQL expression. For example, if PL/CUDA function takes two `pg_text_t` arguments (one is pattern,
and the other is target) and returns `pg_int_t`, it is not technically difficult to come into the auto-
generated code from the WHERE-clause and so on.

Now we focus on the v2.0 release, however, we understand the necessity and requirement.
https://github.com/heterodb/pg-strom/wiki/003:-Development-Roadmap

**Comment by twojenski** [comment]
Hello kaigai

Thanks for response.

I just want to make sure I stated my problem correctly,   I'm trying to optimize a function which will be executed on the SELECT clause,  50,000 rows * 100 columns, so it will be invoked 5,000,000 times.

I do have a functioning version of the function (based on the pattern of STATIC_FUNCTION(cl_int) text_compare ) working.  The performance however is very slow,   original Postgres functions do the job in 40 secs, cuda version of the same code takes over 6 minutes.   This function takes in data that is about 300-800 chars in length.

It maybe the overhead of calling into the CUDA to schedule the operation that is the culprit,  it would have to make and handle 5 million calls in less than 40 sec of time.  This is why I'm trying to confirm if this approach (trying to optimize a function on the SELECT clause) is a proper use of the technology.

Regards

Tek

**Comment by kaigai** [comment]
Rather than PG-Strom, `pl/Python` + `cuPy` might be a good choice for this use cases.
