### ISSUE TITLE
GpuNestLoop error when doing OUTER JOIN

### ISSUE THREAD

**Issue by exialin** [heterodb/pg-strom#344]
I found multiple relations join result incorrect when testing GpuNestLoop and OUTER JOIN is included. My test environment is as follows:
PostgreSQL: 9.6.8
GPU: GTX 1050 Ti (although not recommended, I think the error might not be related with this)
code version: 140b0b338c32eae069f29909a3fd9d716e3f8539 (master branch)

I created 3 tables `j1`, `j2` and `j3` like this:
```
create table j1 (c1 smallint, c2 smallint);
insert into j1 select generate_series(1,10000), random()*32767/10;
```

In order to test GpuNestLoop, I set `pg_strom.enable_gpuhashjoin` to `off`, then ran the following query:
```
select * from j1 join j2 on j1.c2 = j2.c2 left join j3 on j2.c2 = j3.c2;
```
I found that the number of rows returned is the **same** as that of query `select * from j1 join j2 on j1.c2 = j2.c2 join j3 on j2.c2 = j3.c2`. The query plan shows that depth 1 is `GpuNestLoop` and depth 2 is `GpuNestLoopLeft`.

Besides, the result of `select * from j1 join j2 on j1.c2 = j2.c2 right join j3 on j2.c2 = j3.c2` is also incorrect, compared to original PG query result.

I'm wondering if it is really a bug or there is something wrong with my own environment?

Regards

**Comment by kaigai** [comment]
I will try to investigate the problem you reported this weekend. I'm busy until this Friday. Sorry.

**Comment by exialin** [comment]
I tested on GTX 1080 Ti this time, and found that the problem only happens in case of query `select * from j1 join j2 on j1.c2 = j2.c2 left join j3 on j2.c2 = j3.c2`. The number of rows returned is incorrect and changes each time I ran the same query.

So maybe there is something wrong with `GpuNestLoopLeft`.

**Comment by kaigai** [comment]
Likely, 8d1f0b87e7c9b03de17ab10950b4455533d04b46 fixes the bug.

GpuNestLoop didn't adjust row-index of the LEFT OUTER tuple when it is written to the result buffer.
It eventually generates incorrect results, and leads mismatch from the result by PostgreSQL.

```
postgres=# explain analyze
           select j1.c1 a, j1.c2 b, j2.c1 c, j2.c2 d, j3.c1 e, j3.c2 f
             into pg_temp.hoge1
             from j1 join j2 on j1.c2 = j2.c2 left join j3 on j2.c2 = j3.c2;
                                                       QUERY PLAN
--------------------------------------------------------------------------------------------
 Hash Join  (cost=540.00..2662.90 rows=102614 width=12)
                  (actual time=8.996..43.585 rows=94857 loops=1)
   Hash Cond: (j2.c2 = j1.c2)
   ->  Hash Right Join  (cost=270.00..885.70 rows=32070 width=8)
                                    (actual time=4.484..14.013 rows=31167 loops=1)
         Hash Cond: (j3.c2 = j2.c2)
         ->  Seq Scan on j3  (cost=0.00..145.00 rows=10000 width=4)
                                         (actual time=0.009..1.435 rows=10000 loops=1)
         ->  Hash  (cost=145.00..145.00 rows=10000 width=4)
                         (actual time=4.380..4.380 rows=10000 loops=1)
               Buckets: 16384  Batches: 1  Memory Usage: 480kB
               ->  Seq Scan on j2  (cost=0.00..145.00 rows=10000 width=4)
                                               (actual time=0.011..1.857 rows=10000 loops=1)
   ->  Hash  (cost=145.00..145.00 rows=10000 width=4)
                   (actual time=4.395..4.395 rows=10000 loops=1)
         Buckets: 16384  Batches: 1  Memory Usage: 480kB
         ->  Seq Scan on j1  (cost=0.00..145.00 rows=10000 width=4)
                                         (actual time=0.014..1.869 rows=10000 loops=1)
 Planning time: 18.039 ms
 Execution time: 91.462 ms
(13 rows)
```

```
postgres=# set enable_hashjoin = off;
SET
postgres=# set enable_mergejoin = off;
SET
postgres=# explain analyze
           select j1.c1 a, j1.c2 b, j2.c1 c, j2.c2 d, j3.c1 e, j3.c2 f
             into pg_temp.hoge1
             from j1 join j2 on j1.c2 = j2.c2 left join j3 on j2.c2 = j3.c2;
                                                       QUERY PLAN
--------------------------------------------------------------------------------------------
 Custom Scan (GpuJoin) on j1  (cost=5445.22..5445.22 rows=102614 width=12)
                                                 (actual time=40.026..55.927 rows=94857 loops=1)
   GPU Projection: j1.c1, j1.c2, j2.c1, j2.c2, j3.c1, j3.c2
   Outer Scan: j1  (cost=0.00..145.00 rows=10000 width=4)
                           (actual time=0.693..0.693 rows=10000 loops=1)
   Depth 1: GpuHashJoin  (plan nrows: 10000...31997, actual nrows: 10000...30363)
            HashKeys: j1.c2
            JoinQuals: (j1.c2 = j2.c2)
            KDS-Hash (size plan: 713.00KB, exec: 634.88KB)
   Depth 2: GpuHashLeftJoin  (plan nrows: 31997...102614, actual nrows: 30363...94857)
            HashKeys: j2.c2
            JoinQuals: (j2.c2 = j3.c2)
            KDS-Hash (size plan: 713.00KB, exec: 634.88KB)
   ->  Seq Scan on j2  (cost=0.00..145.00 rows=10000 width=4)
                                   (actual time=0.010..1.024 rows=10000 loops=1)
   ->  Seq Scan on j3  (cost=0.00..145.00 rows=10000 width=4)
                                   (actual time=0.007..1.020 rows=10000 loops=1)
 Planning time: 0.781 ms
 Execution time: 856.244 ms
(15 rows)
```

Here is no difference between two results.
```
postgres=# select * from pg_temp.hoge1 except select * from pg_temp.hoge2;
 a | b | c | d | e | f
---+---+---+---+---+---
(0 rows)

postgres=# select * from pg_temp.hoge2 except select * from pg_temp.hoge1;
 a | b | c | d | e | f
---+---+---+---+---+---
(0 rows)
```
Thanks for your reports!

**Comment by exialin** [comment]
Sorry but I'm afraid this issue is not solved yet...

The plan node in your second query is `GpuHashLeftJoin` instead of `GpuNestLoopLeft`. `set pg_strom.enable_gpuhashjoin = off` and `set pg_strom.enable_gpunestloop = on` should bring up the problem.

Could you please recheck it? Thank you~

**Comment by kaigai** [comment]
Sorry, that is a mistake when I get a screen image after the fixup.

```
postgres=# set enable_hashjoin = off;
SET
postgres=# set enable_mergejoin = off;
SET
postgres=# set pg_strom.enable_gpuhashjoin = off;
SET
postgres=# explain analyze
           select j1.c1 a, j1.c2 b, j2.c1 c, j2.c2 d, j3.c1 e, j3.c2 f
             into pg_temp.hoge2
             from j1 join j2 on j1.c2 = j2.c2 left join j3 on j2.c2 = j3.c2;
                                                          QUERY PLAN
--------------------------------------------------------------------------------
 Custom Scan (GpuJoin) on j1  (cost=5582.03..5582.03 rows=102614 width=12)
                              (actual time=1161.898..1182.844 rows=94857 loops=1)
   GPU Projection: j1.c1, j1.c2, j2.c1, j2.c2, j3.c1, j3.c2
   Outer Scan: j1  (cost=0.00..145.00 rows=10000 width=4)
                   (actual time=0.696..0.697 rows=10000 loops=1)
   Depth 1: GpuNestLoop  (plan nrows: 10000...31997, actual nrows: 10000...30363)
            JoinQuals: (j1.c2 = j2.c2)
            KDS-Heap (size plan: 507.92KB, exec: 429.80KB)
   Depth 2: GpuNestLoopLeft  (plan nrows: 31997...102614, actual nrows: 30363...94857)
            JoinQuals: (j2.c2 = j3.c2)
            KDS-Heap (size plan: 507.92KB, exec: 429.80KB)
   ->  Seq Scan on j2  (cost=0.00..145.00 rows=10000 width=4)
                       (actual time=0.011..0.941 rows=10000 loops=1)
   ->  Seq Scan on j3  (cost=0.00..145.00 rows=10000 width=4)
                       (actual time=0.006..0.926 rows=10000 loops=1)
 Planning time: 0.665 ms
 Execution time: 1869.769 ms
(13 rows)

postgres=# select * from pg_temp.hoge2 except select * from pg_temp.hoge1;
 a | b | c | d | e | f
---+---+---+---+---+---
(0 rows)

postgres=# select * from pg_temp.hoge1 except select * from pg_temp.hoge2;
 a | b | c | d | e | f
---+---+---+---+---+---
(0 rows)
```

**Comment by exialin** [comment]
Sorry I didn't report my problem clearly.

I tested with the latest PG-Strom code, but the problem is still there. At least in my case `pg_temp.hoge2` is a **subset** of `pg_temp.hoge1`. I forced GpuNestLoop by 
```
set pg_strom.gpu_setup_cost = 0;
set pg_strom.enable_gpuhashjoin = off;
```

Besides, my environment is PostgreSQl 9.6.8 and GTX 1080 Ti, though I think it is unlikely to cause the difference.

**Comment by kaigai** [comment]
I have some requests to you.

1. Could you show me your query execution plan with `EXPLAIN`.
1. Could you show me the rows which is contained at `pg_temp.hoge1` (without PG-Strom), but not contained at `pg_temp.hoge2` (with PG-Strom).
1. Are the mismatched rows always identical over the multiple trials?

Thanks,

**Comment by exialin** [comment]
Sorry my testing environment currently has no access to the internet, so I will post some photos to express the problem as clearly as possible.

First, PG-Strom is disabled and run the query:
```
set pg_strom.enabled = off;
explain analyze select j1.c1 a, j1.c2 b, j2.c1 c, j2.c2 d, j3.c1 e, j3.c2 f into temp1 from j1 join j2 on j1.c2 = j2.c2 left join j3 on j2.c2 = j3.c2;
```
The query plan is:
![20180430213730](https://user-images.githubusercontent.com/4889894/39430308-113beeaa-4cc0-11e8-821f-94191f298d19.jpg)

Then, force to use GpuNestLoop and run the query again:
```
set pg_strom.enabled = on;
set pg_strom.gpu_setup_cost = 0;
set pg_strom.enable_gpuhashjoin = off;
explain analyze select j1.c1 a, j1.c2 b, j2.c1 c, j2.c2 d, j3.c1 e, j3.c2 f into temp2 from j1 join j2 on j1.c2 = j2.c2 left join j3 on j2.c2 = j3.c2;
```

This time, GpuNestLoopLeft is in the plan:
![20180430213720](https://user-images.githubusercontent.com/4889894/39430667-fbbfe116-4cc0-11e8-9979-6b818bae98ab.jpg)

The difference between `temp1` and `temp2`:
```
testdb=# select * from temp2 except select * from temp1;
 a | b | c | d | e | f
---+---+---+---+---+---
(0 rows)
```
But the result of `select * from temp1 except select * from temp2` is not empty:
![20180430220145](https://user-images.githubusercontent.com/4889894/39431042-1c19f590-4cc2-11e8-8edd-90906ed64a86.jpg)

As for
> Are the mismatched rows always identical over the multiple trials?

Yes, the result won't change after multiple trials.

Hope this time the problem is clear. Thanks for your effort!

**Comment by kaigai** [comment]
Thanks. If mismatched rows are changed over multiple trials, I doubt problems around synchronization between threads.
It still misses 1202 rows when PG-Strom is enabled, and all the missing rows are generated by OUTER JOIN part (on the other words, column `e` and `f` are NULL. Right?)

**Comment by exialin** [comment]
Yes, but RIGHT JOIN and FULL JOIN are right. I remember the outer path is not pulled up when `right join j3` or `full join j3` (sorry I can't test it now, but that might be related with the problem).

**Comment by kaigai** [comment]
Hmm... I could not reproduce the problem based on PostgreSQL 9.6.8 and GTX1080Ti environment with the latest revision of PG-Strom. Nvidia driver version is 390.30.

Could you ensure the latest PG-Strom is cleanly installed on and PostgreSQL is restarted once again?

**Comment by exialin** [comment]
Well, I noticed that our Nvidia driver versions are different. I was using 387.26, and now I update it to the latest 390.48, then the problem is gone! So the driver could potentially cause error. Amazing...

Thank you very much for your help!
