### ISSUE TITLE
Cannot use In-memory Columnar Cache

### ISSUE THREAD

**Issue by exialin** [heterodb/pg-strom#346]
I was trying to use In-memory Columnar Cache feature of PG-Strom 2.0, but I couldn't make it work.

I created a database `testdb` and set `pg_strom.ccache_databases = testdb` in postgresql.conf. I created a table `j1` and ran `select pgstrom_ccache_enabled('j1');`. `\d j1` shows that the triggers were generated.

But `pgstrom.ccache_info` is empty, and CCache Hits is 0 when I run query on `j1`. I tried `INSERT`, `DELETE` and `UPDATA` on `j1` to trigger the building of cache, but it didn't work.

So, did I miss any steps?

Regards

**Comment by kaigai** [comment]
Could you try `vacuum analyze` on the `j1`, then wait for while, or run `pstrom_ccache_prewarm('j1')`?

I guess PostgreSQL does not create visibility-map yet. It informs other modules whether heap block contains only all-visible tuples, or not.
The ccache behavior is a bit conservative. It caches only 128MB blocks which contains no partially visible records from the point of MVCC.

**Comment by exialin** [comment]
Thanks for your reply!

It seems that ccache works only when the table is big enough (the 128MB threshold). After testing on a bigger table, now caches are successfully generated.
