### ISSUE TITLE
CUDA error occurs when running UPDATE/DELETE

### ISSUE THREAD

**Issue by exialin** [heterodb/pg-strom#347]
When I previously played with In-memory Column Cache as #346 mentioned, I tried to do some DML queries to trigger the building process. Then I encoutered a CUDA error with `UPDATE` or `DELETE`.

For example, I have a table `j1` with two columns `c1` and `c2`. Running `update j1 set c1 = 1 where c2 = 2` would get the following error:
```
WARNING:  failed on cuEventRecord: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered
...
ERROR:    (gpuscan.c:2964) failed on cuEventSynchronize: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered
````

Trying to delete one row from `j1` would get the same error. The problem might be with the GpuScan node in the plan.

Regards

**Comment by kaigai** [comment]
Likely, 4a8c9ba7343d401dc8e0b9bbdcb02551cbe88b0d fixed the problem.
It contained two independent bugs.

1. Loop counter to copy system attribute variables was not signed data type, thus this loop didn't work and system attributes (like `ctid`) were kept uninitialized.
1. gpuscan_projection_tuple() was wrong. It tried to copy `ctid` onto extra-buffer once, however, it is fundamentally unnecessary. Other portion considered the projection task includes `ctid` needs no extra buffer, so `memcpy()` on `NULL` leads GPU kernel crash with `CUDA_ERROR_ILLEGAL_ADDRESS`.
