### ISSUE TITLE
catastrophic error: cannot open source file "utility"

### ISSUE THREAD

**Issue by trunksio** [heterodb/pg-strom#354]
Hi - I am trying to build an nvidia-docker container (from base image nvidia/cuda:9.0-devel based on ubuntu 16.04)
As part of the docker build I am checking out this repo and successfully building / installing - however when I try to compile the sample function
CREATE FUNCTION gpu_add(int, int)
RETURNS int
AS $$
#plcuda_include "cuda_mathlib.h"
#plcuda_begin
  if (get_global_id() == 0)
    *retval = pgfn_int4pl(kcxt, arg1, arg2);
#plcuda_end
$$ LANGUAGE plcuda

I get the following error:
[00000] ERROR: build failure: /usr/local/cuda/include/cuda_fp16.hpp(55): catastrophic error: cannot open source file "utility"

is there some development libraries I am missing from my build?

Thanks,

Lewis.

**Comment by kaigai** [comment]
Please use CUDA 9.1, as documentation says.

**Comment by trunksio** [comment]
Yes - just picked that up. Apologies.
