### ISSUE TITLE
Empty GpuHashJoin result for equal join with arithmetic expression

### ISSUE THREAD

**Issue by exialin** [heterodb/pg-strom#355]
I found that GpuHashJoin result is not right when running query like `select * from j1, j2 where j1.c2 = j2.c2 + 10`.

With the default PG-Strom settings, I would get the following result:
![20180503102709](https://user-images.githubusercontent.com/4889894/39557820-f7144172-4ebc-11e8-8c68-6e8dc2ebb47a.jpg)

Then I disable GpuHashJoin and force to use GpuNestLoop. The result is not **empty** and is the same as that of original PostgreSQL. The plan is as follows:
![20180503102723](https://user-images.githubusercontent.com/4889894/39557879-4cac6448-4ebd-11e8-94c9-f74dad1eed62.jpg)

Regards

**Comment by kaigai** [comment]
Thanks for the corner case report.
In this case, `j1.c2` is smallint (2bytes) but `j2.c2 + 10` is int (4bytes).
These expressions will generate different hash-values for same values, then it leads empty results in GpuHashJoin.

In fact, `select * from j1,j2 where (j1.c1 + 10)::smallint = j2.c1` makes correct results.

I'm now considering a clean way to fix.
