### ISSUE TITLE
PostgreSQL 9.6 has no IS_SIMPLE_REL macro

### ISSUE THREAD

**Issue by exialin** [heterodb/pg-strom#358]
Hello, master.

Commit f69f4f0bf3d0362d72660452fdb96cbab963567f uses `IS_SIMPLE_REL`, but it is not defined in PostgreSQl 9.6. A small fix is needed. :-)

**Comment by kaigai** [comment]
Thanks, 5df581d06d25d6df98a72c62198d221351eed4c2 uses PG9.6 style.
