### ISSUE TITLE
nvme_strom on ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by guiuprado** [heterodb/pg-strom#359]
Hi Kaigai, how you doing!?

I would like to ask a question.

We are trying to build and use pg_strom on Ubuntu 16.04 LTS. 

We need to use this distro of linux because the google cloud only optimize this type of images.

After some research we can start the postgresql 10 with pg_strom (looking this issue #307, and try run without pg_ctlcluster actually work for us).

But we still get a message wen postgres start:

```
PG-Strom: nvme_strom driver is not installed
``` 

So if we don't build nvme module we can`t have the power of NVMe drivers?

If no we will try to setup another instance with centos7 and try to install the NVMe drives.

Thank you very much for help us and maintain this amazing project.

**Comment by kaigai** [comment]
I'm also interested in supporting Ubuntu environment, however, we don't have enough time for the task right now. (As you may know, here are many action items...)

> So if we don't build nvme module we can`t have the power of NVMe drivers?
Yes. And, sorry, because of our business reason, `nvme_strom` driver is kept in binary distribution.

I hope you to use RHEL7/CentOS7 right now.

**Comment by guiuprado** [comment]
Hi @kaigaim thanks for replying. No problem at all. We still want to test the pg_strom.
After some time we create the new instance with all requirements.
It's working but we don't understand why the performance in many cases was slowly when pg_strom was enable and faster when disabled.
The machine created is in CentOS 7 x64 with 32 vCPUs and 120 GB RAM and 4 x 375GB Nvme with stripped into a ext4 1,5TB partition.
We think the slowdown on the queries are caused because some throughput between the GPU, RAM, or Disk.
This thinking came wen we check a constant time in some queries alternating from 12 to 16 seconds. My guess is if the time spend with in/out data to GPU is greater then the time spend processing the query at the GPU.

We use queries with where and group by counter a table fo 11M rows.
Ours queries is in this issues #356.

```
SET pg_strom.enabled = on;
explain analyze select "grupo_atividade_cognatis", sum("faturamento") from "default"."t_total_empresas" group by "grupo_atividade_cognatis";`
```

You have any tip why this happening? Or even some tip to improve the performance?

Thank you very much.

**Comment by kaigai** [comment]
b0e867ee256f2d566891265e4242e70f0615f0da adds GPUDirect Storage supports.
It shall be released 2021Q1 by NVIDIA, a good alternative of NVME-Strom driver.
