### ISSUE TITLE
gstore_fdw column use compress option will failed when insert

### ISSUE THREAD

**Issue by digoal** [heterodb/pg-strom#368]
gstore_fdw , when column use compress option , insert value to it will crash. 

```
postgres=# CREATE FOREIGN TABLE ft (          
    id int,
    signature smallint[] OPTIONS (compression 'pglz')
)
SERVER gstore_fdw OPTIONS(pinning '0', format 'pgstrom');
CREATE FOREIGN TABLE


postgres=# insert into ft values (1,array[1,2,3]);
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> \q
```

but when the compressed column use null , it's ok.

```
postgres=# insert into ft values (1,null);
INSERT 0 1
```

best regards, digoal

**Comment by kaigai** [comment]
06abf8a73d484a09cc58ec794e4d61bfe1cd5d01 fixed the problem.

I didn't test the case when varlena datum is too short to compress the variable using pglz.
If varlena is not suitable for compression, `toast_compress_datum` returns `NULL`, then it leads crash.

**Comment by digoal** [comment]
thank you.
