### ISSUE TITLE
CUDA build failure when select tableoid

### ISSUE THREAD

**Issue by exialin** [heterodb/pg-strom#372]
Hello @kaigai . I ran into the following error:

```
testdb=# select *, tableoid from j1 where c1 < 100;
ERROR:  build failure:
pg-strom(154): error: identifier "htup" is undefined
...
```

`htup` is not in the argument list of function `gpuscan_projection_column`, thus causing the error.

Best Regards

**Comment by kaigai** [comment]
Thanks, fa2c42e9db4e6fdca6efdea6830881c6cb366948 fixes the problem.

`gpuscan_projection_(row|column)` shall never be called when `htup == NULL` or thread refers out of the range. So, we don't check NULL here.
