### ISSUE TITLE
running NOT LIKE '%ABCDEF0' type of query 

### ISSUE THREAD

**Issue by kl3eo** [heterodb/pg-strom#375]
I successfully run this query, SELECT memo from t_10g where memo LIKE '%abcdef0', which sends ~ 20 records to output from 100 million records of t_10g. Then I logically reverse it with NOT LIKE clause and expect the count 99999980. However, that freezes Pg-Strom. The same result when reversing a maths filter like SELECT count(x) from t_10g where sqrt((x-100)^2+(y-200)^2) < 10, by changing '< 10' to '> 10'. Do we run successfully only queries that result in smaller datasets?

**Comment by kaigai** [comment]
Can you provide us `EXPLAIN` results on these queries.
And, does `EXPLAIN ANALYZE` finish correctly?

I doubt too much number of rows gives memory pressure `psql` frontend because it keeps rows to be printed.

**Comment by kl3eo** [comment]
The first query is OK, but
I did cancel of the second query as it would not return in 5 min:

people=# explain analyze select count(*) from t_10g where memo like '%abcdef%';
                                                                        QUERY PLAN                                            
                            
------------------------------------------------------------------------------------------------------------------------------
----------------------------
 Finalize Aggregate  (cost=806835.55..806835.56 rows=1 width=8) (actual time=7510.728..7510.729 rows=1 loops=1)
   ->  Gather  (cost=806835.33..806835.54 rows=2 width=8) (actual time=7510.710..7510.725 rows=3 loops=1)
         Workers Planned: 2
         Workers Launched: 2
         ->  Partial Aggregate  (cost=805835.33..805835.34 rows=1 width=8) (actual time=7224.663..7224.663 rows=1 loops=3)
               ->  Parallel Custom Scan (GpuScan) on t_10g  (cost=28462.76..805824.92 rows=4167 width=0) (actual time=1222.748
..7224.597 rows=57 loops=3)
                     GPU Filter: (memo ~~ '%abcdef%'::text)
                     Rows Removed by GPU Filter: 33333276
 Planning time: 20.168 ms
 Execution time: 7757.764 ms
(10 rows)

people=# explain (analyze,verbose,timing,costs,buffers)  select count(*) from t_10g where memo not like '%abcdef%';
^CCancel request sent
ERROR:  canceling statement due to user request
people=#

**Comment by kl3eo** [comment]
But when you add NVMe-strom,  you will get the query return in feasible time. So the question now is  - does big set result always need NVMe loaded?

people=# set pg_strom.nvme_strom_enabled=on;
SET
people=# set pg_strom.nvme_strom_threshold='512MB';
SET
people=# explain (analyze,verbose,timing,costs,buffers)  select count(*) from t_10g where memo not like '%abcdef%';
                                                                                QUERY PLAN                                    
                                             
------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------
 Finalize Aggregate  (cost=819003.82..819003.83 rows=1 width=8) (actual time=11521.731..11521.731 rows=1 loops=1)
   Output: count(*)
   Buffers: shared read=393261
   ->  Gather  (cost=819003.61..819003.82 rows=2 width=8) (actual time=11301.869..11521.725 rows=3 loops=1)
         Output: (PARTIAL count(*))
         Workers Planned: 2
         Workers Launched: 2
         Buffers: shared read=393261
         ->  Partial Aggregate  (cost=818003.61..818003.62 rows=1 width=8) (actual time=11258.085..11258.085 rows=1 loops=3)
               Output: PARTIAL count(*)
               Buffers: shared read=1234568
               Worker 0: actual time=11349.992..11349.992 rows=1 loops=1
                 Buffers: shared read=431816
               Worker 1: actual time=11122.636..11122.636 rows=1 loops=1
                 Buffers: shared read=409491
               ->  Parallel Custom Scan (GpuScan) on public.t_10g  (cost=25397.89..713847.35 rows=41662503 width=0) (actual ti
me=2752.776..8066.322 rows=33333276 loops=3)
                     GPU Filter: (t_10g.memo !~~ '%abcdef%'::text)
                     Rows Removed by GPU Filter: 57
                     NVMe-Strom: enabled
                     Buffers: shared read=1234568
                     Worker 0: actual time=2688.736..8096.464 rows=34977046 loops=1
                       Buffers: shared read=431816
                     Worker 1: actual time=2719.273..8019.753 rows=33168698 loops=1
                       Buffers: shared read=409491
 Planning time: 7.723 ms
 Execution time: 11867.891 ms
(26 rows)

However there's one more artefact: try maths filter - it gives out different values every time you run it:

people=# SELECT count(*) FROM t_10g WHERE sqrt(abs(x-200) + abs(y-300) + abs(z-400)) < 11;
 count  
--------
 235720
(1 row)

people=# SELECT count(*) FROM t_10g WHERE sqrt(abs(x-200) + abs(y-300) + abs(z-400)) > 11;
  count   
----------
 99403425
(1 row)

people=# SELECT count(*) FROM t_10g WHERE sqrt(abs(x-200) + abs(y-300) + abs(z-400)) > 11;
  count   
----------
 99469343
(1 row)

people=# SELECT count(*) FROM t_10g WHERE sqrt(abs(x-200) + abs(y-300) + abs(z-400)) < 11;
 count  
--------
 236060
(1 row)

**Comment by kl3eo** [comment]
forgot to mention that loading nvme will shorten the time but the count itself would be wrong

like in these

people=# select count(*) from t_10g where memo not like '%bcdefa0%';
^CCancel request sent
ERROR:  canceling statement due to user request
people=# set pg_strom.nvme_strom_enabled=on;
SET
people=# set pg_strom.nvme_strom_threshold='512MB';;
SET
people=# select count(*) from t_10g where memo not like '%bcdefa0%';
  count   
----------
 99442224
(1 row)

people=# select count(*) from t_10g where memo not like '%bcdefa0%';
  count   
----------
 99508320
(1 row)

**Comment by kaigai** [comment]
For more detailed investigation, I think I have to construct equivalent data-set on my local environment.
It looks like your case is on artificial data-set.

Could you send me the query to set up the test tables?
Unfortunately, I'm busy by the 1st week of Aug. But I'll back to the problem. Please wait for a while.

**Comment by kl3eo** [comment]
yep, sure, here is the code:
people=# CREATE TABLE t_10g AS
   SELECT
     generate_series as id,
     (random() * 1000)::float as x,
     (random() * 1000)::float as y,
     (random() * 1000)::float as z,
     md5(generate_series::text) as memo
   FROM
  generate_series(1,100000000);

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
