### ISSUE TITLE
failed on cuCtxSynchronize: CUDA_ERROR_ASSERT - device-side assert triggered

### ISSUE THREAD

**Issue by Eduardo95** [heterodb/pg-strom#376]
When I run JOIN operation（e.g. select count(*) from t1, t2 where t1.c1 = t2.c1）, there is an error. Three functions (cuCtxSynchronize, cuMemFree and cuCtxGetLimit) failed in the process. I am wondering what brought up this problem? Is that because the synchronization between cpu and gpu failed or there was not enough memory? Thanks.

**Comment by kaigai** [comment]
cuCtxSynchronize() just reports the last error reported by asynchronous tasks.
Only GPU kernel can trigger `CUDA_ERROR_ASSERT` error by assertion checks.

Can you find any more detailed log (including filename and lineno) in the logfile?

**Comment by Eduardo95** [comment]
I saw this message when I tried to run the SQL again

pg_strom:5109: void gpujoin_projection_row(kern_gpujoin *, kern_multirels *, kern_data_store *, kern_data_store *, kern_resultbuf *): block: [273,0,0], thread: [760,0,0] Assertion `pos == (pos & ~7)` failed.

**Comment by kaigai** [comment]
Thanks. It looks to me bug around alignment.
Can you provide us a query to reproduce the dataset?
I like to run the workload on my development system.

**Comment by Eduardo95** [comment]
Ok, there are two tables.
Create table t1(c1 integer, c2 double precision);
Create table t2(c1 integer, c2 double precision);
insert into t1 select generate_series(1,10000000), 0.1;
insert into t2 select generate_series(1,10000000), 0.1;
explain (analyze,verbose,costs,buffers,timing) select count(*) from t1 natural join t2;
 Thanks.

**Comment by kaigai** [comment]
Not certain whether it can be reproduced on the latest revision.
