### ISSUE TITLE
I have a problem when I load citus and pg_strom

### ISSUE THREAD

**Issue by hwlicreres** [heterodb/pg-strom#382]
I have a problem when I load citus and pg_strom.I have loaded two extensions : citus and pg_strom , when I started the server , the server outputs some error in logfile,such as:

ERROR: function dump_local_wait_edges() does not exist at character 15
HINT: No function matches the given name and argument types,You might need to add explicit type casts
Error: (cuda_program.c:1370) failed on cuModuleData : CUDA_ERROR_OUT_OF_MEMORY - out of memory

when I am doing some queries,some servers may crash and I have to restart them.

My Operating System is Centos7.5 , I7 7700,16G Ram,GPU is TITAN V postgresql version is 10.4, citus version is 7.4-3, pg_strom version is 2.0, cuda version is 9.2.88

I make 6 worker nodes,citus.replication_model is streaming,citus.shard_count is 60

create xxx( xxx INT8, xxx INT8, xxxx INT4, xxxx INT4, xxxx INT8, xxxx INT4, xxx INT4, xxxx INT2, xxxx VARCHAR(3), xxx VARCHAR(3), xxx INT4, xxxx INT8, xxx INT2,xxx VARCHAR(512), xxxx VARCHAR(8000) );

I insert into 121249776 lines, then I do this query:select count(*) from xxx , the server crash just like I said before.

please help me.

**Comment by kaigai** [comment]
Probably, `cuModuleData` is `cuModuleLoadData`, or you used older version.

I also found a problem around `cuModuleLoadData`. It consumes too much device memory when application loads GPU binary on Volta device. Now I'm under investigation for trouble escalation to NVIDIA.
Device memory usage increases 1.5GB on `cuModuleLoadData`, it is too much.

**Comment by hwlicreres** [comment]
@kaigai  Thankyou for your reply!

**Comment by archenroot** [comment]
@kaigai @hwlicreres - I would like to hear more about possible integration of Citus and PGStorm.

Citus gives us horizontal scalability while we each node can offload aggregations on GPU. I would like to hear how it works guys, any real data results, etc. well welcomed.

Thank you. I am going to test this on CUDA 9.2 or 10.0 as well anyway.

**Comment by jfbaro** [comment]
That's quite a powerful combination (if they work as expected when running side by side) 😍😍

**Comment by kaigai** [comment]
Not certain whether it can be reproduced on the latest revision.
