### ISSUE TITLE
nvme_strom install error

### ISSUE THREAD

**Issue by noprogramnolife** [heterodb/pg-strom#383]
hi;
 I have a trouble  and I hope can get some help. when I install nvme_strom,  Then i get a  below trouble.
 rpm -i nvme_strom-1.3-1.el7.x86_64.rpm
warning: nvme_strom-1.3-1.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 4eb31320: NOKEY
error: Failed dependencies:
        libcuda.so.1()(64bit) is needed by nvme_strom-1.3-1.el7.x86_64

my system's  all libcuda.so.1  and   libcuda.so as below:
[root@localhost pgres]# find / -name libcuda.so.1
/usr/lib/libcuda.so.1
/usr/lib64/libcuda.so.1
[root@localhost pgres]# find / -name libcuda.so
/usr/lib/libcuda.so
/usr/lib64/libcuda.so
/usr/local/cuda-9.2/lib64/stubs/libcuda.so

my   cuda toolkit is 9.2
        kernel: 3.10.0-862.11.6.el7.x86_64
       system:  Red Hat Enterprise Linux Server release 7.4 (Maipo)
       SSD: NVMe-SSD

my  LD_LIBRARY_PATH= $LD_LIBRARY_PATH:/usr/local/cuda-9.2/lib64:/usr/lib64:/usr/lib
       PATH=$PATH:/sbin:/usr/local/cuda/bin

 I think  I had add all path it's in ,but is don't work. can you give me  some suggestions. Thanks

**Comment by kaigai** [comment]
Do you install the CUDA toolkit by RPM?
If you might install it by runfile, RHEL packager might not know about CUDA.

We may need to fix up specfile of RPM, to allow runfile installation, but please wait for a while....
