### ISSUE TITLE
Help needed. adding pg_strom.nvme_strom_enabled=off to postgresql.conf did not work

### ISSUE THREAD

**Issue by kethineni1** [heterodb/pg-strom#385]
Red Hat Enterprise Linux Server release 7.5 (Maipo)
/usr/local/cuda-9.2/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148
NVIDIA-SMI 396.44                 Driver Version: 396.44

018-09-18 20:03:28.029 PDT [95386] LOG:  PG-Strom built for PostgreSQL 10
2018-09-18 20:03:29.778 PDT [95386] LOG:  PG-Strom: GPU0 Tesla P100-PCIE-16GB (3584 CUDA cores; 1328MHz, L2 4096kB), RAM 15.90GB (4096bits, 698MHz), CC 6.0
2018-09-18 20:03:32.503 PDT [95386] FATAL:  failed on opendir('/sys/class/nvme'): No such file or directory
2018-09-18 20:03:32.503 PDT [95386] LOG:  database system is shut down

**Comment by kaigai** [comment]
Oops, I didn't consider the hardware which have no nvme devices.
`pg_strom.nvme_strom_enabled` controls run-time storage engine only, but your problem is around the startup code that collects device information.
I'll fix up soon.

**Comment by kethineni1** [comment]
Thanks a lot Kai

**Comment by kaigai** [comment]
Likely, fffc613dd91424c46279468417132021fb8428f9 shall fix the problem.

Thanks,

**Comment by kethineni1** [comment]
Confirming the fix worked. Thanks.
