### ISSUE TITLE
CUDA 10.0 - could not load library "/usr/pgsql-10/lib/pg_strom.so": libnvrtc.so.9.2

### ISSUE THREAD

**Issue by jspinella** [heterodb/pg-strom#393]
After reviewing similar issues here, I believe this issue hasn't been addressed yet.

I'm closely following the official pg_strom guide, and am at the part where I finally start Postgres server via `systemctl start postgresql-10` which fails.` journalctl -xe` shows this error:

**could not load library "/usr/pgsql-10/lib/pg_strom.so": libnvrtc.so.9.2: cannot open shared object file: No such file or directory**

Sure enough, I don't see a `libnvrtc.so.9.2` in [/usr/local/cuda-10.0/targets/x86_64-linux/lib/ ](url)but there is a `libnvrtc.so.10.0`. 

I am using pg_strom-PG10 with PostgreSQL 10 and I was able to initdb via `initdb -D /var/lib/pgdata/` successfully so I am rather certain the issue is with the CUDA library and that I need CUDA 9.2 to get around this roadblock, however the 9.0 version of the RPM from Nvidia.com also installs CUDA 10....

I think I can just change the reference to libnvrtc.so.9.2 to libnvrtc.so.10, but I am not sure how or where to do that, editing the pg_strom.so file directly seems sketchy and I wonder if it will result in unintended issues?

**Comment by kaigai** [comment]
The problem is `-lnvrtc` option on build tries to include `libnvrtc.so.<major>.<minor>`, even though CUDA toolkit provides `/usr/local/cuda/lib64/libnvrtc.so` as universal location.
```
$ readelf -d pg_strom.so

Dynamic section at offset 0xb1ad8 contains 28 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libnvrtc.so.10.0]
 0x0000000000000001 (NEEDED)             Shared library: [libcuda.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000001d (RUNPATH)            Library runpath: [/usr/local/pgsql-10/lib]
 0x000000000000000c (INIT)               0x20620
 0x000000000000000d (FINI)               0x869c8
     :
```
I'm looking for an option of `ld` command not to solve symbolic link on `-l` but works in progress.

**Comment by jspinella** [comment]
I see. Is there something I can do in the meantime to get the ball rolling again? I see your output of readelf is showing so.10.0 rather than so.9.2?

**Comment by kaigai** [comment]
I'm looking for a way to embed `libnvrtc.so`; with no version info, to be managed by packager.
If not possible, an alternative is to solve symbols by PG-Strom itself, as we did in the former version.
https://github.com/heterodb/pg-strom/blob/master/deadcode/opencl_entry.c#L1366

**Comment by drgarciafuentes** [comment]
I experienced the same issue after a fresh install of PostgreSQL-10/pg_strom-PG10 on CentOS 7.5.
I can see a couple of version under the url https://heterodb.github.io/swdc/

pg_strom-PG10-2.0-180713.el7.x86_64.rpm
pg_strom-PG10-2.0-180723.el7.x86_64.rpm
pg_strom-PG10-2.0-1.el7.x86_64.rpm

Is any of these packages containing the fix? If yes, the repo might be pointing to the buggy version. If not, when is the next RPM package schedule to be released.

Thanks in advance.

**Comment by kaigai** [comment]
Sorry, I'm now quite busy for the preparation of PGconf.EU next week.
Could you wait for my back from Lisbbon?

**Comment by jspinella** [comment]
Yes, of course! Thanks again.

**Comment by drgarciafuentes** [comment]
I totally understand your commitment to PGconf.EU and the lack of time, being there done that. But, could you at least confirm the main branch fixes the issue and is safe to compile so we can replace the buggy pg_strom.so until you have the time for an RPM/DEB release?
Thanks.

**Comment by drgarciafuentes** [comment]
**Solved:** 
Reviewed the patches referred by @kaigai on [edcfca2](https://github.com/heterodb/pg-strom/commit/edcfca2e54e85b984e7546ebc6d3f15e84c5ca34) STABLE_v1 brach.
Cloned the branch, compiled as indicated in documentation, and replaced the pg_strom.so file (RPM version) at /usr/pgsql-10/lib/pg_strom.so with the new one.
PostgreSQL-10 server starts and loads pg_strom successfully.


> postgresql-10.service - PostgreSQL 10 database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql-10.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/postgresql-10.service.d
           └─pg_strom.conf
   Active: active (running) since Mon 2018-10-22 11:44:32 CDT; 2s ago
     Docs: https://www.postgresql.org/docs/10/static/
  Process: 15122 ExecStartPre=/usr/pgsql-10/bin/postgresql-10-check-db-dir ${PGDATA} (code=exited, status=0/SUCCESS)
 Main PID: 15129 (postmaster)
   CGroup: /system.slice/postgresql-10.service
           ├─15129 /usr/pgsql-10/bin/postmaster -D /var/lib/pgsql/10/data/
           ├─15153 postgres: logger process
           ├─15155 postgres: bgworker: PG-Strom Program Builder-1
           ├─15156 postgres: bgworker: PG-Strom Program Builder-0
           ├─15157 postgres: bgworker: PG-Strom GPU memory keeper
           ├─15158 postgres: checkpointer process
           ├─15159 postgres: writer process
           ├─15160 postgres: wal writer process
           ├─15161 postgres: autovacuum launcher process
           ├─15162 postgres: stats collector process
           ├─15163 postgres: bgworker: PG-Strom ccache-builder2
           ├─15164 postgres: bgworker: PG-Strom ccache-builder1
           └─15165 postgres: bgworker: logical replication launcher

**Comment by drgarciafuentes** [comment]
closed

**Comment by kaigai** [comment]
I made a newer package `pg_strom-PG10-2.0-181106` that contains the feature above.
