### ISSUE TITLE
Build failure. PG-Strom unable to compile *.gpu files.

### ISSUE THREAD

**Issue by drgarciafuentes** [heterodb/pg-strom#394]
Hello @kaigai,

After fixing the problem described in #393. I had yet another problem while benchmarking the server performance with one DB with PG-Strom extension disabled and another DB with PG-Strom enabled.
The same two queries are executed in each database but the second query throws an error stating that Pg-Strom was unable to compile the cuda code inside a *.gpu file, see below.

> ERROR: build failure: /usr/pgsql-10/share/extension/cuda_gpuscan.h(224): error: function "gpuscan_projection_tuple" was referenced but not defined /usr/pgsql-10/share/extension/cuda_gpuscan.h(233): error: function "gpuscan_projection_column" was referenced but not defined 2 errors detected in the compilation of "pg-strom". source: /var/lib/pgsql/10/data/pgsql_tmp/pgsql_tmp_strom_11835.1.gpu SQL state: 00000

I'm not sure if this is the result of what I had to do to resolve issue #393 and get the module to load or it is actually a bug. Below are the queries I am using for testing, very simple ones.

`CREATE TABLE t_test AS
SELECT x, 'a'::char(100) AS y, 'b'::char(100) AS z
FROM   generate_series(1, 5000000) AS x
ORDER BY random();
SELECT 5000000`

`SELECT Count(*) 
FROM public.t_test 
WHERE sqrt(x) > 0
GROUP BY y;`

My environment: CentOS 7.5, NVIDIA GP104 [GeForce GTX 1080], Intel Xeon E3-1200, 15 Gb RAM (DDR4 2133 MHz, Root "/" FS on 250GB Samsung SSD 860, Partition "/var" FS on 500GB Samsung SSD 860)

Any ideas?

**Comment by kaigai** [comment]
Could you give us GPU source code which is displayed at `EXPLAIN VERBOSE` if `pg_strom.debug_kernel_source = on`?

**Comment by drgarciafuentes** [comment]
Hello Kaigi, here is the referred code by `EXPLAIN VERBOSE` and `SET pg_strom.debug_kernel_source = on`

>#include <cuda_device_runtime_api.h>
#define BLCKSZ 8192
#define MAXIMUM_ALIGNOF 8
#define NAMEDATALEN 64
#define KERN_CONTEXT_VARLENA_BUFSZ 1
#include "cuda_common.h"
#define PG_BOOLOID 16
#define PG_INT2OID 21
#define PG_INT4OID 23
#define PG_INT8OID 20
#define PG_FLOAT2OID 17147
#define PG_FLOAT4OID 700
#define PG_FLOAT8OID 701
#define PG_CASHOID 790
#define PG_UUIDOID 2950
#define PG_MACADDROID 829
#define PG_INETOID 869
#define PG_CIDROID 650
#define PG_DATEOID 1082
#define PG_TIMEOID 1083
#define PG_TIMETZOID 1266
#define PG_TIMESTAMPOID 1114
#define PG_TIMESTAMPTZOID 1184
#define PG_INTERVALOID 1186
#define PG_BPCHAROID 1042
#define PG_VARCHAROID 1043
#define PG_NUMERICOID 1700
#define PG_BYTEAOID 17
#define PG_TEXTOID 25
#define PG_INT4RANGEOID 3904
#define PG_INT8RANGEOID 3926
#define PG_TSRANGEOID 3908
#define PG_TSTZRANGEOID 3910
#define PG_DATERANGEOID 3912
#define GPUSCAN_KERNEL_REQUIRED                1
#define GPUSCAN_HAS_DEVICE_PROJECTION          1
#define GPUSCAN_DEVICE_PROJECTION_NFIELDS      1
#define GPUSCAN_HAS_WHERE_QUALS                1
#include "cuda_dynpara.h"
#include "cuda_mathlib.h"
#include "cuda_primitive.h"
typedef union {
    pg_varlena_t     varlena_v;
    pg_bool_t        bool_v;
    pg_int2_t        int2_v;
    pg_int4_t        int4_v;
    pg_int8_t        int8_v;
   pg_float2_t      float2_v;
    pg_float4_t      float4_v;
    pg_float8_t      float8_v;
#ifdef CUDA_NUMERIC_H
    pg_numeric_t     numeric_v;
#endif
#ifdef CUDA_MISC_H
    pg_money_t       money_v;
    pg_uuid_t        uuid_v;
    pg_macaddr_t     macaddr_v;
    pg_inet_t        inet_v;
    pg_cidr_t        cidr_t;
#endif
#ifdef CUDA_TIMELIB_H
    pg_date_t        date_v;
    pg_time_t        time_v;
    pg_timestamp_t   timestamp_v;
    pg_timestamptz_t timestamptz_v;
    pg_interval_t    interval_v;
#endif
#ifdef CUDA_TEXTLIB_H
    pg_bpchar_t      bpchar_v;
    pg_text_t        text_v;
    pg_varchar_t     varchar_v;
#endif
#ifdef CUDA_RANGETYPE_H
    pg_int4range_t   int4range_v;
    pg_int8range_t   int8range_v;
#ifdef CUDA_TIMELIB_H
    pg_tsrange_t     tsrange_v;
    pg_tstzrange_t   tstzrange_v;
    pg_daterange_t   daterange_v;
#endif
#endif
#ifdef CUDA_MATRIX_H
    pg_array_t       array_v;
    pg_matrix_t      matrix_v;
#endif
  } pg_anytype_t;
#include "cuda_gpuscan.h"
STATIC_FUNCTION(cl_bool)
gpuscan_quals_eval(kern_context *kcxt,
                   kern_data_store *kds,
                   ItemPointerData *t_self,
                   HeapTupleHeaderData *htup)
{
  void *addr __attribute__((unused));
  pg_float8_t KPARAM_0 = pg_float8_param(kcxt,0);
 pg_int4_t KVAR_1;
  addr = kern_get_datum_tuple(kds->colmeta,htup,0);
  KVAR_1 = pg_int4_datum_ref(kcxt,addr);
  return EVAL(pgfn_float8gt(kcxt, pgfn_dsqrt(kcxt, pgfn_to_float8(kcxt, KVAR_1)), KPARAM_0));
}
STATIC_FUNCTION(cl_bool)
gpuscan_quals_eval_column(kern_context *kcxt,
                          kern_data_store *kds,
                          cl_uint row_index)
{
  void *addr __attribute__((unused));
  pg_float8_t KPARAM_0 = pg_float8_param(kcxt,0);
  pg_int4_t KVAR_1;
  addr = kern_get_datum_column(kds,0,row_index);
  KVAR_1 = pg_int4_datum_ref(kcxt,addr);
  return EVAL(pgfn_float8gt(kcxt, pgfn_dsqrt(kcxt, pgfn_to_float8(kcxt, KVAR_1)), KPARAM_0));
}
STATIC_FUNCTION(void)
gpuscan_projection_tuple(kern_context *kcxt,
                         kern_data_store *kds_src,
                         HeapTupleHeaderData *htup,
                         ItemPointerData *t_self,
                         Datum *tup_values,
                         cl_bool *tup_isnull)
{
  void    *addr __attribute__((unused));
  cl_int   len __attribute__((unused));
  EXTRACT_HEAP_TUPLE_BEGIN(addr, kds_src, htup);
  EXTRACT_HEAP_TUPLE_NEXT(addr);
  tup_isnull[0] = !addr;
  if (addr)
    tup_values[0] = PointerGetDatum(addr);
  EXTRACT_HEAP_TUPLE_END();
}
STATIC_FUNCTION(void)
gpuscan_projection_column(kern_context *kcxt,
                          kern_data_store *kds_src,
                          size_t src_index,
                          Datum *tup_values,
                          cl_bool *tup_isnull)
{
  void    *addr __attribute__((unused));
  cl_uint  len  __attribute__((unused));
  addr = kern_get_datum_column(kds_src,1,src_index);
  tup_isnull[0] = !addr;
  if (addr)
    tup_values[0] = PointerGetDatum(addr);
}
#include "cuda_terminal.h"

**Comment by drgarciafuentes** [comment]
Hello @kaigai, any news on this matter?

**Comment by kaigai** [comment]
It is strange because `gpuscan_projection_tuple` and `gpuscan_projection_column` are exactly declared, however, compiler concerned about.

Can you check /usr/pgsql-10/share/extension/cuda_gpuscan.h in your environment declares above functions with identical arguments types?

**Comment by drgarciafuentes** [comment]
Hello @kaigai,

I checked the file `/usr/pgsql-10/share/extension/cuda_gpuscan.h` and compared with the code submitted above. In both function definitions there is an additional parameter `char *extra_buf` defined in the header file which is not present on the code that fails to compile.
That is the only difference I can see.

**Comment by kaigai** [comment]
Ah, you may mixture different revision of PG-Strom.
I recently (about 1 month before) added an infrastructure of GPU kernel to modify variable-length data on the fly. This `extra_buf` argument was added at that time.

Could you install the `pg_strom-PG10-2.0-181106` to overwrite files entirely, then restart the system.

**Comment by drgarciafuentes** [comment]
The `pg_strom-PG10-2.0-181106` update package resolved the issue, thank you.

On that happy note, do you have any documentation for the test benchmark on the master branch, you seem to be using dbt3 test suite?
`https://github.com/heterodb/pg-strom/blob/master/test/testdb_init.sql`

Any specific config, setup or details to run the test? It will be great if your documentation material include some of that.
Thanks

**Comment by kaigai** [comment]
We usually run star-schema benchmark.
TPC-H/DBT-3 contains several complicated queries which make inefficient results, and rarely used for massive log processing.
The latest results are published inside of my presentation at PGconf.EU
https://www.slideshare.net/kaigai/20181016pgconfeussd2gpumulti

It shows full-scan with JOIN/GROUP BY on 1TB table finished less than 80s (~13.5GB/s).

**Comment by kaigai** [comment]
Anyway, issue is closed.
Please use mailing-list for further Q&A.
