### ISSUE TITLE
gpuscan_exec_quals_row kernel error

### ISSUE THREAD

**Issue by jbrindle** [heterodb/pg-strom#397]
This happens for me on master and using the release binaries. PG10.

postgres=# select user_screen_name, tweet_text from tweets where tweet_text like '%help%';
ERROR:  (gpu_context.c:743) GPU kernel error - CPU ReCheck at cuda_textlib.h:850 by gpuscan_exec_quals_row

I can do other text like queries fine. The data set is the IRA twitter archive from:
https://about.twitter.com/en_us/values/elections-integrity.html#data

**Comment by kaigai** [comment]
Please try `SET pg_strom.cpu_fallback = on`.

In some cases, GPU kernel cannot process its operation on GPU device side.
(E.g, text datum would be too long for inline representation)
L850 of cuda_textlib.h says, either of left/right of the like operator is compressed or externally stored by toast mechanism of PostgreSQL.

CPU fallback mechanism runs it on CPU side again. So, as long as small number of rows contains long text, it makes sense.

**Comment by jbrindle** [comment]
Got it, that fixed it. Thank you.
