### ISSUE TITLE
PostgreSQL log file - WARNING: schema "pgstrom" was not found.

### ISSUE THREAD

**Issue by drgarciafuentes** [heterodb/pg-strom#398]
Hello @kaigai,

I can't find a way to turn off this warnings on the log file. Your documentation does not contain details about it.

`2018-11-15 19:04:46.194 CST [17822] WARNING:  schema "pgstrom" was not found
2018-11-15 19:04:46.194 CST [17822] HINT:  Run: CREATE EXTENSION pg_strom`

I know that creating the extension on every database would remove the log entry but, not all the databases are going to have pgstrom enabled. Could you please indicate how to suppress these warning so the log files do not grow out of proportion?

Thanks.

**Comment by kaigai** [comment]
Could you check whether the extension is exactly installed on the database where the log message is generated.

`select * from pg_namespace where nspname = 'pgstrom'`

and

`select * from pg_extension where extname = 'pg_strom'`

**Comment by drgarciafuentes** [comment]
I cleaned up and started from fresh after we solved the previous issues. The logs are being generated from the main db `postgres`, so none of the basic cluster databases (`postgres, template0, template1`) have the extension created.

I assumed that I could load the extension per db as needed. Is it mandatory to create the extension in all of the main cluster databases?

**Comment by kaigai** [comment]
> I assumed that I could load the extension per db as needed.

No, unfortunately. PG-Strom is loaded on PostgreSQL startup time, however, it internally assumes some database objects (its own functions, operators, ...) are installed.
Database objects must be created using DDL for each database.

Or, run `CREATE EXTENSION` at `postgres` and `template1` on the installation time,
Other new databases shall inherit configuration of `template1`, so no need to run the command any more.

**Comment by drgarciafuentes** [comment]
Alright, that certainly fixed the issue. I'll move other related questions to the mailing list.
Thanks.
