### ISSUE TITLE
ERROR: failed on cuCtxCreate: CUDA_ERROR_OUT_OF_MEMORY - out of memory

### ISSUE THREAD

**Issue by drgarciafuentes** [heterodb/pg-strom#400]
Hello @kaigai,

Here is another error I get when benchmarking the server with pgbench and a custom script (Select only with 5 table JOINS). Pgbench was executed with the following options:
`pgbench -c 100 -j 100 -T 300 -U pguser -n -f /root/query-file.sql database`

When executed each of the 100 pgbench clients gets the same error:
`client ## aborted in command 0 of script 0; ERROR: failed on cuCtxCreate: CUDA_ERROR_OUT_OF_MEMORY - out of memory`

Disabling pgstrom at the start of the script allows pgbench to run without problems.
The server has 15G of RAM and looking at the memory utilization graph it does not seem to be using all of it.

**Comment by drgarciafuentes** [comment]
Makes sense. So, what's your recommendation for max allowed concurrency based on available memory, e.g, NVIDIA Tesla V100 32GB?
Is it possible to enforce a limit to the number of GPU contexts in PG-Strom?

thanks

**Comment by kaigai** [comment]
Depending on the query and data.

In general, I expect 4-5 parallel queries from my experiences. It is not far from usual analytics & batch processing.

And, CUDA MPS is enhanced for Volta-series. It is valuable to check.
https://docs.nvidia.com/deploy/mps/index.html
