### ISSUE TITLE
GPU Scan and GPU filter not working

### ISSUE THREAD

**Issue by ayanray089** [heterodb/pg-strom#406]
Hi ,

I am trying to analyze a query on below table with 5 mil rows:
```
CREATE TABLE t_test_1 AS
 
SELECT       x, 'a'::char(100) AS y, 'b'::char(100) AS z
 
FROM   generate_series(1, 5000000) AS x
 
ORDER BY random();
```
Analyzing the below query:
```
explain (analyze,verbose,timing,costs,buffers)

SELECT count(*)
 
FROM   postgres.public.t_test_1
 
WHERE sqrt(x) > 0
 
GROUP BY y;

The plan is below:

GroupAggregate  (cost=99034.18..99038.27 rows=1 width=109) (actual time=1463.815..1463.815 rows=1 loops=1)
  Output: pgstrom.sum((pgstrom.nrows())), y
  Group Key: t_test_1.y
  Buffers: shared hit=147077
  ->  Sort  (cost=99034.18..99035.20 rows=408 width=109) (actual time=1463.796..1463.797 rows=3 loops=1)
        Output: (pgstrom.nrows()), y
        Sort Key: t_test_1.y
        Sort Method: quicksort  Memory: 25kB
        Buffers: shared hit=147077
        ->  Gather  (cost=98973.14..99016.49 rows=408 width=109) (actual time=1358.588..1479.223 rows=3 loops=1)
              Output: (pgstrom.nrows()), y
              Workers Planned: 2
              Workers Launched: 2
              Buffers: shared hit=147077
              ->  Parallel Custom Scan (GpuPreAgg) on public.t_test_1  (cost=97973.14..97975.69 rows=204 width=109) (actual time=1213.433..1213.445 rows=1 loops=3)
                    Output: (pgstrom.nrows()), y
                    Reduction: Local
                    GPU Projection: t_test_1.y, pgstrom.nrows(), t_test_1.x
                    Outer Scan: public.t_test_1  (cost=1666.67..97647.62 rows=694445 width=101) (actual time=86.117..1417.750 rows=0 loops=1)
                    Outer Scan Filter: (sqrt((t_test_1.x)::double precision) > '0'::double precision)
                    GPU Preference: None
                    Buffers: shared hit=65440
                    Worker 0: actual time=1143.683..1143.691 rows=1 loops=1
                      Buffers: shared hit=41704
                    Worker 1: actual time=1138.665..1138.675 rows=1 loops=1
                      Buffers: shared hit=39933
Planning time: 0.446 ms
Execution time: 1556.337 ms
```

I can see from the plan that it's not using GPU Filter and GPU Scan(Bulk) and that is why probably it is much slower than expected in the initial scan part and the GPU also probably is not filtering anything before sending to CPU. Can you please point us to right reason for the issue?

**Comment by kaigai** [comment]
Please use quotation tag for better view.

Anyway, it exactly uses GPU. The GpuPreAgg plan also scans on `public.t_test_1` table, and `(sqrt((t_test_1.x)::double precision) > '0'::double precision)` shall be executed on device.

**Comment by ayanray089** [comment]
@kaigai Thanks for your response!

{% quote %}
Outer Scan: public.t_test_1  (cost=1666.67..97647.62 rows=694445 width=101) (actual time=86.117..1417.750 rows=0 loops=1)
{% endquote %}

Shouldn't it have been GPUScan (Bulk) instead of Outer Scan?


The above query is slower than Postgres when executed on 5 million rows. Hence, trying to investigate the plan generated where is the slowness coming from.

**Comment by kaigai** [comment]
`Parallel Custom Scan (GpuPreAgg) on public.t_test_1` does both of scan and aggregation at once.
It internally loads the `public.t_test_1` table, so no individual `GpuScan` node is needed.
This design eliminates data exchange on CPU from GpuScan to GpuPreAgg.

> The above query is slower than Postgres when executed on 5 million rows.
It is not strange. 5 million rows are too small for PG-Strom.
(Probably, most of time is consumed by GPU device initialization at CUDA driver)

It is designed to process billion rows more than system memory, by utilization of NVME-SSD and GPU.
It is typically suitable for log processing workloads.

**Comment by ayanray089** [comment]
Thanks @kaigai ! Appreciate your prompt response.
