### ISSUE TITLE
Support for Analytical functions

### ISSUE THREAD

**Issue by ayanray089** [heterodb/pg-strom#407]
Hi,

Seems like PgStrom does not execute analytical/window functions on GPU.

Query:
explain (analyze,verbose,timing,costs,buffers)

SELECT x,y,z, rank() over (partition by y order by x) count
 
FROM   postgres.public.t_test_1;

Plan:

WindowAgg  (cost=27141003.78..29141004.10 rows=100000016 width=214) (actual time=246116.402..357246.487 rows=100000000 loops=1)
  Output: x, y, z, rank() OVER (?)
  Buffers: shared hit=2912 read=2938265, temp read=2641888 written=2641915
  ->  Sort  (cost=27141003.78..27391003.82 rows=100000016 width=206) (actual time=246116.390..302591.590 rows=100000000 loops=1)
        Output: x, y, z
        Sort Key: t_test_1.y, t_test_1.x
        Sort Method: external merge  Disk: 21135104kB
        Buffers: shared hit=2912 read=2938265, temp read=2641888 written=2641915
        ->  Seq Scan on public.t_test_1  (cost=0.00..3941177.16 rows=100000016 width=206) (actual time=0.022..23411.803 rows=100000000 loops=1)
              Output: x, y, z
              Buffers: shared hit=2912 read=2938265
Planning time: 0.150 ms
Execution time: 361193.179 ms

Can you please suggest if I'm missing something?

Thanks!

**Comment by kaigai** [comment]
Yes, it is not supported except for a corner case.

If you use a foreign-table by Gstore_fdw, sorting operation is pushed down to the GPU-side, so CPU can skip sorting. It may be beneficial for window-function, however, note that number of rows are restricted by GPU memory.

**Comment by ayanray089** [comment]
Thanks @kaigai

**Comment by yjhjstz** [comment]
@kaigai where is the code for GPU-side sort ?

**Comment by kaigai** [comment]
It was removed, because ...
- Sort does not reduce number of rows; that means we have to move tons of data from device to host, not only host to device.
- GpuSort makes sense only if large dataset, however, large dataset also takes larger bandwidth consumption between CPU/GPU.

You can see the deprecated code at:
https://github.com/heterodb/pg-strom/blob/master/deadcode/cuda_gpusort.h
