### ISSUE TITLE
Scale-out of pgStrom

### ISSUE THREAD

**Issue by ayanray089** [heterodb/pg-strom#408]
Hi,

Is it possible to scale out PgStrom using other postgres extensions like Citusdata or Greenplum.
If done, will it still be able to leverage the GPU power?
Does PgStrom work with Postgres 11?

**Comment by kaigai** [comment]
> Is it possible to scale out PgStrom using other postgres extensions like Citusdata or Greenplum.
> If done, will it still be able to leverage the GPU power?
>
I don't know about Greenplum, however, I had tested (just tested) CitusDB with PG-Strom in the past.
When I installed PG-Strom for all the worker node of CitusDB, it used GPU-aware query execution plan on every worker node.
Please note that it is NOT a dedicated evaluation, just a trial.

> Does PgStrom work with Postgres 11?
Yes. Bugs reports are welcome.
