### ISSUE TITLE
PgStrom performance

### ISSUE THREAD

**Issue by ayanray089** [heterodb/pg-strom#412]
Hi @kaigai ,

Aggregate query takes 346 ms in Omnisci whereas it takes 26339ms in PgStrom and 34422ms in Postgres

Can you explain what is the reason of slowness for PgStrom over Omnisci/MapD even though it's leveraging GPU.

**Comment by kaigai** [comment]
It is likely I/O (data transfer between RAM and GPU) and data format (row-based of PostgreSQL).
Probably, Map-D contains all the data on GPU device RAM, thus no I/O stuff happen and they designed the database from the scratch to adopt optimized data-format; here is benefit and pain.
This approach will not work for terabytes scale data because GPU RAM is much smaller than the storage size.
And, an approach to support optimized data-format (columnar-storage) is under works for PG-Strom also.

**Comment by ayanray089** [comment]
Thanks @kaigai for your response. For terabytes of data, I think we have two options in MapD
1. set watchdog = false , which will allow the query to run in stages on the GPU
2. allow-cpu-retry = true, to direct queries, that do not fit in the GPU memory available, to fall back and be executed on the CPU

**Comment by kaigai** [comment]
I'm not certain for Map-D configuration.

In general, storage design is key of performance for the data size more than memory.
And, I didn't heard Map-D (and other GPU database) has special optimization in this area.

At a conference in Tokyo, I saw Map-D folks presented 1-2GB/s query execution throughput
is expected if data is stored in cold storage (NVME-SSD).
On the other hands, it is a strong point for PG-Strom.

I recommend that these products are designed for different purpose, and different workloads.

**Comment by kaigai** [comment]
This is the slides they presented. I got a T-shirt of Map-D here.
https://www.slideshare.net/InsightTechnology/db-tech-showcase-tookyo-2018dbts2018-b24-speed-meets-scale-analyzing-visualizing-billions-of-data-points-with-gpus/12

**Comment by ayanray089** [comment]
Thanks @kaigai !

**Comment by mlazatinph** [comment]
> And, an approach to support optimized data-format (columnar-storage) is under works for PG-Strom also.

I'm excited for this. Will this happen this year? Next year? In the next 5 years?

**Comment by kaigai** [comment]
> I'm excited for this. Will this happen this year? Next year? In the next 5 years?

About this topic, I will have a presentation at the seminar tomorrow. :-)
https://www.sraoss.co.jp/event_seminar/2019/0418.php

We already have benchmark result of SSD2GPU Direct SQL on Arrow_Fdw (columnar-storage).
It needs a few more weeks for documentation in English. Please wait for that.

**Comment by mlazatinph** [comment]
Oh wow! Nice! Good luck on your presentation tomorrow :-)

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
