### ISSUE TITLE
Missing "KDS_CALCULATE_SLOT_LENGTH" 

### ISSUE THREAD

**Issue by yu45020** [heterodb/pg-strom#414]
I build the extension from the master branch. Postgres is able to detect my single GPU when I use "explain ...." but fails when I drop "explain" and run queries:

``/usr/share/postgresql/11/extension/cuda_gpupreagg.h(480): error: identifier "KDS_CALCULATE_SLOT_LENGTH" is undefined``

I bypass the error by commenting out the following lines in [gpupreagg](https://github.com/heterodb/pg-strom/blob/b9594b41d38eff0fe6463b32996fceee5bf65e2f/src/gpupreagg.c#L1063)
 
```c
	kds_length = (KDS_CALCULATE_SLOT_LENGTH(ncols, nrooms) +
				  STROMALIGN(extra_sz) * nrooms);
	// unified memory eliminates limitation of the device memory
	// however, some penalty is needed for large buffer
	if (kds_length > gpuMemMaxAllocSize())
return false; /* expected buffer size is too large */

```

and [cuda_gpupreagg](https://github.com/heterodb/pg-strom/blob/a83715434ad01c797eae11dde974f1919ef5415c/src/cuda_gpupreagg.h#L480)

```c
			if (KDS_CALCULATE_SLOT_LENGTH(kds_slot->ncols, newval.i.nitems) +
				__kds_unpack(newval.i.usage) > kds_slot->length)
			{
				suspend_kernel = true;
				atomicAdd(&kgpreagg->suspend_count, 1);
				break;
}
```

My queries are running with GPU now, and I have not hit an error yet.

**Comment by kaigai** [comment]
Thanks for your report.
Fixed at 9ef9ede89441af6a48cf0e82cfd32b94ef4a05b0
