### ISSUE TITLE
build error on mac

### ISSUE THREAD

**Issue by gaos1** [heterodb/pg-strom#415]
is there any guideline to build and install pg-strom on a mac pro, e.g. osx 10.13?

I got the following error: 
```
src/pg_strom.h:170:10: fatal error: 'sys/vfs.h' file not found
#include <sys/vfs.h>
         ^~~~~~~~~~~
1 error generated.
make: *** [src/main.o] Error 1
```

**Comment by kaigai** [comment]
See the checklist here.
http://heterodb.github.io/pg-strom/install/#checklist

PG-Strom now supports Linux on x86_64 operating system only.

**Comment by gaos1** [comment]
Thanks. I only have a mac with GPU at this moment. could you give me some hints if I want to dig into the code and make it work on mac?  what changes I might need to look into?  or it is almost impossible?

**Comment by kaigai** [comment]
PG-Strom references /sys to get hardware information for optimization purpose. I believe this pseudo filesystem is specific to Linux.
Anyway, macOS is not designed for server usage. I like to recommend to use PG-Strom on the validated hardware configuration.
https://github.com/heterodb/pg-strom/wiki/002:-HW-Validation-List
