### ISSUE TITLE
ERROR: Bug? no relevant Var-node reference in child rel: {VAR :varno 1 :varattno 2 :vartype 1082 :vartypmod -1 :varcollid 0 :varlevelsup 0 :varnoold 1 :varoattno 2 :location 7}

### ISSUE THREAD

**Issue by mlazatinph** [heterodb/pg-strom#417]
I am using Postgresql v10.7 on Ubuntu 18.04. 
I have created a partitioned table with two partitions.
Then when I query the table with a group by, I get this error:

`ERROR: Bug? no relevant Var-node reference in child rel: {VAR :varno 1 :varattno 2 :vartype 1082 :vartypmod -1 :varcollid 0 :varlevelsup 0 :varnoold 1 :varoattno 2 :location 7}`

Here's my sample SQL:

```
drop table if exists test.my_partitioned_table;

create table test.my_partitioned_table
(id int not null
,date_partition date
) partition by list(date_partition)
;

create table test.my_partitioned_table_1 partition of test.my_partitioned_table for values in ('2019-01-01') ;
create table test.my_partitioned_table_2 partition of test.my_partitioned_table for values in ('2019-01-02') ;

select date_partition, count(id)
from test.my_partitioned_table
group by date_partition
order by date_partition;
```

**Comment by mlazatinph** [comment]
Adding a count(distinct) prevents this error

select date_partition, count(id), count(distinct id)
from test.my_partitioned_table
group by date_partition
order by date_partition;

**Comment by kaigai** [comment]
Now I'm checking the problem.
It comes from `AppendPath->partitioned_rels` has different meaning at PG10 from PG11.

I'd like to consider a solution. Please wait for a while.

**Comment by mlazatinph** [comment]
I've confirmed that there is no issue in PG11. Issue is in PG10 only. Thanks kaigai for looking into this.

**Comment by kaigai** [comment]
c98c9ee11ece4bcc99401558e5ebaa83e4fa7cd8 should fix the problem.

Even though `AppendPath->partitioned_rels` and `AppendRelInfo` are key information to push down JOIN/GROUP BY across `Append` node, these structures were revised at PG11, so extension needs to pay attention for them.
The commit above revised the logic to push down JOIN/GROUP BY entirely, and fixed potential bugs also.

**Comment by mlazatinph** [comment]
Confirming this is solved in PG10. Thanks @kaigai !
