### ISSUE TITLE
"PG_VARLENA_SCALAR_ARRAY_OP" is undefined

### ISSUE THREAD

**Issue by MarkYSA** [heterodb/pg-strom#432]
Hello,

I've received the following error for some SQL queries:

pg-strom(39): error: identifier "PG_VARLENA_SCALAR_ARRAY_OP" is undefined

pg-strom(53): error: identifier "PG_VARLENA_SCALAR_ARRAY_OP" is undefined

2 errors detected in the compilation of "pg-strom".

source: /var/lib/pgsql/data/pgsql_tmp/pgsql_tmp_strom_21.0.gpu

Postgres version: 10.0
PG_STROM version is 10

this is docker container with cuda and pgsql
RTX 2080Ti

**Comment by kaigai** [comment]
Thanks for your report. It is a bug, and fixed at e71bae788911c8cd791081f7ff02f1af08a02656
Please check it.

**Comment by MarkYSA** [comment]
Fixed, thank you!
