### ISSUE TITLE
pg_strom not used in queries

### ISSUE THREAD

**Issue by baretomas** [heterodb/pg-strom#433]
Hello and thanks for very interesting extension to postgres!

I thought I would test it out on an old gaming computer I had laying around Dell Precision T3500 with a GTX 1050 Ti. Yeh I know it's not recommended, but this is just for testing it out before splashing out on a new server.

I followed the install instructions, using Centos 7, and Postgres 11 and latest nvidia and cuda drivers and pg_strom-PG11.

Hit some minor snags along the way, but mostly because of my own fumblings.

Now everything is up and running, I can see this on the status after starting postgres server:
` CGroup: /system.slice/postgresql-11.service
           ├─2740 /usr/pgsql-11/bin/postmaster -D /var/lib/pgsql/11/data/
           ├─2747 postgres: logger
           ├─2749 postgres: PG-Strom Program Builder-1
           ├─2750 postgres: PG-Strom Program Builder-0
           ├─2751 postgres: PG-Strom GPU memory keeper
           ├─2756 postgres: checkpointer
           ├─2757 postgres: background writer
           ├─2758 postgres: walwriter
           ├─2759 postgres: autovacuum launcher
           ├─2760 postgres: stats collector
           ├─2761 postgres: logical replication launcher
           └─2767 postgres: postgres postgres 10.0.0.177(61142) idle

Aug 15 14:22:11 pve2 postmaster[2740]: 2019-08-15 14:22:11.739 CEST [2740] LOG:  PG-Strom: GPU0 GeForce GTX 1050 Ti (768 CUDA cores; 1392MHz, L2 1024kB), RAM 4039MB (128bits, 3.34GHz), CC 6.1
Aug 15 14:22:11 pve2 postmaster[2740]: 2019-08-15 14:22:11.740 CEST [2740] LOG:  no nvme devices are installed
Aug 15 14:22:11 pve2 postmaster[2740]: 2019-08-15 14:22:11.741 CEST [2740] LOG:  PG-Strom: nvme_strom driver is not installed
`

It mentions pg_strom etc, but I seem to be missing :

> |-24901 postgres: bgworker: PG-Strom ccache-builder2
> |-24902 postgres: bgworker: PG-Strom ccache-builder1

Is that critical? In case, how to fix?

I created a db and added the extension pg_strom to it, and then imported a backup of a database I wanted to test on. To my disappointment, not any of my queries seem to use the GPU at all, as only the standard postgres calls is used.

> 
>  GroupAggregate  (cost=0.15..4284.27 rows=1000 width=44)
>    Group Key: cfs.configs_series_id
>    ->  Nested Loop  (cost=0.15..2696.78 rows=210000 width=8)
>          ->  Index Only Scan using configs_series_pkey on configs_series cfs  (cost=0.15..59.15 rows=1000 width=4)
>          ->  Materialize  (cost=0.00..13.15 rows=210 width=4)
>                ->  Seq Scan on configs cf  (cost=0.00..12.10 rows=210 width=4)
> 

Can anyone help me with this issue? I need an adult!

/brgds

**Comment by kaigai** [comment]
I guess you tried CROSS JOIN workloads without any join-qualifiers.
PG-Strom does not propose its own custom-path for the case, because GPU can provide no advantage here.

> It mentions pg_strom etc, but I seem to be missing :
> 
> |-24901 postgres: bgworker: PG-Strom ccache-builder2
> |-24902 postgres: bgworker: PG-Strom ccache-builder1
> 
> Is that critical? In case, how to fix?

Columnar-cache was deprecated and removed.
Now columnar-storage is replaced by arrow_fdw.

Thanks,

**Comment by baretomas** [comment]
Thanks!
Can you suggest a simple query I can use to confirm pg_strom is active? 
Ive tried group by with no effect either.

What are the requirements to a query for pg_strom to be activated?

**Comment by kaigai** [comment]
How about SSBM workloads?

This wiki focus on SSD-to-GPU Direct SQL, however, it enables PG-Strom at least.
(Of course, I never guarantee the performance. We recommend a validated hardware configuration)
https://github.com/heterodb/pg-strom/wiki/801:-How-to-setup-&-run-SSBM

**Comment by baretomas** [comment]
Thanks again!

Performance is ofc not my main concern at the moment. Only learning about how pg_strom works, and the possible advantages it has towards my use case.

Will check out your SSBM suggestion!
