### ISSUE TITLE
make failed in ubutnu 14.04 and postgresql 11

### ISSUE THREAD

**Issue by changchichung** [heterodb/pg-strom#434]
after git from this repo and I try to make . but there`s some error messages like this
```
gcc  "-DPGSTROM_VERSION=\"2.2\"" -DCPU_ARCH=\"x86_64\" -DPGSHAREDIR=\"/usr/share/postgresql/11\" -DPGSERV_INCLUDEDIR=\"/usr/include/postgresql/11/server\" -DCUDA_INCLUDE_PATH=\"/usr/local/cuda/include\" -DCUDA_BINARY_PATH=\"/usr/local/cuda/bin\" -DCUDA_LIBRARY_PATH=\"/usr/local/cuda/lib64\" -DCUDA_MAXREGCOUNT=128 -DCMD_GPUINFO_PATH=\"/usr/lib/postgresql/11/bin/gpuinfo\" -I /usr/local/cuda/include -L /usr/local/cuda/lib64 ./utils/gpuinfo.c -o utils/gpuinfo -lcuda
gcc -D__PG2ARROW__=1 -g -O0 -I ./src -I ./utils -I /usr/include/postgresql -I /usr/include/postgresql/11/server -L /usr/lib/x86_64-linux-gnu ./utils/pg2arrow.c ./utils/arrow_write.c -o utils/pg2arrow -lpq -lpgcommon
./utils/pg2arrow.c: In function ‘pgsql_dump_attribute’:
./utils/pg2arrow.c:899:6: warning: format ‘%s’ expects a matching ‘char *’ argument [-Wformat=]
      attr->attbyval ? "true" : "false", attr->attalign, attr->typtype);
      ^
/usr/bin/ld: cannot find -lpgcommon
collect2: error: ld returned 1 exit status
make: *** [utils/pg2arrow] Error 1
root@hqdc034:~/pg_strom# 
```

any suggestions for that ?

**Comment by changchichung** [comment]
I fix the problem by

1.sudo  ln -snf /usr/lib/postgresql/11/lib/libpgcommon.a /usr/lib/x86_64-linux-gnu/libpgcommon.a
2.sudo  ln -snf /usr/lib/postgresql/11/lib/libpgport.a /usr/lib/x86_64-linux-gnu/libpgport.a

and then comes another error 
not found -lselinux -ledit

and fix by 
sudo apt install libselinux1-dev libedit-dev

**Comment by kaigai** [comment]
I'm not certain about Ubuntu's package configuration.

In case of CentOS/RHEL, you need to install postgresql-devel and postgresql-libs packages.
Does Ubuntu have relevant packages?

**Comment by changchichung** [comment]
no , no such packages in ubuntu I think. maybe it`s include in some other packages , after all , the libpgcommon/libpgport were both already laying there.
