### ISSUE TITLE
pgstrom_devtype_lookup bug when add negative entry to list

### ISSUE THREAD

**Issue by idrissehitoglu2** [heterodb/pg-strom#436]
In function pgstrom_devtype_lookup when entry not found in the catalog, new negative entry generated and added to devtype_info_slot list. but type_oid for new type wasnt set to type_oid coming from function argument.  dtype->type_oid = type_oid;  should be added.

**Comment by kaigai** [comment]
Thanks for your report.
b6c1aca64691e27913d920d9332530bf1e7db35d fixed the problem.
