### ISSUE TITLE
GetOptimalGpuForTablespace returns false

### ISSUE THREAD

**Issue by idrissehitoglu2** [heterodb/pg-strom#438]
in function GetOptimalGpuForTablespace if nvme_strom_enabled isnt enabled it returns false but its return value check is as integer as cuda_index. i suppose it should return -1. even if it meant to return 0 (first gpu)  this case, i think "return false" gives misunderstanding.

**Comment by kaigai** [comment]
Thanks for your report, and sorry for my late.
4db2bae159a58841614828a694e7bb87acc5e26a should fix this problem.
