### ISSUE TITLE
pg-strom join plan execution time 

### ISSUE THREAD

**Issue by idrissehitoglu2** [heterodb/pg-strom#439]
for some queries pg-strom takes too much time for execution of join planning time. for query given below 
query execution time is 0.235 sec (cpu execution. no plan selected for gpu)
pg-strom used 0.173 sec for planning join (time passed for gpujoin_add_join_path function execution).
try_add_gpujoin_paths function called 9418 times and used 0.153 sec.
codegen_expression_walker used 0.090 sec

is it normal it takes too much time for planning? is it possible to make some optimization for planning join step for queries have several join clause?

SELECT I.*, H.BASEQUAN AS PRODUCTQUANTITY, H.QUNIT AS PRODUCTUNIT, B.IUNIT AS COMPONENTQUNITX, M4.ISDUMMY, B4.ISCOUNTABLE, R.FIXREQDUR AS FIXLEADTIME, R.VARREQDUR AS VARLEADTIME, R.OPERATION, '' AS DUMMYMATERIAL, '' AS DUMMYBOMITEM, 0.0 AS QUANTITYX, X.STEXT AS COMPONENTTEXT 
FROM IASBOMHEAD H 
INNER JOIN IASBOMITEM I ON (I.CLIENT = H.CLIENT AND I.COMPANY = H.COMPANY AND I.PLANT = H.PLANT AND I.BOMNUMBER = H.BOMNUMBER AND I.MATERIAL = H.MATERIAL AND I.ALTERNUM = H.ALTERNUM) 
INNER JOIN IASBOM005 B5 ON (B5.CLIENT = I.CLIENT AND B5.COMPANY = I.COMPANY AND B5.ITEMTYPE = I.ITEMTYPE) 
INNER JOIN IASMATBASIC B ON (B.CLIENT = I.CLIENT AND B.COMPANY = I.COMPANY AND B.MATERIAL = I.COMPONENT) 
INNER JOIN IASMATMOP M ON (M.CLIENT = I.CLIENT AND M.COMPANY = I.COMPANY AND M.PLANT = I.PLANT AND M.MATERIAL = I.COMPONENT) 
INNER JOIN IASMRP004 M4 ON (M4.CLIENT = M.CLIENT AND M4.COMPANY = M.COMPANY AND M4.PLANT = M.PLANT AND M4.SPPROKEY = M.SPPROKEY) 
INNER JOIN IASBAS004 B4 ON (B4.CLIENT = I.CLIENT AND B4.COMPANY = I.COMPANY AND B4.QUNIT = I.QUNIT) 
LEFT OUTER JOIN IASROUMAT R ON (R.CLIENT = I.CLIENT AND R.COMPANY = I.COMPANY AND R.PLANT = I.PLANT AND R.ROUNUM = I.MATERIAL AND R.MATERIAL = I.MATERIAL AND R.ALTERNUM = I.ALTERNUM AND R.BOMITEM = I.BOMITEM AND R.COMPONENT = I.COMPONENT AND R.VALIDFROM <= '01.22.2018' AND R.VALIDUNTIL >= '01.22.2018') 
LEFT OUTER JOIN IASMATX X ON (X.CLIENT = I.CLIENT AND X.COMPANY = I.COMPANY AND X.PLANT = I.PLANT AND X.MATERIAL = I.COMPONENT AND X.TEXTTYPE = 'M' AND X.LANGU = 'E' AND X.VALIDFROM <= '01.22.2018' AND X.VALIDUNTIL >= '01.22.2018') WHERE H.CLIENT = '00' AND H.COMPANY = '01' AND H.PLANT = '01' AND H.BOMNUMBER = '1010086' AND (H.MATERIAL = '1010086' OR H.MATERIAL = '*') AND H.ALTERNUM = '00' AND H.ISDELETE = 0 AND H.VALIDFROM <= '01.22.2018' AND H.VALIDUNTIL >= '01.22.2018' AND I.VALIDFROM <= '01.22.2018' AND I.VALIDUNTIL >= '01.22.2018' AND I.ISENGDESG = 1 AND B5.ISMATENTRY = 1 AND (B5.ISREQPLAN = 1 OR M4.ISDUMMY = 1) AND M.VALIDFROM <= '01.22.2018' AND M.VALIDUNTIL >= '01.22.2018' AND B.VALIDFROM <= '01.22.2018' AND B.VALIDUNTIL >= '01.22.2018' AND B4.LANGU = 'E'

**Comment by kaigai** [comment]
Hmm. Indeed, we have not pay attention for query planning time so much, because people usually applied PG-Strom on the workloads that usually take minutes or hours. It is relatively smaller portion in the total query processing time.
It is exactly what we shall revise in the (near) future version, however, we have no options right now.

**Comment by idrissehitoglu2** [comment]
Thank you.
Do you have a short explanation why try_add_gpujoin_paths function called too many times (9418 times for one query) ?

**Comment by kaigai** [comment]
Does the configuration below have impact on your query?
```
SET pg_strom.enable_partitionwise_gpujoin = off;
```
PG-Strom tries to extract scan on partitioned table, and distributes inner (usually small) relations to the partition leafs.

> Do you have a short explanation why try_add_gpujoin_paths function called too many times (9418 times for one query) ?

This query intends to join eight tables, so it may be possible. PG-Strom just tries to investigate possible join path for each invocation of set_join_pathlist_hook().
However, it may be possible to optimize the code for early break if potential join path has obviously more expensive than others.

**Comment by idrissehitoglu2** [comment]
enable_partitionwise_gpujoin  it doesnt has any impact.

> However, it may be possible to optimize the code for early break if potential join path has obviously more expensive than others.

i have no idea how to do this.

**Comment by kaigai** [comment]
I have no idea to avoid the problem, because PG-Strom has to add "additional" plan in addition to the built-in logics.
