### ISSUE TITLE
pg_strom build error: “make: *** No targets specified and no makefile found. Stop.”

### ISSUE THREAD

**Issue by jacobkreider** [heterodb/pg-strom#440]
As the title says, we are getting that error when building the pgstrom for Postgresql 10.

From the install instructions:
    $ cd pg-strom
   $ make PG_CONFIG=/usr/pgsql-10/bin/pg_config
   $ sudo make install PG_CONFIG=/usr/pgsql-10/bin/pg_config

We change directory to our pg_strom folder, but when we run the make command, we get the error seen in the title.

There's no makefile in the pg_strom folder, and ./configure gives us a file not found error. Autoconf doesn't work either, and cmake is not known.

We are installing on CentOS 7 (the install instructions we're using are for Red Hat/CentOS), and I'm not sure what we're missing.

We checked our CUDA installation (a troubleshooting tip found in the documentation), but it's in the place the pgstrom install is supposed to expect.

**Comment by idrissehitoglu2** [comment]
there should be makefile under pg-strom folder.  get clean pg-strom installation from git and retry it.

**Comment by jacobkreider** [comment]
This is correct. the rpm file we were using did not include the makefile. We used the github install and it works as expected.

**Comment by kaigai** [comment]
http://heterodb.github.io/pg-strom/install/#installation-from-the-source

Could you check the installation steps?
We intend `make` command is executed on the directory where PG-Strom is checked out.
(and, it is what we are usually doing in PostgreSQL)
