### ISSUE TITLE
License activation to use all features of NVME-strom module

### ISSUE THREAD

**Issue by sgi-bi** [heterodb/pg-strom#442]
Under the pg- strom installation manual there is a step that requires activation of license to use all the features of NVME-Strom module. I am having a hard time locating the file. Can someone please guide me through locating the file.

Thanks

Below are the steps from the manual:

**License activation

License activation is needed to use all the features of NVME-Strom module, provided by HeteroDB,Inc. You can operate the system without license, but features below are restricted. - Multiple GPUs support - Striping support (md-raid0) at SSD-to-GPU Direct SQL

You can obtain a license file, like as a plain text below, from HeteroDB,Inc.**

**Comment by kaigai** [comment]
Please contact to contact@heterodb.com, with result of `nvidia-smi -q` on your environment.
We (HeteroDB) can send back a trial license, then you copy the file at `/etc/heterodb.license` and restart PostgreSQL.

**Comment by kaigai** [comment]
BTW, our license enables the features below
1. use of multiple GPUs
1. use of multiple NVME-SSDs in striping mode
1. use of some SQL functions / operators on GPU (but no functions right now)
1. use of NVME-oF (RDMA)

The second one is the largest performance impact, because single NVME-SSD restricts query execution throughput by its SeqRead performance. If you need more throughput, striping of multiple SSDs are necessary.

**Comment by kaigai** [comment]
Could you contact to contact@heterodb.com, because we (HeteroDB) don't disclose license costing in public. And, GitHub issue is not a place where we discuss business topic.

**Comment by ujangja** [comment]
how can we edit trial license to prove the pg-strom functionality ?


waiting for server to start....2020-11-28 07:32:24.964 WIB [179968] LOG:  00000: NVRTC 11.1 is successfully loaded.
2020-11-28 07:32:24.964 WIB [179968] LOCATION:  pgstrom_init_nvrtc, nvrtc.c:246
2020-11-28 07:32:24.964 WIB [179968] LOG:  00000: PG-Strom version 2.9 built for PostgreSQL 12
2020-11-28 07:32:24.964 WIB [179968] LOCATION:  _PG_init, main.c:709
.failed on ioctl(STROM_IOCTL__LICENSE_LOAD): Key has expired
.2020-11-28 07:32:27.303 WIB [179968] LOG:  00000: PG-Strom: GPU0 Tesla P40 (3840 CUDA cores; 1531MHz, L2 3072kB), RAM 22.38GB (384bits, 3.45GHz), CC 6.1
2020-11-28 07:32:27.303 WIB [179968] LOCATION:  pgstrom_collect_gpu_device, gpu_device.c:285
2020-11-28 07:32:27.309 WIB [179968] LOG:  00000: PG-Strom: commercial license is expired
2020-11-28 07:32:27.309 WIB [179968] LOCATION:  commercial_license_query, main.c:563
2020-11-28 07:32:27.310 WIB [179968] LOG:  00000: starting PostgreSQL 12.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit


cat /etc/heterodb.license


IAgIVdKxhe+BSer3Y67jQW0+uTzYh00K6WOSH7xQ26Qcw8aeUNYqJB9YcKJTJb+QQhjmUeQpUnboNxVwLCd3HFuLXeBWMKp11/BgG0FSrkUWu/ZCtDtw0F1hEIUY7m767zAGV8y+i7BuNXGJFvRlAkxdVO3/K47ocIgoVkuzBfLvN/h9LffOydUnHPzrFHfLc0r3nNNgtyTrfvoZiXegkGM9GBTAKyq8uWu/OGonh9ybzVKOgofhDLk0rVbLohOXDhMlwDl2oMGIr83tIpCWG+BGE+TDwsJ4n71Sv6n4bi/ZBXBS498qShNHDGrbz6cNcDVBa+EuZc6HzZoF6UrljEcl=
----
VERSION:2
SERIAL_NR:HDB-TRIAL
ISSUED_AT:2019-05-09
EXPIRED_AT:2019-06-08
GPU_UUID:GPU-a137b1df-53c9-197f-2801-f2dccaf9d42f

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
