### ISSUE TITLE
pg-strom(410): error: "array_v" has already been declared in the current scope

### ISSUE THREAD

**Issue by jackguo-isogruppe** [heterodb/pg-strom#444]
- using rpm: https://heterodb.github.io/swdc/yum/rhel7-x86_64/pg_strom-PG11-2.2-1.el7.x86_64.rpm
- centos 7
- postgresql 11
- cuda 10.1

[sql_snip.txt](https://github.com/heterodb/pg-strom/files/3698078/sql_snip.txt)
[pgsql_tmp_strom_5447.0.gpu.txt](https://github.com/heterodb/pg-strom/files/3698083/pgsql_tmp_strom_5447.0.gpu.txt)

**Comment by jackguo-isogruppe** [comment]
i just tested it with https://heterodb.github.io/swdc/yum/rhel7-x86_64/pg_strom-PG11-2.1-7.el7.x86_64.rpm

the same error does not occur.

**Comment by kaigai** [comment]
Does the commit 43c801442c46b34c81c4a76e727e4a3b90f2f3d8 fix the problem?

P.S, Your query seems to me too complicated, even though I'm not sure data size of individual tables.
    I'm interested in whether PG-Strom can help acceleration well.

**Comment by jackguo-isogruppe** [comment]
Hi,
Thanks for the fast response. I'll have to try it out. 
I am also curious whether pg-storms helps with this query. Currently I haven't hat the chance to see pg-storm perform due to the bug XD

**Comment by jackguo-isogruppe** [comment]
Hi,
I just tried it out. the sql works now.
[explain_plan_1570783616765.svg.txt](https://github.com/heterodb/pg-strom/files/3716512/explain_plan_1570783616765.svg.txt)

**Comment by jackguo-isogruppe** [comment]
SET pg_strom.enabled = off;
Successfully run. Total query runtime: 3 secs 171 msec.
18214 rows affected.

--------
SET pg_strom.enabled = on;
Successfully run. Total query runtime: 3 secs 566 msec.
18214 rows affected.

**Comment by kaigai** [comment]
Thanks. How about the performance?

The recent version of PG-Strom is desigend to tackle tons of data-set (often more than terabyes scale).
So, I'm not certain how PG-Strom is helpful for the kind of workloads.

**Comment by jackguo-isogruppe** [comment]
Not certain whether or not it scales better if we have more data, And we are still at the phase of doing some prelimiary sandbox testing.

**Comment by kaigai** [comment]
Ah, well, thanks.
Probably, it is **harmless** but not beneficial so much.

https://www.slideshare.net/kaigai/20190909pgconfasiakaigai/7
This is my slide at PGconf.ASIA last month. It may be a good picture which area is we are working for...
