### ISSUE TITLE
makefile error while building pg_strom

### ISSUE THREAD

**Issue by sgi-bi** [heterodb/pg-strom#445]
I am trying to follow the steps from the installation documention to build pg_strom. Below is the make file error I recive when I type the following:

make PG_CONFIG=/usr/pgsql-11/bin/pg_config

Error:
/opt/rh/llvm-toolset-7/root/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2   "-DPGSTROM_VERSION=\"2.3\"" -DCPU_ARCH=\"x86_64\" -DPGSHAREDIR=\"/usr/pgsql-11/share\" -DPGSERV_INCLUDEDIR=\"/usr/pgsql-11/include/server\" -DCUDA_INCLUDE_PATH=\"/usr/local/cuda/include\" -DCUDA_BINARY_PATH=\"/usr/local/cuda/bin\" -DCUDA_LIBRARY_PATH=\"/usr/local/cuda/lib64\" -DCUDA_MAXREGCOUNT=128 -DCMD_GPUINFO_PATH=\"/usr/pgsql-11/bin/gpuinfo\" -I /usr/local/cuda/include -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o src/main.bc src/main.c
/bin/sh: /opt/rh/llvm-toolset-7/root/usr/bin/clang: No such file or directory
make: *** [src/main.bc] Error 127

**Comment by kaigai** [comment]
Please look at the knowledge 101
https://github.com/heterodb/pg-strom/wiki/101:-source-build-towards-PostgreSQL-11-RPM-installation

**Comment by sgi-bi** [comment]
Hello KaiGai,

Thank you for the email. The above instructions have worked for me and I
was able to complete the make file. But when I try to run the  postgresql
service it fails to start. I was able to start the service before. Below is
the error:

[root@localhost ~]# systemctl status -l postgresql-11
● postgresql-11.service - PostgreSQL 11 database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql-11.service; disabled;
vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2019-10-08 08:56:14 EDT;
1min 14s ago
     Docs: https://www.postgresql.org/docs/11/static/
  Process: 8704 ExecStart=/usr/pgsql-11/bin/postmaster -D ${PGDATA}
(code=exited, status=1/FAILURE)
  Process: 8695 ExecStartPre=/usr/pgsql-11/bin/postgresql-11-check-db-dir
${PGDATA} (code=exited, status=0/SUCCESS)
 Main PID: 8704 (code=exited, status=1/FAILURE)

Oct 08 08:56:14 localhost.localdomain postmaster[8704]: 2019-10-08
08:56:14.072 EDT [8704] LOG:  PG-Strom version 2.3 built for PostgreSQL 11
Oct 08 08:56:14 localhost.localdomain postmaster[8704]: modprobe: ERROR:
could not insert 'nvme_strom': Invalid argument
Oct 08 08:56:14 localhost.localdomain postmaster[8704]: /sbin/modprobe exit
with status: 1
Oct 08 08:56:14 localhost.localdomain postmaster[8704]:
./utils/gpuinfo.c:116  failed on open('/proc/nvme-strom'): No such file or
directory
Oct 08 08:56:14 localhost.localdomain postmaster[8704]: 2019-10-08
08:56:14.347 EDT [8704] FATAL:  PG-Strom: no supported GPU devices found
Oct 08 08:56:14 localhost.localdomain postmaster[8704]: 2019-10-08
08:56:14.348 EDT [8704] LOG:  database system is shut down
Oct 08 08:56:14 localhost.localdomain systemd[1]: postgresql-11.service:
main process exited, code=exited, status=1/FAILURE
Oct 08 08:56:14 localhost.localdomain systemd[1]: Failed to start
PostgreSQL 11 database server.
Oct 08 08:56:14 localhost.localdomain systemd[1]: Unit
postgresql-11.service entered failed state.
Oct 08 08:56:14 localhost.localdomain systemd[1]: postgresql-11.service
failed.

Thanks for your help.

-Pooja

**Comment by kaigai** [comment]
Does the commit `6454d16324dda64e9c41d9013381a5a7997b770a` work for you?

The `gpuinfo` command kicked by PG-Strom extension collects device information and
ensures `nvme_strom` kernel module. However, it terminated earlier than collecting device
information when `nvme_strom` kernel module is not installed. So, PG-Strom cannot see
the installed devices, then raised an error.
