### ISSUE TITLE
ERROR:  build failure: pg-strom(54): error: identifier "__temp1" is undefined  pg-strom(54): error: identifier "__anynull1" is undefined

### ISSUE THREAD

**Issue by jackguo-isogruppe** [heterodb/pg-strom#446]
ERROR:  build failure:
pg-strom(54): error: identifier "__temp1" is undefined

pg-strom(54): error: identifier "__anynull1" is undefined

2 errors detected in the compilation of "pg-strom".

source: /var/lib/pgsql/11/data/pgsql_tmp/pgsql_tmp_strom_26010.0.gpu
SQL state: 00000

git log: commit b35e3e627fee7bb78f0d52bdb722f97d306afdf9
postgresql: version 11
os version: centos 7

[bug.sql.txt](https://github.com/heterodb/pg-strom/files/3730256/bug.sql.txt)

[pgsql_tmp_strom_26010.0.gpu.txt](https://github.com/heterodb/pg-strom/files/3732939/pgsql_tmp_strom_26010.0.gpu.txt)

Tue Oct 15 17:51:05 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   51C    P2    76W / 300W |   7263MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       951      C   postgres: PG-Strom GPU memory keeper        7005MiB |
|    0      4682      C   postgres: PG-Strom GPU memory keeper         155MiB |
+-----------------------------------------------------------------------------+

**Comment by jackguo-isogruppe** [comment]
if I don't use the where clause I get a successful build xD:
 
Successfully run. Total query runtime: 16 secs 404 msec.
9368 rows affected.

------------------------------------
SELECT  
mandator_id
,userloginname 
,clientsystem 
,EXTRACT(MONTH FROM bookingdate) AS month 
,EXTRACT(YEAR FROM bookingdate) AS year
FROM pgstorm_booking booking
-- WHERE bookingdate BETWEEN '2016-01-01' AND '2020-12-31'
GROUP BY mandator_id, userloginname, clientsystem, EXTRACT(MONTH FROM bookingdate), EXTRACT(YEAR FROM bookingdate);

**Comment by jackguo-isogruppe** [comment]
sorry updated the first post with the correct gpu file

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
