### ISSUE TITLE
Question regarding the pgstorm sql optimizer

### ISSUE THREAD

**Issue by jackguo-isogruppe** [heterodb/pg-strom#447]
[gpu_scan_w_where_explain_plan_1571211232711.svg.txt](https://github.com/heterodb/pg-strom/files/3733009/gpu_scan_w_where_explain_plan_1571211232711.svg.txt)
[cpu_seq_scan_wo_where_explain_plan_1571211121869.svg.txt](https://github.com/heterodb/pg-strom/files/3733010/cpu_seq_scan_wo_where_explain_plan_1571211121869.svg.txt)
[sequence_scan.sql.txt](https://github.com/heterodb/pg-strom/files/3733013/sequence_scan.sql.txt)

So I have this very simple aggregated sql. 
The table has a brin-index on bookingdate.

Without the where-clause the postgres optimizer chooses a cpu sequence scan over the gpu scan.
With the where-clause it tries for an index-brin scan and finds the gpu scan more cost efficient.
Why don't you usually do a gpu-scan over a sequence-scan?

Having to force the gpu-scan with a where-clause seems kinda counter intuitive to me.

Also are you suggestion the optimizer to look only at the 'Startup-Cost'?
cpu: 0
gpu: 33194

Because the Total Cost is still cheaper on the gpu side than on the cpu side.
cpu: 1014737
gpu: 592552

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
