### ISSUE TITLE
FATAL:  could not load library "/XX/XX/pg_strom.so" undefined symbol: heap_parallelscan_reinitialize

### ISSUE THREAD

**Issue by xiaocai2333** [heterodb/pg-strom#449]
Is this what I am missing？

**Comment by kaigai** [comment]
I expect you likely try to build (a bit) old pg_strom code towards the latest PostgreSQL 12.
Please use PostgreSQL 11. The latest Git master branch is just compilable to PostgreSQL 12, but has not tested well right now.
