### ISSUE TITLE
FailedAssertion on variadic function.

### ISSUE THREAD

**Issue by idrissehitoglu2** [heterodb/pg-strom#450]
TRAP: FailedAssertion("!(proc->pronargs == list_length(func_args))", File: "src/codegen.c", Line: 2388)
im getting this error on CONCAT function.

PostgreSQL 11.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3), 64-bit
PG-Strom version 2.3 built for PostgreSQL 11
PG-Strom: GPU0 GeForce RTX 2080 Ti (4352 CUDA cores; 1635MHz, L2 5632kB), RAM 10.73GB (352bits, 6.68GHz), CC 7.5
no nvme devices are installed

**Comment by kaigai** [comment]
Thanks for your report.
1e8dd5ca24d3e48efb9838b24b91ed1a4552f2a2 fixed up the problem you reported.

Our internal infrastructure didn't pay attention for this kind of variadic functions.
So, this commit also add support of `concat` function (but up to 4 arguments right now) for validation purpose.

**Comment by idrissehitoglu2** [comment]
thank you for fix.
