### ISSUE TITLE
Why the Aggregate function takes so much time compared with pure postgres

### ISSUE THREAD

**Issue by liuheyuan** [heterodb/pg-strom#453]
I use SSB as testing workload and run query 1.1.
I have two scenarios: 1) using pure Postgres to run the query 2) just use pg_strom arrow_fdw and disable pg_strom GPU function. But I found below differences, the arrow_fdw takes so much time to do the aggregate function compared with pure Postgres.

**1. Pure Postgres: 18ms**

                                                                            QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Finalize Aggregate  (cost=788362.58..788362.58 rows=1 width=8) (actual time=13998.692..13998.692 rows=1 loops=1)
   **->  Gather  (cost=788362.46..788362.46 rows=56 width=8) (actual time=13998.239..14016.410 rows=56 loops=1)**
         Workers Planned: 56
         Workers Launched: 56
         ->  Partial Aggregate  (cost=788362.46..788362.46 rows=1 width=8) (actual time=13980.750..13980.750 rows=1 loops=56)
               ->  Hash Join  (cost=6.66..788361.28 rows=272 width=16) (actual time=2.223..13900.270 rows=638256 loops=56)
                     Hash Cond: (lineorder.lo_orderdate = date_.d_datekey)
                     ->  Parallel Seq Scan on lineorder  (cost=0.00..788232.67 rows=53571 width=24) (actual time=0.122..13302.726 rows=4207729 loops=56)
                           Filter: ((lo_discount >= '1'::double precision) AND (lo_discount <= '3'::double precision) AND (lo_quantity < '25'::double precision))
                           Rows Removed by Filter: 27934933
                     ->  Hash  (cost=6.63..6.63 rows=13 width=8) (actual time=1.490..1.490 rows=365 loops=56)
                           Buckets: 1024  Batches: 1  Memory Usage: 23kB
                           ->  Seq Scan on date_  (cost=0.00..6.63 rows=13 width=8) (actual time=0.184..1.327 rows=365 loops=56)
                                 Filter: (d_year = 1993)
                                 Rows Removed by Filter: 2192
 Planning Time: 2.632 ms
 Execution Time: 14016.590 ms
(17 rows)

**2) Use arrow_fdw and disable pg_strom GPU function. Aggregate time: 12922ms**

                                                                               QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Finalize Aggregate  (cost=338032.50..338032.50 rows=1 width=8) (actual time=29686.785..29686.786 rows=1 loops=1)
   **->  Gather  (cost=338032.38..338032.38 rows=56 width=8) (actual time=17709.763..30630.236 rows=56 loops=1)**
         Workers Planned: 56
         Workers Launched: 56
         ->  Partial Aggregate  (cost=338032.38..338032.38 rows=1 width=8) (actual time=17835.186..17835.186 rows=1 loops=56)
               ->  Parallel Hash Join  (cost=338011.20..338017.28 rows=3482 width=16) (actual time=17627.469..17803.001 rows=638256 loops=56)
                     Hash Cond: (date_.d_datekey = lineorder.lo_orderdate)
                     ->  Parallel Foreign Scan on date_  (cost=0.00..0.22 rows=1 width=8) (actual time=0.007..0.017 rows=7 loops=56)
                           Filter: (d_year = 1993)
                           Rows Removed by Filter: 39
                           referenced: d_datekey, d_year
                           files0: /mnt/nvme0/pgstrom/arrowssb/date_.arrow (size: 277.07KB)
                     ->  Parallel Hash  (cost=337884.97..337884.97 rows=53571 width=24) (actual time=17626.867..17626.867 rows=4207729 loops=56)
                           Buckets: 67108864 (originally 4194304)  Batches: 1 (originally 1)  Memory Usage: 13928160kB
                           ->  Parallel Foreign Scan on lineorder  (cost=0.00..337884.97 rows=53571 width=24) (actual time=20.175..13654.213 rows=4207729 loops=56)
                                 Filter: ((lo_discount >= '1'::double precision) AND (lo_discount <= '3'::double precision) AND (lo_quantity < '25'::double precision))
                                 Rows Removed by Filter: 27934933
                                 referenced: lo_orderdate, lo_quantity, lo_extendedprice, lo_discount
                                 files0: /mnt/nvme0/pgstrom/arrowssb/lineorder.arrow (size: 231.34GB)
 Planning Time: 2.607 ms
 Execution Time: 30631.989 ms
(21 rows)

**Comment by liuheyuan** [comment]
I cache all the data to memory first to avoid the IO latency.

**Comment by kaigai** [comment]
It uses CPU to scan the foreign `lineorder` table.
Likely, your configuration internally transform Arrow::Decimal (int128) to PostgreSQL::numeric (variable length), prior to evaluation of WHERE-clause. It is CPU consuming operations.

**Comment by kaigai** [comment]
Our GPU implementation is optimized to handle Arrow::Decial as numeric on device side.
I'll review your report on PG12 crash. Please wait for a while.

**Comment by liuheyuan** [comment]
Thanks for your reply and I will check whether there is any configuration to avoid this transform. I think if just using arrow file to get better performance improvements without GPU.  Pg_strom will be a great framework to help customers.

**Comment by kaigai** [comment]
No, it is not a stuff to be configurable.
Apache Arrow format defines fixed-precision 128bit number data type as `Decimal`, it is similar characteristics to `Numeric` in PostgreSQL, because it never causes calculation errors like float32.
It is wired design of arrow_fdw, here is no way to avoid.

Also note that 128bit values are usually larger than PostgreSQL's numeric with 4-6 digits, because its internal representation is 3-byte header + 2-4 bytes digits. It is 5-9 bytes per datum, even though 128bit value takes 16bytes per datum.

Some of numeric columns in SSBM holds only small integer values.
In this case, Arrow::Decimal <-> PostgreSQL::Numeric mapping is not best choice. Float4/Int4 may be better choice for example.

**Comment by liuheyuan** [comment]
I have use pure Postgres and arrow_fdw and compare the result. I found the arrow_fdw can scale better than pure Postgres just Parallel Foreign Scan on lineorder.

1. Arrow_fdw:

CPU Cores | 24 | 56 | 96 | 112 |  
-- | -- | -- | -- | -- | --
Total Time | 34205 | 28042 | 25421 | 25140 |  
Parallel Scan Time | 17082 | 11933 | 7740 | 7253 |  

2. Pure Postgres:

CPU Cores | 24 | 56 | 96 | 112 |  
-- | -- | -- | -- | -- | --
Total Time | 16358 | 13698 | 12864 | 13453 |  
Parallel Scan Time | 15418 | 13177 | 12420 | 13041 |

**Comment by shaunstoltz** [comment]
Are you running this inside docker container?

**Comment by knowever** [comment]
shaunstoltz,

I replied with a docker container build for you (on another issue)

https://github.com/heterodb/pg-strom/issues/454#issuecomment-583848978

I think its something you should be able to follow with no problems. If not let me know and I can try publishing my image.

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
