### ISSUE TITLE
PG10 issue | CREATE EXTENSION pg_strom --> syntax error at or near "FUNCTION" at character 503

### ISSUE THREAD

**Issue by shaunstoltz** [heterodb/pg-strom#454]
Has anyone got this working on Ubuntu?

020-01-14 17:32:40.725 UTC [378] WARNING:  schema "pgstrom" was not found
2020-01-14 17:32:40.725 UTC [378] HINT:  Run: CREATE EXTENSION pg_strom
2020-01-14 17:32:41.101 UTC [357] ERROR:  syntax error at or near "FUNCTION" at character 503

**Comment by shaunstoltz** [comment]
Is there a docker image using Ubuntu around?

**Comment by shaunstoltz** [comment]
Hmm... bumped to PG11 and its working... may be related to this bug? https://github.com/heterodb/pg2arrow/issues/11

**Comment by knowever** [comment]
Hey I got the docker working CentOs. Using 
https://github.com/sclorg/postgresql-container/tree/generated/12

as my starting point. Had to rebuild nvidia's base images 10.2 to use 
FROM centos/s2i-core-centos7

https://gitlab.com/nvidia/container-images/cuda/-/tree/master/dist/centos7/10.2

Then I made the postgresql-container image 12 use my custom built nvidia's images (not preferred)

FROM knmtech/cuda:10.2-devel-s2i-core-centos7

Once I did that it was a matter of picking the right packages and building. I will try again later to hack the office postgres to use Ubuntu directly from a none modified Nvidia base 10.2 later.

https://github.com/docker-library/postgres/blob/0d0485cb02e526f5a240b7740b46c35404aaf13f/12/Dockerfile

Below is my hacked version of CentOs postgresql 12 with osm2pgsql (for testing large dataset), pg-strom. I hope it helps.

[QUICK_INSTALL_README.txt](https://github.com/heterodb/pg-strom/files/4176967/QUICK_INSTALL_README.txt)
[postgresql-container.tar.gz](https://github.com/heterodb/pg-strom/files/4176968/postgresql-container.tar.gz)



--

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
