### ISSUE TITLE
how to native support base type `FLOAT4ARRAY` ?

### ISSUE THREAD

**Issue by yjhjstz** [heterodb/pg-strom#455]
any idea， many thanks .

**Comment by yjhjstz** [comment]
can anyone offer Implementation of `knn_gpu_similarity`, many thanks.

**Comment by kaigai** [comment]
Do you want to run the drug-discovery workloads I had presented a few years before?
It used non-public data owned by my co-author, so it needs individual permission for sharing.
Are you working for bio-infomatics?

**Comment by yjhjstz** [comment]
I work for AI algorithm to find out similarity, I don't need data, but the implementation guide of knn_gpu_similarity.

**Comment by kaigai** [comment]
Sorry, data & code are not in public. However, a research poster I presented 3 years before introduces what we did at that time.
See, **Elements: k-NN Similarity Search** section.
We partitioned NxM combinations into multiple parts for each 1024 items, then calculate similarity for each CUDA-code. The result array has (1024+k) items, so iteration of the calculation shall make the top-k similarity eventually (It is initialized to -1.0; smaller than any similarity). Number of SM in GPU is relatively small, so final merge step is not a heavy calculation; enough to run on CPU.

[2016Oct_CBI_Workshop_Poster.pdf](https://github.com/heterodb/pg-strom/files/4089063/2016Oct_CBI_Workshop_Poster.pdf)

**Comment by yjhjstz** [comment]
thanks, anyway.  
But I have another question that how to add pg base type FLOAT4ARRAY in pgstrom ? and support operator like '<->'  for similarity calculation ?

**Comment by kaigai** [comment]
Here is no graceful way right now. You need to add function catalog to `codegen.c` and implement relevant GPU implementation somewhere.
I understand it is painful for the people who want to extend PG-Strom, and we shall support capability to extend GPU code for SQL.

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
