### ISSUE TITLE
Install pg_storm extension using Window 7

### ISSUE THREAD

**Issue by hussain7006** [heterodb/pg-strom#459]
0

I am not a native English speaker so please ignore my grammar mistakes.

I want to add or install pg_storm extension having postgresql (11.5) in my local machine using windows 7, I search a alot and got most of the solution are on Linux based.

Is there any way to add or install **pg_storm** extension having PostgreSQL (11.5) in my local machine using windows 7 in it.

And please also guide me, "I want to use **pg_storm** only to reduce my path finding queries time with the help of GPU", is it right way or not.

If not please suggest me right way.

Thank you!

**Comment by kaigai** [comment]
Soory, we only perform on Linux (x86_64) platform.
