### ISSUE TITLE
ssbm tests fail with: type with OID 0 does not exist

### ISSUE THREAD

**Issue by arg7** [heterodb/pg-strom#460]
Hi there!
here is my problem, some of SQL selects fail with: 
 
    ERROR:  42704: type with OID 0 does not exist

for example ./test/sql/ssbm-11.sql, if pg-strom is enabled.

Tests such as dfunc_math.sql dtype*.sql are ok.

My platform is Ubuntu 18.04.4 LTS, GPU is Nvidia P106-100 with latest drivers:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  P106-100            On   | 00000000:09:00.0 Off |                  N/A |
| 42%   35C    P0    24W / 120W |     71MiB /  6080MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     16643      C   ... 12/main: PG-Strom GPU memory keeper       61MiB |
+-----------------------------------------------------------------------------+

I've installed PostgreSQL v12 from postgresql apt repositories and PG_Strom from sources to avoid version mismatches.

With debug logs of PG set to level 3, I'm getting:
2020-04-22 19:43:56.992 CEST [16669] postgres@ssbm DEBUG:  GpuJoin: date1 IHJ lineorder Cost=11468.63..1140233.28
2020-04-22 19:43:56.993 CEST [16669] postgres@ssbm DEBUG:  GpuJoin: date1 IHJ lineorder Cost=30172.02..731792.20
2020-04-22 19:43:56.993 CEST [16669] postgres@ssbm DEBUG:  GpuJoin: lineorder IHJ date1 Cost=1238173.16..1238173.16 rejected
2020-04-22 19:43:56.993 CEST [16669] postgres@ssbm ERROR:  type with OID 0 does not exist
2020-04-22 19:43:56.993 CEST [16669] postgres@ssbm STATEMENT:  select sum(lo_extendedprice*lo_discount) as revenue
	    from lineorder,date1
	    where lo_orderdate = d_datekey
	    and d_year = 1993
	    and lo_discount between 1 and 3
	    and lo_quantity < 25;

I've tried also with Nvidia GTX 1650, with the same results.

What should I do to fix the problem?

Thank you very much,

Best regards,
Andrey

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
