### ISSUE TITLE
 GPU kernel: compressed or external varlena on device

### ISSUE THREAD

**Issue by wuruilongll** [heterodb/pg-strom#466]
I had installed pg12 and my gpu is nvidia 2080ti ,pg_strom version 2.3, when i execute the SQL 

`select geom from t1 where gid = '{46C0-9684}' ` and `select geom from t1 where gid <> '{46C0-9684}'`

it reports  SQL error: GPU kernel: compressed or external varlena on device,

 when execute 

`select geom from t1 where gid > '{46C0-9684}' ` and `select geom from t1 where gid < '{46C0-9684}'`

it's ok，i found the doucument about text functions/operators as  following  screenshots

![image](https://user-images.githubusercontent.com/7246516/90003595-e31a2c00-dcc6-11ea-87b0-71679a5bcce4.png)

**Comment by kaigai** [comment]
It means the `gid` column (likely, text) contains too large text more than the threshold PostgreSQL saves datum inline.
Here is two solutions.
1. set `pg_strom.cpu_fallback`, to enable CPU fallback mode if GPU cannot handle it.
  it prevents errors, but performance is not good.
2. change column's storage option to `MAIN` using `ALTER TABLE`, then rebuild the table again.
   it is not a perfect option, but expand the threshold to compress or save externally.
https://www.postgresql.org/docs/devel/sql-altertable.html
https://www.postgresql.org/docs/devel/storage-toast.html

**Comment by kaigai** [comment]
BTW, it looks to me you are trying to fetch something geometry data.
Are you doing something about PostGIS? We are now working to support PostGIS functions on GPU.

**Comment by wuruilongll** [comment]
> It means the `gid` column (likely, text) contains too large text more than the threshold PostgreSQL saves datum inline.
> Here is two solutions.
> 
> 1. set `pg_strom.cpu_fallback`, to enable CPU fallback mode if GPU cannot handle it.
>    it prevents errors, but performance is not good.
> 2. change column's storage option to `MAIN` using `ALTER TABLE`, then rebuild the table again.
>    it is not a perfect option, but expand the threshold to compress or save externally.
>    https://www.postgresql.org/docs/devel/sql-altertable.html
>    https://www.postgresql.org/docs/devel/storage-toast.html

Thanks , I did it by the first way , it take effect and execute success by setting the parameter in a session , but whether it can be written to a global configuration file, so i can develop my webapp use the jdbc.

`set pg_strom.cpu_fallback = on`
`select geom from t1 where gid = '{46C0-9684}' `

Also , when enable CPU fallback and create btree index on the field `gid` , the query performance is also fast in millions of data.

**Comment by kaigai** [comment]
If index works effectively on your workloads, basically, I don't recommend PG-Strom for the kind of job. :-)

**Comment by wuruilongll** [comment]
> BTW, it looks to me you are trying to fetch something geometry data.
> Are you doing something about PostGIS? We are now working to support PostGIS functions on GPU.

Yes, i am a GISer, and i like to develop my app with PostGIS, it is very convenient and powerful. I also concerned about some open source GIS, at the same time i am using the OmniSciDB, it implemented many PostGIS functions, but PG-Strom as an extension of PG, it is lightweight and i prefer to use it, hoping it will be more powerful in the future. :-)

**Comment by kaigai** [comment]
It is now under active development. Please wait for Q4-2020.

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
