### ISSUE TITLE
Compared to apache/madlib ?

### ISSUE THREAD

**Issue by elgalu** [heterodb/pg-strom#468]
Does this project enhances or overlaps with https://github.com/apache/madlib ?

> MADlib 2020 release: new features: ... Tensorflow backend with GPU acceleration

**Comment by kaigai** [comment]
It looks to me they use GPU acceleration for machine-learning workloads, not generic SQL acceleration.
As long as MADLib's resource management does not break something in PG-Strom, a PostgreSQL install will be able to host both of the extensions. (I'm not certain whether the TensorFlow still acquires all the GPU device memory at the startup time. If this behavior is not fixed yet, PG-Strom side falls into resource starvations.)
