### ISSUE TITLE
Installation Issue on Ubuntu

### ISSUE THREAD

**Issue by maliabd-al-majid** [heterodb/pg-strom#474]
i have checked Checklist on My Ubuntu System:
1- nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
2- installed Postgresql 10.
3- installed Cuda Toolkit.
4- GPU DEVICE : Nvidia Quadro RTX 4000.
 i have faced problem in step Building the PG-Strom :

`make PG_CONFIG=/usr/pgsql-10/bin/pg_config`

while i have checked pg_config :

`BINDIR = /usr/lib/postgresql/10/bin
DOCDIR = /usr/share/doc/postgresql-doc-10
HTMLDIR = /usr/share/doc/postgresql-doc-10
INCLUDEDIR = /usr/include/postgresql
PKGINCLUDEDIR = /usr/include/postgresql
INCLUDEDIR-SERVER = /usr/include/postgresql/10/server
LIBDIR = /usr/lib/x86_64-linux-gnu
PKGLIBDIR = /usr/lib/postgresql/10/lib
LOCALEDIR = /usr/share/locale
MANDIR = /usr/share/postgresql/10/man
SHAREDIR = /usr/share/postgresql/10
SYSCONFDIR = /etc/postgresql-common
PGXS = /usr/lib/postgresql/10/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=/usr/include' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=/usr/lib/x86_64-linux-gnu' '--runstatedir=/run' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-icu' '--with-tcl' '--with-perl' '--with-python' '--with-pam' '--with-openssl' '--with-libxml' '--with-libxslt' 'PYTHON=/usr/bin/python3' '--mandir=/usr/share/postgresql/10/man' '--docdir=/usr/share/doc/postgresql-doc-10' '--sysconfdir=/etc/postgresql-common' '--datarootdir=/usr/share/' '--datadir=/usr/share/postgresql/10' '--bindir=/usr/lib/postgresql/10/bin' '--libdir=/usr/lib/x86_64-linux-gnu/' '--libexecdir=/usr/lib/postgresql/' '--includedir=/usr/include/postgresql/' '--with-extra-version= (Ubuntu 10.15-1.pgdg20.04+1)' '--enable-nls' '--enable-integer-datetimes' '--enable-thread-safety' '--enable-tap-tests' '--enable-debug' '--enable-dtrace' '--disable-rpath' '--with-uuid=e2fs' '--with-gnu-ld' '--with-pgport=5432' '--with-system-tzdata=/usr/share/zoneinfo' '--with-systemd' '--with-selinux' 'MKDIR_P=/bin/mkdir -p' 'TAR=/bin/tar' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now' '--with-gssapi' '--with-ldap' '--with-includes=/usr/include/mit-krb5' '--with-libs=/usr/lib/mit-krb5' '--with-libs=/usr/lib/x86_64-linux-gnu/mit-krb5' 'build_alias=x86_64-linux-gnu' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2'
CC = gcc
CPPFLAGS = -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/include/mit-krb5
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lpthread -lselinux -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -ledit -lrt -lcrypt -ldl -lm 
VERSION = PostgreSQL 10.15 (Ubuntu 10.15-1.pgdg20.04+1)
`

issue that i got :

`grep: /include/cuda.h: No such file or directory
/bin/sh: 1: test: -ge: unexpected operator
/bin/sh: 1: test: -ge: unexpected operator
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC  -D__PGSTROM_MODULE__=1 "-DPGSTROM_VERSION=\"3.0\"" -DCPU_ARCH=\"x86_64\" -DPGSHAREDIR=\"/usr/share/postgresql/10\" -DPGSERV_INCLUDEDIR=\"/usr/include/postgresql/10/server\" -DCUDA_INCLUDE_PATH=\"/include\" -DCUDA_BINARY_PATH=\"/bin\" -DCUDA_LIBRARY_PATH=\"/lib64\" -DCUDA_MAXREGCOUNT=128 -DCMD_GPUINFO_PATH=\"/usr/lib/postgresql/10/bin/gpuinfo\" -I /include -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o src/main.o src/main.c
In file included from src/main.c:18:
src/pg_strom.h:16:10: fatal error: postgres.h: No such file or directory
   16 | #include "postgres.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: src/main.o] Error 1
(base) mohamednadeem@mohamednadeem-HP-Z2-To`

so please assist in finding solution for this issue

**Comment by kaigai** [comment]
Did you change CUDA installation path?
`Makefile` of PG-Strom looks up CUDA installation path from `/usr/local/cuda` or `/usr/local/cuda-*`.

**Comment by maliabd-al-majid** [comment]
no , i didn't  inside /usr/local/ i have cuda , cuda10.1 and cuda10.2 .
I have tried make and make install , and that is the issue i got :
`gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC  -D__PGSTROM_MODULE__=1 "-DPGSTROM_VERSION=\"3.0\"" -DCPU_ARCH=\"x86_64\" -DPGSHAREDIR=\"/usr/share/postgresql/10\" -DPGSERV_INCLUDEDIR=\"/usr/include/postgresql/10/server\" -DCUDA_INCLUDE_PATH=\"/usr/local/cuda/include\" -DCUDA_BINARY_PATH=\"/usr/local/cuda/bin\" -DCUDA_LIBRARY_PATH=\"/usr/local/cuda/lib64\" -DCUDA_MAXREGCOUNT=128 -DCMD_GPUINFO_PATH=\"/usr/lib/postgresql/10/bin/gpuinfo\" -I /usr/local/cuda/include -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o src/main.o src/main.c
In file included from src/main.c:18:
src/pg_strom.h:16:10: fatal error: postgres.h: No such file or directory
   16 | #include "postgres.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: src/main.o] Error 1
`

**Comment by maliabd-al-majid** [comment]
Postgres version : 

```
postgres=# SELECT version();
                                                              version                                                               
------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 10.15 (Ubuntu 10.15-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
(1 row)

```

**Comment by maliabd-al-majid** [comment]
please ignore previous errors .
that is the last error i got after solving other errors :
```
/usr/local/cuda/bin/nvcc  -I /usr/include/postgresql/10/server --fatbin --maxrregcount=128 --gpu-architecture=compute_60 --gpu-code=sm_60,sm_61,sm_70,sm_75 --relocatable-device-code=true -o src/cuda_common.fatbin src/cuda_common.cu
In file included from /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
  138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~
make: *** [Makefile:288: src/cuda_common.fatbin] Error 1

```
i have gcc version : 

```
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by maliabd-al-majid** [comment]
that is the last issue i have :
```
/usr/bin/ld: cannot find -lpgcommon
/usr/bin/ld: cannot find -lpgport
collect2: error: ld returned 1 exit status
make: *** [Makefile:335: utils/pg2arrow] Error 1
```

**Comment by maliabd-al-majid** [comment]
i still have this issue after i updated to postgresql 13 :
```
gcc -D__PG2ARROW__=1 -D_GNU_SOURCE -g -Wall -I ./src -I ./utils -I /usr/include/postgresql -I /usr/include/postgresql/13/server -L /usr/lib/x86_64-linux-gnu -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -L/usr/lib/llvm-9/lib -Wl,--as-needed \
              ./utils/sql2arrow.c ./utils/pgsql_client.c ./src/arrow_nodes.c ./src/arrow_write.c ./src/arrow_pgsql.c -o utils/pg2arrow -lpq -lpgcommon -lpgport
/usr/bin/ld: cannot find -lpgcommon
/usr/bin/ld: cannot find -lpgport
collect2: error: ld returned 1 exit status
make: *** [Makefile:335: utils/pg2arrow] Error 1
```
packages that i have in postgresql 13 :
```

ii  pgdg-keyring                               2018.2                                all          keyring for apt.postgresql.org
ii  postgresql-13                              13.1-1.pgdg20.04+1                    amd64        object-relational SQL database, version 13 server
ii  postgresql-client-13                       13.1-1.pgdg20.04+1                    amd64        front-end programs for PostgreSQL 13
ii  postgresql-client-common                   223.pgdg20.04+1                       all          manager for multiple PostgreSQL client versions
ii  postgresql-common                          223.pgdg20.04+1                       all          PostgreSQL database-cluster manager
ii  postgresql-server-dev-13                   13.1-1.pgdg20.04+1                    amd64        development files for PostgreSQL 13 server-side programming

```

**Comment by kaigai** [comment]
PG-Strom still does not catch up PostgreSQL v13, please use v12 instead.

I'm not good at Ubuntu system. However, missing "postgres.h" is a bit strange.
Do you install the `postgresql-server-dev-10` or later version here?
If you can find out `pg_config` in your command search path, `pg_config` solves compiler options to find out headers and libraries.

`pg2arrow` may also needs `libpq-dev` package also.
https://www.postgresql.org/download/linux/ubuntu/

**Comment by maliabd-al-majid** [comment]
i run pg_config :
```
pg_config
BINDIR = /usr/lib/postgresql/12/bin
DOCDIR = /usr/share/doc/postgresql-doc-12
HTMLDIR = /usr/share/doc/postgresql-doc-12
INCLUDEDIR = /usr/include/postgresql
PKGINCLUDEDIR = /usr/include/postgresql
INCLUDEDIR-SERVER = /usr/include/postgresql/12/server
LIBDIR = /usr/lib/x86_64-linux-gnu
PKGLIBDIR = /usr/lib/postgresql/12/lib
LOCALEDIR = /usr/share/locale
MANDIR = /usr/share/postgresql/12/man
SHAREDIR = /usr/share/postgresql/12
SYSCONFDIR = /etc/postgresql-common
PGXS = /usr/lib/postgresql/12/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=/usr/include' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=/usr/lib/x86_64-linux-gnu' '--runstatedir=/run' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-icu' '--with-tcl' '--with-perl' '--with-python' '--with-pam' '--with-openssl' '--with-libxml' '--with-libxslt' 'PYTHON=/usr/bin/python3' '--mandir=/usr/share/postgresql/12/man' '--docdir=/usr/share/doc/postgresql-doc-12' '--sysconfdir=/etc/postgresql-common' '--datarootdir=/usr/share/' '--datadir=/usr/share/postgresql/12' '--bindir=/usr/lib/postgresql/12/bin' '--libdir=/usr/lib/x86_64-linux-gnu/' '--libexecdir=/usr/lib/postgresql/' '--includedir=/usr/include/postgresql/' '--with-extra-version= (Ubuntu 12.5-1.pgdg20.04+1)' '--enable-nls' '--enable-integer-datetimes' '--enable-thread-safety' '--enable-tap-tests' '--enable-debug' '--enable-dtrace' '--disable-rpath' '--with-uuid=e2fs' '--with-gnu-ld' '--with-pgport=5432' '--with-system-tzdata=/usr/share/zoneinfo' '--with-llvm' 'LLVM_CONFIG=/usr/bin/llvm-config-9' 'CLANG=/usr/bin/clang-9' '--with-systemd' '--with-selinux' 'MKDIR_P=/bin/mkdir -p' 'TAR=/bin/tar' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now' '--with-gssapi' '--with-ldap' '--with-includes=/usr/include/mit-krb5' '--with-libs=/usr/lib/mit-krb5' '--with-libs=/usr/lib/x86_64-linux-gnu/mit-krb5' 'build_alias=x86_64-linux-gnu' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security'
CC = gcc
CPPFLAGS = -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/include/mit-krb5
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -L/usr/lib/llvm-9/lib -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lpthread -lselinux -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -ledit -lrt -lcrypt -ldl -lm 
VERSION = PostgreSQL 12.5 (Ubuntu 12.5-1.pgdg20.04+1)
```
and it says that libraries lpgcommon and lpgport are added .
it seems that library directory is different from the one in pgstrom installation:

```
make install
gcc -D__PG2ARROW__=1 -D_GNU_SOURCE -g -Wall -I ./src -I ./utils -I /usr/include/postgresql -I /usr/include/postgresql/12/server -L /usr/lib/x86_64-linux-gnu -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -L/usr/lib/llvm-9/lib -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed \
              ./utils/sql2arrow.c ./utils/pgsql_client.c ./src/arrow_nodes.c ./src/arrow_write.c ./src/arrow_pgsql.c -o utils/pg2arrow -lpq -lpgcommon -lpgport
/usr/bin/ld: cannot find -lpgcommon
/usr/bin/ld: cannot find -lpgport
collect2: error: ld returned 1 exit status
make: *** [Makefile:335: utils/pg2arrow] Error 1


```

**Comment by maliabd-al-majid** [comment]
i have found solution i will write it as it might help others:
1-in terminal :
`emacs ~/.bashrc`
2- add :
```
export C_INCLUDE_PATH=/usr/include/postgresql:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/usr/include/postgresql:$CPLUS_INCLUDE_PATH
export LD_LIBRARY_PATH=/usr/lib/postgresql/12/lib:$LD_LIBRARY_PATH
export LIBRARY_PATH=/usr/lib/postgresql/12/lib:$LIBRARY_PATH
```
