### ISSUE TITLE
arrow_fdw without gpu

### ISSUE THREAD

**Issue by ujangja** [heterodb/pg-strom#483]
I tested arrow_fdw and it looks greate, faster than c-store on my env.

Is there any plan to split arrow_fdw without gpu/cuda dependencies?

Recently I tried to fake postgres startup with shared_preload_libraries = 'pg_strom' just to take arrow_fdw on a vm without gpu.

looks like these errors keep showing in postgres log:

ERROR:  XX000: failed on cuInit: CUDA_ERROR_NO_DEVICE - no CUDA-capable device is detected
LOCATION:  gpummgrBgWorkerMain, gpu_mmgr.c:1227
LOG:  00000: background worker "PG-Strom GPU memory keeper" (PID 3011) exited with exit code 1
LOCATION:  LogChildExit, postmaster.c:3688
ERROR:  XX000: failed on cuInit: CUDA_ERROR_NO_DEVICE - no CUDA-capable device is detected
LOCATION:  gpummgrBgWorkerMain, gpu_mmgr.c:1227
LOG:  00000: background worker "PG-Strom GPU memory keeper" (PID 3013) exited with exit code 1
LOCATION:  LogChildExit, postmaster.c:3688

**Comment by kaigai** [comment]
I have no plan because of code management complexity.

However, it may be reasonable to allow to start PostgreSQL with pg_strom.so even if no supported GPU devices.
If no devices found, it should turn off the GPU-related feature of PG-Strom, then Arrow_Fdw will remain.

**Comment by ujangja** [comment]
I did some changes at main.c file and compiled, looks like everything were fine, tested arrow_fdw also fine, so are these changes will not cause any future error?

        /* disable here -- */
        /* pgstrom_init_gpu_device(); -- */
        /* pgstrom_init_gpu_mmgr(); -- */
        /* pgstrom_init_gpu_context(); -- */
        /* pgstrom_init_cuda_program(); -- */
        /* pgstrom_init_nvme_strom(); -- */


        pgstrom_init_codegen();

        /* init custom-scan providers/FDWs */
        pgstrom_init_gputasks();
        pgstrom_init_gpuscan();
        pgstrom_init_gpujoin();
        pgstrom_init_gpupreagg();
        pgstrom_init_relscan();
        pgstrom_init_arrow_fdw();
        /* pgstrom_init_gstore_fdw(); -- */

        /* check commercial license, if any */
        check_heterodb_license();

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
