### ISSUE TITLE
issue while using threads .

### ISSUE THREAD

**Issue by maliabd-al-majid** [heterodb/pg-strom#484]
i have installed pg-strom and i faced some issues when i try to use threads .
i got issue , it only occurs when i increase number of queries on views:
`psycopg2.errors.DataCorrupted: GPU kernel: corrupted numeric header
`

**Comment by kaigai** [comment]
Could you show us which numeric value produce this error?

This error message is caused by:
https://github.com/heterodb/pg-strom/blob/master/src/cuda_numeric.cu#L175

I doubt this numeric value is very large to transform to an external toast form.

**Comment by maliabd-al-majid** [comment]
thanks for your reply
i think numeric value is around 1000000.
is there a way to increase numeric value limit ?

**Comment by kaigai** [comment]
> i found a solution for the numeric value problem.

What is the solution you applied to?
This error message shall not be generated, when numeric value is less than sizeof(NumericChoice) (~ 40bytes).
I'm still unable to identify the problem, thus, no idea.

**Comment by maliabd-al-majid** [comment]
numeric value was too large. 
is it possible to change size of numeric value ? .

**Comment by kaigai** [comment]
Ok, PG-Strom internally maps numeric value to 128bit values (that is for data portability with Apache Arrow's Decimal).
So, here is no solution except of reduction of the number of digits.

**Comment by maliabd-al-majid** [comment]
thanks for your huge effort.
