### ISSUE TITLE
Error when I use ccache

### ISSUE THREAD

**Issue by CPythoner** [heterodb/pg-strom#501]
PostgreSQL version: 10
pg_strom version: 2.0

I set one database in variant `pg_strom.ccache_databases` and I set `pg_strom.ccache_num_builders` 4 or 8, there is a error when I restart postgres: `number of the configured databases by pg_strom.ccache_databases is larger than number of the builder processes by pg_strom.ccache_num_builders, so columnar cache will be never built on some databases`.

How can I resolve the error?

Thanks!

**Comment by kaigai** [comment]
Sorry, ccache is not a feature no longer supported.

Once I tried to implement it, we couldn't find out any valuable use scenario here.
http://heterodb.github.io/pg-strom/release_note/#dropped-features

**Comment by CPythoner** [comment]
Which feature shall I use to speed up GPU execution instead of ccache in version 2.2 or 2.3？

**Comment by CPythoner** [comment]
> Sorry, ccache is not a feature no longer supported.
> 
> Once I tried to implement it, we couldn't find out any valuable use scenario here.
> http://heterodb.github.io/pg-strom/release_note/#dropped-features

Thanks for your reply.
Which feature shall I use to speed up GPU execution instead of ccache in version 2.2 or 2.3？

**Comment by kaigai** [comment]
Pg2Arrow + Arrow_Fdw is partially alternative feature.

In 3.0, we will provide a special trigger function that allows to synchronize PostgreSQL table with GPU memory store.
It shall be the successor of ccache.

**Comment by CPythoner** [comment]
OK, thank you. Hope 3.0's coming.
