### ISSUE TITLE
could not load library "/usr/pgsql-10/lib/pg_strom.so": /usr/pgsql-10/lib/pg_strom.so: undefined symbol: cuIpcOpenMemHandle_v2

### ISSUE THREAD

**Issue by Venkatclouddba** [heterodb/pg-strom#508]
Postgress (version 10) failed to start with below error
could not load library "/usr/pgsql-10/lib/pg_strom.so": /usr/pgsql-10/lib/pg_strom.so: undefined symbol: cuIpcOpenMemHandle_v2
below are current configurations

yum list installed | grep gpu
cuda-gpu-library-advisor-10-1.x86_64  10.1.168-1                  @cuda
yum list installed | grep strom*
nvme_strom.x86_64                     2.8-1.el7                   @heterodb
pg_strom-PG10.x86_64                  2.9-210109.el7              @heterodb
yum list installed | grep postgres
postgresql-alternatives.noarch        1.1-1.el7                   @heterodb
postgresql10.x86_64                   10.15-1PGDG.rhel7           @pgdg10
postgresql10-devel.x86_64             10.15-1PGDG.rhel7           @pgdg10
postgresql10-libs.x86_64              10.15-1PGDG.rhel7           @pgdg10
postgresql10-server.x86_64            10.15-1PGDG.rhel7           @pgdg10

**Comment by Cerdore** [comment]
Hello! I also encountered this problem, did you solve it?

**Comment by kaigai** [comment]
Note that the latest PG-Strom does not support build towards PostgreSQL v10.x

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
