### ISSUE TITLE
Does pg-strom have only one active contributor? 

### ISSUE THREAD

**Issue by eugeneYWang** [heterodb/pg-strom#516]
It is shocking to see the the most of commits was from one person.

**Comment by kaigai** [comment]
Because it was originated from my personal project several years before....

We have been welcome people's involvement.

**Comment by eugeneYWang** [comment]
@kaigai Thank you for answering!

I also have a question about tuning. For original CPU-based Postgres (9+), parallel connections cost the same work_mem and resources as normal connections, and maximum parallel workers is suggested to be set as the number of CPU cores. So we know how to calculate work_mem and nums of total connections and parallel workers. 

When it comes to GPU Postgres, I guess those rules might change. As the founder of this GPU-based extension, do you have any tuning advice or any instruction about configurations in `postgresql.conf` ?

**Comment by eugeneYWang** [comment]
Just so you know, my case is a postgres 12 used to do heavy geospatial-analytics queries. Currently our CPU-based Postgres VM with 28GB RAM has given 103MB for work_mem and 100 total connections.

**Comment by kaigai** [comment]
Please use Discussions for not an issue topics.
https://github.com/heterodb/pg-strom/discussions

**Comment by eugeneYWang** [comment]
Sure Thank you.
