### ISSUE TITLE
How can I get pg_strom_3.0.tar.gz?

### ISSUE THREAD

**Issue by wnn156** [heterodb/pg-strom#518]
I've been experimenting with version 3.0 download at "https://heterodb.github.io/swdc/".
I want to experiment in a new environment, but I can't find it now.
Can I get the pg_strom_3.0.tar.gz?

**Comment by kaigai** [comment]
Not yet.
It is under the final packaging works.

And, please use Discussions for not-an-issue.
https://github.com/heterodb/pg-strom/discussions
