### ISSUE TITLE
pg2arrow aborts

### ISSUE THREAD

**Issue by thrasibule** [heterodb/pg-strom#523]
I'm trying the pg2arrow tool compiled from source as of ce01e37, but it crashes with the following error:
```
pg2arrow: arrow_write.c:786: addBufferArrowBlockVector: Assertion `ArrowNodeIs(b, Block)' failed.
Aborted (core dumped)
```
It seems like most of the data gets written out, but it bombs at the footer generation. If I look into the tag of the block that causes the asert, they're ``ArrowNodeTag__Null`` instead of ``ArrowNodeTag__Block``. Any idea what might be causing this? This is with postgresql 13.3.

**Comment by kaigai** [comment]
Could you show us the backtrace, if core dump is successfully generated?

**Comment by kaigai** [comment]
`addBufferArrowBlockVector` that includes `arrow_write.c:786` is only called by `createArrowFooter` to generate dictionary-batches and record-batches.
Is your query output contains any Enum data types in PostgreSQL?
If Enum data types are contained, pg2arrow tries to generate dictionary-batch, and it is relatively less tested...

**Comment by kaigai** [comment]
Does cb994a20b2476fc2ee7b4c62421009fced50a6a0 solve the issue?

I'm not certain whether this fix solves your problem, however, it exactly destroyes the table->recordBatches[] array if multiple enum data types are used, then it is passed to `addBufferArrowBlockVector` eventually.

**Comment by thrasibule** [comment]
Yes it does, thanks! I did have multiple enums in that queries indeed.
