### ISSUE TITLE
3.0 build issue

### ISSUE THREAD

**Issue by devrimgunduz** [heterodb/pg-strom#526]
Hi,

I cannot build 3.0 on my RHEL 8 box. heterodb_extra.h file does not even exist in the tarball. What am I missing?

> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC  -D__PGSTROM_MODULE__=1 "-DPGSTROM_VERSION=\"3.0\"" -DCPU_ARCH=\"x86_64\" -DPGSHAREDIR=\"/usr/pgsql-12/share\" -DPGSERV_INCLUDEDIR=\"/usr/pgsql-12/include/server\" -DCUDA_INCLUDE_PATH=\"/usr/local/cuda/include\" -DCUDA_BINARY_PATH=\"/usr/local/cuda/bin\" -DCUDA_LIBRARY_PATH=\"/usr/local/cuda/lib64\" -DCUDA_MAXREGCOUNT=128 -DCMD_GPUINFO_PATH=\"/usr/pgsql-12/bin/gpuinfo\" -DPGSTROM_GITHASH=\"HEAD\" -I /usr/local/cuda/include -I. -I./ -I/usr/pgsql-12/include/server -I/usr/pgsql-12/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o src/gpu_device.o src/gpu_device.c
In file included from src/shmbuf.c:12:
src/pg_strom.h:220:10: fatal error: heterodb_extra.h: No such file or directory
 #include <heterodb_extra.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: src/shmbuf.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from src/datastore.c:13:
src/pg_strom.h:220:10: fatal error: heterodb_extra.h: No such file or directory
 #include <heterodb_extra.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: src/datastore.o] Error 1
In file included from src/gpu_device.c:12:
src/pg_strom.h:220:10: fatal error: heterodb_extra.h: No such file or directory
 #include <heterodb_extra.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/extra.c:13:
src/pg_strom.h:220:10: fatal error: heterodb_extra.h: No such file or directory
 #include <heterodb_extra.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/nvrtc.c:12:
src/pg_strom.h:220:10: fatal error: heterodb_extra.h: No such file or directory
 #include <heterodb_extra.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: src/gpu_device.o] Error 1
In file included from src/codegen.c:12:
src/pg_strom.h:220:10: fatal error: heterodb_extra.h: No such file or directory
 #include <heterodb_extra.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: src/nvrtc.o] Error 1
make[1]: *** [<builtin>: src/extra.o] Error 1
In file included from src/main.c:12:
src/pg_strom.h:220:10: fatal error: heterodb_extra.h: No such file or directory
 #include <heterodb_extra.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/cuda_program.c:12:
src/pg_strom.h:220:10: fatal error: heterodb_extra.h: No such file or directory
 #include <heterodb_extra.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: src/codegen.o] Error 1
make[1]: *** [<builtin>: src/main.o] Error 1
make[1]: *** [<builtin>: src/cuda_program.o] Error 1

**Comment by kaigai** [comment]
It is provided in the heterodb-extra package, from:
https://heterodb.github.io/swdc/yum/rhel8-x86_64/heterodb-extra-3.0-3.el8.x86_64.rpm

**Comment by devrimgunduz** [comment]
Oh, ok. There is no such comment in the release notes, so... 

That said, how can I get the source rpm for that binary RPM? I'm publishing pg_strom via PGDG non-free RPM repository, and I must make sure that each component can be rebuilt on our build servers.

**Comment by kaigai** [comment]
Ah... The `heterodb-extra` is the non-free portion of PG-Strom; that handles GPUDirect SQL mainly.
So, PG-Strom tarball may need to package its header files for the standalone build.
Please wait for renewal of the package?

As an aside, even if the heterodb-extra.so library is not installed, PG-Strom will work, but no GPUDirect SQL support.

**Comment by devrimgunduz** [comment]
Hi @kaigai ,

> Ah... The `heterodb-extra` is the non-free portion of PG-Strom; that handles GPUDirect SQL mainly.
> So, PG-Strom tarball may need to package its header files for the standalone build.
> Please wait for renewal of the package?

Sure, but please make sure that you bump up the version number as well :)
 
> As an aside, even if the heterodb-extra.so library is not installed, PG-Strom will work, but no GPUDirect SQL support.

That is ok, I think.

Regards, Devrim

**Comment by kaigai** [comment]
One point I want to confirm. How about CUDA Toolkit provided by NVIDIA?
PG-Strom depends on CUDA Toolkit to control GPU devices, of course.
However, its source code is not disclosed.

**Comment by kaigai** [comment]
The new PG-Strom 3.1-1 package should be built without heterodb-extra module.
We copied its header definitions to PG-Strom also.

https://heterodb.github.io/swdc/

**Comment by devrimgunduz** [comment]
Thanks! It works.
