### ISSUE TITLE
RTX 2070 super / ubuntu 20.04 / postgres-12.8 / pg_stom-3.1 / pg_strom.enabled off / no other error indications

### ISSUE THREAD

**Issue by mattcsl** [heterodb/pg-strom#531]
I can't seem to get this running on my rtx 2070 super / ubuntu 20.04 / postgresql 12.8

Any help would be extremely appreciated!
Thanks!

Output from nvidia-smi:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:0A:00.0  On |                  N/A |
|  0%   43C    P8    24W / 215W |    392MiB /  7979MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1495      G   /usr/lib/xorg/Xorg                 60MiB |
|    0   N/A  N/A      2066      G   /usr/lib/xorg/Xorg                183MiB |
|    0   N/A  N/A      2263      G   /usr/bin/gnome-shell               39MiB |
|    0   N/A  N/A      2754      G   ...AAAAAAAAA= --shared-files       96MiB |
+-----------------------------------------------------------------------------+

Output from postgresql-12-main.log:
155 2021-08-22 11:28:45.365 PDT [55885] LOG:  NVRTC 11.4 is successfully loaded.
156 2021-08-22 11:28:45.365 PDT [55885] LOG:  HeteroDB Extra module is not available
157 2021-08-22 11:28:45.365 PDT [55885] LOG:  PG-Strom version 3.1 built for PostgreSQL 12
158 2021-08-22 11:28:45.394 PDT [55885] LOG:  starting PostgreSQL 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
159 2021-08-22 11:28:45.394 PDT [55885] LOG:  listening on IPv4 address "127.0.0.1", port 5432
160 2021-08-22 11:28:45.395 PDT [55885] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
161 2021-08-22 11:28:45.608 PDT [55891] LOG:  database system was shut down at 2021-08-22 11:28:42 PDT
162 2021-08-22 11:28:45.608 PDT [55892] LOG:  CUDA Program Builder-1 with NVRTC version 11.4
163 2021-08-22 11:28:45.608 PDT [55893] LOG:  CUDA Program Builder-0 with NVRTC version 11.4
164 2021-08-22 11:28:45.613 PDT [55885] LOG:  database system is ready to accept connections

Output from postgresql show all;
 pg_strom.cuda_visible_devices           |                                         | CUDA_VISIBLE_DEVICES environment variables
 pg_strom.debug_jit_compile_options      | off                                     | Enables debug options on GPU kernel build
 pg_strom.enable_brin                    | on                                      | Enables to use BRIN-index
 pg_strom.enable_gpucache                | on                                      | Enables GpuCache as a data source for scan
 pg_strom.enable_gpuhashjoin             | on                                      | Enables the use of GpuHashJoin logic
 pg_strom.enable_gpunestloop             | on                                      | Enables the use of GpuNestLoop logic
 pg_strom.enable_gpupreagg               | on                                      | Enables the use of GPU preprocessed aggregate
 pg_strom.enable_gpuscan                 | on                                      | Enables the use of GPU accelerated full-scan
 pg_strom.enable_partitionwise_gpujoin   | on                                      | (EXPERIMENTAL) Enables partition wise GpuJoin
 pg_strom.enable_partitionwise_gpupreagg | on                                      | (EXPERIMENTAL) Enables partition wise GpuPreAgg
 pg_strom.enabled                        | off                                     | Enables the planner's use of PG-Strom
 pg_strom.gpucache_auto_preload          |                                         | list of tables or '*' for GpuCache preloading
 pg_strom.gpupreagg_reduction_threshold  | 20                                      | Minimus reduction ratio to use GpuPreAgg
 pg_strom.max_async_tasks                | 5                                       | Soft limit for CUDA worker threads per backend
 pg_strom.num_program_builders           | 2                                       | number of workers to build CUDA C programs
 pg_strom.nvme_distance_map              |                                         | Manual configuration of optimal GPU for each NVME
 pg_strom.program_cache_size             | 256MB                                   | size of shared program cache
 pg_strom.pullup_outer_join              | on                                      | Enables to pull up GpuJoin under GpuPreAgg
 pg_strom.pullup_outer_scan              | on                                      | Enables to pull up simple outer scan
 pg_strom.reuse_cuda_context             | off                                     | Reuse CUDA context, if query completed successfully

**Comment by kaigai** [comment]
Likely, it is a wrong logic to detect installed GPUs, if heterodb-extra module (currently, it is provided for only RHEL/CentOS) is not installed.
Please try the latest git master.

**Comment by mattcsl** [comment]
This worked thanks!
