### ISSUE TITLE
Problem with undefined symbols when I ctreate extensions in pg

### ISSUE THREAD

**Issue by Cerdore** [heterodb/pg-strom#532]
Hi!
    The PG I use is built from source code. Also I want to use pg-strom built from source. But when I try to use pg strom, I get an error.
    `ERROR:  could not load library "/home/xsdb/pg/pg/lib/postgresql/pg_strom.so": /home/xsdb/pg/pg/lib/postgresql/pg_strom.so: undefined symbol: cuIpcOpenMemHandle_v2`
    Then I tried to perform two operations. The first was to see how many undefined symbols the .so file had, and the second was to see where exactly those undefined files were.
    First,  I used command 'ldd -r xxx/pg_strom.so', and got this:
![image](https://user-images.githubusercontent.com/24353799/132089187-fae296c6-dab2-46c5-a013-a7a77e9ce6e8.png)
    It looks like some libraries are missing when I used "make install PG_CONFIG=/home/xsdb/pg/pg/bin/pg_config". But I don't know why this question came up.
    
![image](https://user-images.githubusercontent.com/24353799/132091168-6c21ecaf-49a8-4594-bae1-9196b0d521fc.png)

    Looking forward to hearing from you！

**Comment by kaigai** [comment]
Which version of CUDA Toolkit you installed?

Please confirm CUDA 11.4 and suitable nvidia driver are installed on your environment.

**Comment by Cerdore** [comment]
> Which version of CUDA Toolkit you installed?
> 
> Please confirm CUDA 11.4 and suitable nvidia driver are installed on your environment.

Thank you for your reply!

I am using CUDA 11.4. Because I'm using docker, my cuda version is higher than my nvidia driver version.
Except for the library function cuIpcOpenMemHandle_v2, the other undefined symbols such as RegisterCustomScanMethods seem to come from PG. Do I need to pay any special attention to the PG built from the source, such as Makefile.

**Comment by kaigai** [comment]
Please use the supported nvidia driver version.

`/usr/lib64/libcuda.*` is distributed as a part of nvidia driver.

**Comment by Cerdore** [comment]
![image](https://user-images.githubusercontent.com/24353799/132094950-42b613f5-0327-4ed2-979e-93c655c78f5a.png)

"/usr/local/lib64" is in My LD_LIBRARY_PATH.

![image](https://user-images.githubusercontent.com/24353799/132095780-791d9f87-b7b2-4364-8365-535cc4e74f2a.png)

I will go to see if the version is appropriate....
Thank you!

**Comment by Cerdore** [comment]
Hi, I've solved this problem by changing the docker image.  Actually, the problem is initially "/usr/bin/ld: cannot find -lnvidia-ml". And because I was using docker, I didn't install the nvidia-driver in container. Now I changed to **image "nvidia/cuda:11.4.1-devel-centos8".**

Thank you for your prompt response! BTW, this is a really excellent work. I think you can post a paper sometime :)
