### ISSUE TITLE
Problems with the debugging execution process of PG-Strom

### ISSUE THREAD

**Issue by Cerdore** [heterodb/pg-strom#533]
Hello! I am now trying to read your source code, starting with debugging the code. 

But I don't understand where the dynamically generated code is called. I would like to know **if there is a way to debug the dynamically generated code.** 

I tried to use perf before to see the order of the code calls, and I didn't see it either.
![image](https://user-images.githubusercontent.com/24353799/132990930-22d29c6d-dcf1-473d-b6c0-e29f6258a67d.png)

Does the 'ExecScan' in "ExecGpuJoin" call the contents of CustomScan?
```
static TupleTableSlot *
ExecGpuJoin(CustomScanState *node)
{
	GpuJoinState *gjs = (GpuJoinState *) node;

	ActivateGpuContext(gjs->gts.gcontext);
	if (!GpuJoinInnerPreload(&gjs->gts, NULL))
		return NULL;
	return ExecScan(&node->ss,
					(ExecScanAccessMtd) pgstromExecGpuTaskState,
					(ExecScanRecheckMtd) ExecReCheckGpuJoin);
}
```

**Comment by kaigai** [comment]
The dynamically generated code is not executed on the CPU's context.
It shall be executed as a part of GPU kernel.

Try `EXPLAIN VERBOSE`, then look at the file displayed at 'kernel source' line.

**Comment by Cerdore** [comment]
Thank you for your timely response. My previous question was a bit confusing and I will take care of it in the future. Thank you again!
