### ISSUE TITLE
Build error against PostgreSQL 14

### ISSUE THREAD

**Issue by devrimgunduz** [heterodb/pg-strom#534]
Hi @kaigai ,

pg_strom fails to build against v14. Can you please take a look? v14 is due next Thursday, so a new release will be appreciated.

Thanks! Devrim

> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC  -D__PGSTROM_MODULE__=1 "-DPGSTROM_VERSION=\"3.1\"" -DCPU_ARCH=\"x86_64\" -DPGSHAREDIR=\"/usr/pgsql-14/share\" -DPGSERV_INCLUDEDIR=\"/usr/pgsql-14/include/server\" -DCUDA_INCLUDE_PATH=\"/usr/local/cuda/include\" -DCUDA_BINARY_PATH=\"/usr/local/cuda/bin\" -DCUDA_LIBRARY_PATH=\"/usr/local/cuda/lib64\" -DCUDA_MAXREGCOUNT=128 -DCMD_GPUINFO_PATH=\"/usr/pgsql-14/bin/gpuinfo\" -DPGSTROM_GITHASH=\"HEAD\" -I /usr/local/cuda/include -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o src/gpu_device.o src/gpu_device.c
src/shmbuf.c: In function '__shmemContextStatsPrint':
src/shmbuf.c:1006:3: error: too few arguments to function 'printfunc'
   printfunc(__context, passthru, temp);
   ^~~~~~~~~
src/shmbuf.c: In function 'pgstrom_init_shmbuf':
src/shmbuf.c:1467:38: warning: assignment to 'void (*)(struct MemoryContextData *, void (*)(struct MemoryContextData *, void *, const char *, _Bool), void *, MemoryContextCounters *, _Bool)' {aka 'void (*)(struct MemoryContextData *, void (*)(struct MemoryContextData *, void *, const char *, _Bool), void *, struct MemoryContextCounters *, _Bool)'} from incompatible pointer type 'void (*)(struct MemoryContextData *, void (*)(struct MemoryContextData *, void *, const char *, _Bool), void *, MemoryContextCounters *)' {aka 'void (*)(struct MemoryContextData *, void (*)(struct MemoryContextData *, void *, const char *, _Bool), void *, struct MemoryContextCounters *)'} [-Wincompatible-pointer-types]
  sharedMemoryContextMethods.stats    = shmemContextStatsPrint;
                                      ^
make[1]: *** [<builtin>: src/shmbuf.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /usr/pgsql-14/include/server/access/tupdesc.h:19,
                 from /usr/pgsql-14/include/server/access/attmap.h:18,
                 from /usr/pgsql-14/include/server/access/tupconvert.h:17,
                 from /usr/pgsql-14/include/server/nodes/execnodes.h:17,
                 from /usr/pgsql-14/include/server/access/brin.h:13,
                 from src/pg_strom.h:22,
                 from src/main.c:12:
src/main.c: In function 'pgstrom_post_planner_recurse':
src/main.c:390:25: error: 'ModifyTable' {aka 'struct ModifyTable'} has no member named 'plans'; did you mean 'plan'?
     foreach (lc, splan->plans)
                         ^~~~~
/usr/pgsql-14/include/server/nodes/pg_list.h:353:38: note: in definition of macro 'foreach'
  for (ForEachState cell##__state = {(lst), 0}; \
                                      ^~~
make[1]: *** [<builtin>: src/main.o] Error 1
make[1]: Leaving directory '/var/lib/pgsql/git/pgrpms/rpm/redhat/master/non-common/pg_strom/master/pg-strom-3.1'

**Comment by kaigai** [comment]
OK, I try to catch up by end of the Sep.

**Comment by devrimgunduz** [comment]
Thanks!

**Comment by kaigai** [comment]
c709699a7c036f252256b269ac89bebc63b293fb and d70a1c1678d4ee76ee09029493c04d5282347c1b allows to compile towards PG14RC. The next v3.3 shall be released in the next week.

**Comment by kaigai** [comment]
Sorry, it was v3.2, not v3.3.

https://heterodb.github.io/swdc/
It should be compilable towards PG14, but we have not done comprehensive tests towards PG14 yet.
So, HeteroDB's SWDC does not provide PG14 packages yet.

**Comment by devrimgunduz** [comment]
Hi @kaigai ,

Getting the error below while compiling 3.2 with PG 14:

> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC  -D__PGSTROM_MODULE__=1 "-DPGSTROM_VERSION=\"3.2\"" -DCPU_ARCH=\"x86_64\" -DPGSHAREDIR=\"/usr/pgsql-14/share\" -DPGSERV_INCLUDEDIR=\"/usr/pgsql-14/include/server\" -DCUDA_INCLUDE_PATH=\"/usr/local/cuda/include\" -DCUDA_BINARY_PATH=\"/usr/local/cuda/bin\" -DCUDA_LIBRARY_PATH=\"/usr/local/cuda/lib64\" -DCUDA_MAXREGCOUNT=128 -DCMD_GPUINFO_PATH=\"/usr/pgsql-14/bin/gpuinfo\" -DPGSTROM_GITHASH=\"HEAD\" -I /usr/local/cuda/include -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o src/misc.o src/misc.c
src/float2.c: In function 'pgstrom_define_shell_type':
src/float2.c:1558:2: error: too many arguments to function 'GenerateTypeDependencies'
  GenerateTypeDependencies(tup,
  ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/pg_strom.h:70,
                 from src/float2.c:12:
/usr/pgsql-14/include/server/catalog/pg_type.h:383:13: note: declared here
 extern void GenerateTypeDependencies(HeapTuple typeTuple,
             ^~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [<builtin>: src/float2.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/var/lib/pgsql/git/pgrpms/rpm/redhat/master/non-common/pg_strom/master/pg-strom-3.2'
error: Bad exit status from /var/tmp/rpm-tmp.KAqBdO (%build)

**Comment by kaigai** [comment]
Can you confirm whether the source tarball is exactly v3.2?

We already added `#if ... #endif` block for the `GenerateTypeDependencies()` to pass build towards PG14.

```
$ tar zxf pg_strom-3.2.tar.gz
$ cd pg_strom-3.2/
$ make PG_CONFIG=/usr/pgsql-14/bin/pg_config
        :
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC  -D__PGSTROM_MODULE__=1 "-DPGSTROM_VERSION=\"3.2\"" -DCPU_ARCH=\"x86_64\" -DPGSHAREDIR=\"/usr/pgsql-14/share\" -DPGSERV_INCLUDEDIR=\"/usr/pgsql-14/include/server\" -DCUDA_INCLUDE_PATH=\"/usr/local/cuda/include\" -DCUDA_BINARY_PATH=\"/usr/local/cuda/bin\" -DCUDA_LIBRARY_PATH=\"/usr/local/cuda/lib64\" -DCUDA_MAXREGCOUNT=128 -DCMD_GPUINFO_PATH=\"/usr/pgsql-14/bin/gpuinfo\" -DPGSTROM_GITHASH=\"v3.2\" -I /usr/local/cuda/include -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o src/aggfuncs.o src/aggfuncs.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC  -D__PGSTROM_MODULE__=1 "-DPGSTROM_VERSION=\"3.2\"" -DCPU_ARCH=\"x86_64\" -DPGSHAREDIR=\"/usr/pgsql-14/share\" -DPGSERV_INCLUDEDIR=\"/usr/pgsql-14/include/server\" -DCUDA_INCLUDE_PATH=\"/usr/local/cuda/include\" -DCUDA_BINARY_PATH=\"/usr/local/cuda/bin\" -DCUDA_LIBRARY_PATH=\"/usr/local/cuda/lib64\" -DCUDA_MAXREGCOUNT=128 -DCMD_GPUINFO_PATH=\"/usr/pgsql-14/bin/gpuinfo\" -DPGSTROM_GITHASH=\"v3.2\" -I /usr/local/cuda/include -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o src/float2.o src/float2.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC  -D__PGSTROM_MODULE__=1 "-DPGSTROM_VERSION=\"3.2\"" -DCPU_ARCH=\"x86_64\" -DPGSHAREDIR=\"/usr/pgsql-14/share\" -DPGSERV_INCLUDEDIR=\"/usr/pgsql-14/include/server\" -DCUDA_INCLUDE_PATH=\"/usr/local/cuda/include\" -DCUDA_BINARY_PATH=\"/usr/local/cuda/bin\" -DCUDA_LIBRARY_PATH=\"/usr/local/cuda/lib64\" -DCUDA_MAXREGCOUNT=128 -DCMD_GPUINFO_PATH=\"/usr/pgsql-14/bin/gpuinfo\" -DPGSTROM_GITHASH=\"v3.2\" -I /usr/local/cuda/include -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o src/tinyint.o src/tinyint.c
     :
```

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.

**Comment by devrimgunduz** [comment]
5.0 alpha1 throws some build warnings, but builds fine.
