### ISSUE TITLE
cannot set pg_strom.enabled to on

### ISSUE THREAD

**Issue by maliabd-al-majid** [heterodb/pg-strom#538]
Hi Sir,

I have installed pg_strom V3.1 , but i found that pg_strom.enabled is set to off and i can't change it to on.
I have ubuntu 20.04, with GPU NVIDIA GeForce RTX 3070,  Nvidia Driver "470.63.01" with cuda 11.4 "Cuda compilation tools, release 11.4, V11.4.120", and postgresql 13.

i have checked the postgresql log file:

> 2021-09-28 17:16:51.446 CEST [36636] LOG:  background worker "logical replication launcher" (PID 36650) exited with exit code 1
2021-09-28 17:16:51.448 CEST [36645] LOG:  shutting down
2021-09-28 17:16:51.471 CEST [36636] LOG:  shared memory segment [.pg_shmbuf_5432.0:0] is removed.
2021-09-28 17:16:51.487 CEST [36636] LOG:  database system is shut down
2021-09-28 17:16:51.596 CEST [36844] LOG:  NVRTC 11.4 is successfully loaded.
2021-09-28 17:16:51.596 CEST [36844] LOG:  HeteroDB Extra module is not available
2021-09-28 17:16:51.596 CEST [36844] LOG:  PG-Strom version 3.1 built for PostgreSQL 13
2021-09-28 17:16:53.040 CEST [36844] LOG:  starting PostgreSQL 13.4 (Ubuntu 13.4-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
2021-09-28 17:16:53.040 CEST [36844] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-28 17:16:53.042 CEST [36844] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-09-28 17:16:53.045 CEST [36850] LOG:  database system was shut down at 2021-09-28 17:16:51 CEST
2021-09-28 17:16:53.046 CEST [36851] LOG:  CUDA Program Builder-1 with NVRTC version 11.4
2021-09-28 17:16:53.046 CEST [36852] LOG:  CUDA Program Builder-0 with NVRTC version 11.4
2021-09-28 17:16:53.049 CEST [36844] LOG:  database system is ready to accept connections
2021-09-28 17:17:18.833 CEST [36882] postgres@postgres ERROR:  parameter "pg_strom.enabled" cannot be changed
2021-09-28 17:17:18.833 CEST [36882] postgres@postgres STATEMENT:  set pg_strom.enabled = on;

so please assist me in solving issue.

**Comment by kaigai** [comment]
What is your `gpuinfo` output?
It looks to me no GPU devices are recognized.

**Comment by maliabd-al-majid** [comment]
GPU device information from running "lshw -C display"

>   *-display                 
       description: VGA compatible controller
       product: TigerLake-LP GT2 [Iris Xe Graphics]
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       logical name: /dev/fb0
       version: 01
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=i915 latency=0 mode=1920x1080 visual=truecolor xres=1920 yres=1080
       resources: iomemory:620-61f iomemory:400-3ff irq:186 memory:622e000000-622effffff memory:4000000000-400fffffff ioport:5000(size=64) memory:c0000-dffff memory:4010000000-4016ffffff memory:4020000000-40ffffffff
  *-display
       description: VGA compatible controller
       product: GA104M [GeForce RTX 3070 Mobile / Max-Q]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: iomemory:600-5ff iomemory:620-61f irq:187 memory:85000000-85ffffff memory:6000000000-61ffffffff memory:6200000000-6201ffffff ioport:4000(size=128) memory:86000000-8607ffff

**Comment by kaigai** [comment]
What I mention is the `gpuinfo` command output; installed as a part of PG-Strom package.

What does `/usr/pgsql-13/bin/gpuinfo` say?

**Comment by maliabd-al-majid** [comment]
I couldn't find it in bin folder, i found it in "./pg-strom-3.1/utils/gpuinfo"
here are its results:
> CUDA Runtime version: 11.4.0
NVIDIA Driver version: 470.63
Number of devices: 0

**Comment by kaigai** [comment]
It wonder whether `cuDeviceGetCount()` can recognize the installed device.
Does `nvidia-smi` shows your device correctly?

**Comment by maliabd-al-majid** [comment]
this is the result of nvidia-smi:

![image](https://user-images.githubusercontent.com/16827753/135184795-0d54dbcf-609b-436c-a3a2-ca15240fc63d.png)

**Comment by maliabd-al-majid** [comment]
i have tested cuda samples, and here are the results:
it shows that cuda was able to detect one device.

> CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "NVIDIA GeForce RTX 3070 Laptop GPU"
  CUDA Driver Version / Runtime Version          11.4 / 11.4
  CUDA Capability Major/Minor version number:    8.6
  Total amount of global memory:                 7982 MBytes (8370061312 bytes)
  (040) Multiprocessors, (128) CUDA Cores/MP:    5120 CUDA Cores
  GPU Max Clock rate:                            1290 MHz (1.29 GHz)
  Memory Clock rate:                             6001 Mhz
  Memory Bus Width:                              256-bit
  L2 Cache Size:                                 4194304 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total shared memory per multiprocessor:        102400 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1536
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Managed Memory:                Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 11.4, CUDA Runtime Version = 11.4, NumDevs = 1
Result = PASS

**Comment by kaigai** [comment]
Do you install multiple CUDA versions?
If so, please rebuild PG-Strom towards the latest CUDA toolkit you install.
I doubt the binary is linked to wrong cuda library.

**Comment by maliabd-al-majid** [comment]
Thanks for your reply.
yes, I have two Cuda versions "11.4" and "10.1". I will rebuild it and get back to you.

**Comment by maliabd-al-majid** [comment]
I have removed Cuda 10.1 and kept only "11.4", and rebuilt PG-Strom, but I am still getting the same error that I can't enable pg_strom.

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
