### ISSUE TITLE
Question about creating foreign table with arrow-fdw

### ISSUE THREAD

**Issue by Cerdore** [heterodb/pg-strom#539]
Hi! 

I met some error when I try using arrow-fdw. My pg-strom is built from source.

Do you have any suggestions? Looking forward to your advice.
![image](https://user-images.githubusercontent.com/24353799/135257311-50e87c53-bdbc-42eb-a953-07d91162a980.png)

**Comment by kaigai** [comment]
As literal, it seems to me `/home/xsdb/arrow/logdata.arrow` is not found from the PostgreSQL server process.

**Comment by Cerdore** [comment]
So I should do some operations before create foreign table?
Sorry, I don't know how this file was generated...

**Comment by Cerdore** [comment]
Oh, I found it... "How to make Arrow files" -> "Writable Arrow_Fdw". Thank you!

**Comment by kaigai** [comment]
Or, use `pg2arrow` to dump exisgin table as an arrow file.

**Comment by Cerdore** [comment]
Thank you!

**Comment by Cerdore** [comment]
Thank you very much for your patience! I will check apache arrow's format document.
