### ISSUE TITLE
(JP) gcontext->optimal_gpu をbitmapに

### ISSUE THREAD

**Issue by kaigai** [heterodb/pg-strom#541]
AMD EPYC CPUのようにPCI-Eレーン数が多いマシンだと、あるNVME-SSDに対して最適なGPUが複数存在してよい事になる。
その場合、Optimal GPUは「どれでもよい」ことになる。

A100のMICを使って仮想GPUにする場合でも同様。

**Comment by jamie-lai** [comment]
small Japanese

**Comment by kaigai** [comment]
実装自体は e5e6a78e07fcb01acd4a8272ca0d41fe30f454aa にて。
テスト環境を作らねば…。

**Comment by kaigai** [comment]
Sorry, issues with `(JP)` mark are almost my personal memo.

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
