### ISSUE TITLE
Fail to use GPU Direct SQL feature  for ioctl encounter error

### ISSUE THREAD

**Issue by shaowei** [heterodb/pg-strom#543]
Hi This is my environment

```
[root@localhost ~]# modinfo nvme_strom
filename:       /lib/modules/3.10.0-1127.19.1.el7.x86_64/extra/nvme_strom.ko.xz
version:        3.0-3.el7
license:        BSD
description:    SSD-to-GPU Direct SQL Module
author:         KaiGai Kohei <kaigai@heterodb.com>
retpoline:      Y
rhelversion:    7.8
depends:        
vermagic:       3.10.0-1127.19.1.el7.x86_64 SMP mod_unload modversions 
parm:           verbose:Enables debug messages (1=on, 2=verbose) (int)
parm:           stat_enabled:Enables run-time statistics (int)
parm:           p2p_dma_max_depth:Max number of concurrent P2P DMA requests per NVME device
parm:           p2p_dma_max_unitsz:Max length of single DMA request in kB
parm:           fast_ssd_mode:Use SSD2GPU Direct even if clean page caches exist (int)
parm:           license:License validation status
```

```
[root@localhost ~]# modinfo nvme-rdma
filename:       /lib/modules/3.10.0-1127.19.1.el7.x86_64/extra/nvme-rdma.ko.xz
version:        3.0
description:    Enhanced nvme-rdma for SSD-to-GPU Direct SQL
license:        GPL v2
retpoline:      Y
rhelversion:    7.8
srcversion:     AC520F98955EA7EAA824CE3
depends:        nvme-fabrics,ib_core,nvme-core,rdma_cm
vermagic:       3.10.0-1127.19.1.el7.x86_64 SMP mod_unload modversions 
parm:           register_always:Use memory registration even for contiguous memory regions (bool)
```

```
[root@localhost ~]# /usr/local/cuda/gds/tools/gdscheck -p
 ============
 ENVIRONMENT:
 ============
 =====================
 DRIVER CONFIGURATION:
 =====================
 NVMe               : Unsupported
 NVMeOF             : Unsupported
 SCSI               : Unsupported
 ScaleFlux CSD      : Unsupported
 NVMesh             : Unsupported
 DDN EXAScaler      : Unsupported
 IBM Spectrum Scale : Unsupported
 NFS                : Unsupported
 WekaFS             : Unsupported
 Userspace RDMA     : Unsupported
 --Mellanox PeerDirect : Disabled
 --rdma library        : Not Loaded (libcufile_rdma.so)
 --rdma devices        : Not configured
 --rdma_device_status  : Up: 0 Down: 0
 =====================
 CUFILE CONFIGURATION:
 =====================
 properties.use_compat_mode : true
 properties.gds_rdma_write_support : true
 properties.use_poll_mode : false
 properties.poll_mode_max_size_kb : 4
 properties.max_batch_io_timeout_msecs : 5
 properties.max_direct_io_size_kb : 16384
 properties.max_device_cache_size_kb : 131072
 properties.max_device_pinned_mem_size_kb : 33554432
 properties.posix_pool_slab_size_kb : 4 1024 16384 
 properties.posix_pool_slab_count : 128 64 32 
 properties.rdma_peer_affinity_policy : RoundRobin
 properties.rdma_dynamic_routing : 0
 fs.generic.posix_unaligned_writes : false
 fs.lustre.posix_gds_min_kb: 0
 fs.weka.rdma_write_support: false
 profile.nvtx : false
 profile.cufile_stats : 0
 miscellaneous.api_check_aggressive : false
 =========
 GPU INFO:
 =========
 GPU index 0 Tesla P100-PCIE-16GB bar:1 bar size (MiB):16384 supports GDS
 ==============
 PLATFORM INFO:
 ==============
 IOMMU: disabled
 Platform verification succeeded
[root@localhost ~]# 
```

```
PostgreSQL 11

pg_strom 2.3

HW is:
	SSD: SSDPEDKE040T7L
	
```

```
the case:
test04=# \dt+
                      List of relations
 Schema |   Name   | Type  |  Owner   |  Size   | Description 
--------+----------+-------+----------+---------+-------------
 public | customer | table | postgres | 0 bytes | 
 public | lineitem | table | postgres | 8788 MB | 
 public | nation   | table | postgres | 0 bytes | 
 public | orders   | table | postgres | 0 bytes | 
 public | part     | table | postgres | 0 bytes | 
 public | partsupp | table | postgres | 0 bytes | 
 public | region   | table | postgres | 0 bytes | 
 public | supplier | table | postgres | 0 bytes | 
 public | test2    | table | postgres | 9647 MB | 
 public | test3    | table | postgres | 9647 MB | 
(10 rows)


postgres=# set pg_strom.nvme_strom_enabled =on;  
SET  
postgres=# set pg_strom.nvme_strom_threshold ='512MB';  
SET  
postgres=#  explain (analyze,verbose,timing,costs,buffers) select count(*) from test2 where c1=1 and c2=1 and c3=1; 
------------------
 Aggregate  (cost=821044.92..821044.93 rows=1 width=8) (actual time=8783.517..8783.517 rows=1 loops=1)
   Output: count(*)
   Buffers: shared hit=160 read=1234568
   ->  Gather  (cost=29304.50..821044.91 rows=1 width=0) (actual time=8783.502..8784.003 rows=0 loops=1)
         Workers Planned: 2
         Workers Launched: 0
         Buffers: shared hit=160 read=1234568
         ->  Parallel Custom Scan (GpuScan) on public.test3  (cost=28304.50..820044.81 rows=0 width=0) (actual time=8783.067..8783.06
8 rows=0 loops=1)
               GPU Filter: ((test3.c1 = 1) AND (test3.c2 = 1) AND (test3.c3 = 1))
               Rows Removed by GPU Filter: 100000000
               GPU Preference: None
               Kernel Source: /usr/nvme1/shaowei/pgdebug/data/pgsql_tmp/pgsql_tmp_strom_116668.0.gpu
               Kernel Binary: /usr/nvme1/shaowei/pgdebug/data/pgsql_tmp/pgsql_tmp_strom_116668.1.ptx
               Buffers: shared hit=160 read=1234568
 Planning Time: 3.592 ms
 Execution Time: 8916.117 ms
```

this is the error from dmesg:
[2167902.585653] nvme-strom: only workable on regular files

I try to debug with gdb and found that in pg_strom src/nvme_strom.c's function _**nvme_strom_ioctl(STROM_IOCTL__CHECK_FILE, uarg)**_ fails for ioctl encounter error,Invalid argument.
It is because uarg->fdesc is a fd of directory.

**Comment by kaigai** [comment]
Please try it again with the latest PG-Strom (v3.2) and the latest kmod driver.
It looks to me RHEL7, so NVIDIA GPUDirect Storage will not be available.

And, table size to be scanned may not exceed the threshold by `pg_strom.gpudirect_threshold`.

**Comment by shaowei** [comment]
But, actually PG-Strom(V2.3) support GPU Direct SQL, right?
I try to test the nvme with https://github.com/enfiskutensykkel/nvme-strom, using nvme-strom/utils/nvme_test. it shows that nvme device works.
```
[root@localhost utils]# ./nvme_test -f /usr/nvme1/casia/shaowei/nvmetest/PG_11_201809051/25019/26505
shaowei nvme_strom_ioctl rc:0
shaowei uarg.ndisks:1
GPU[0] Tesla P100-PCIE-16GB - file: /usr/nvme1/casia/shaowei/nvmetest/PG_11_201809051/25019/26505, i/o size: 1024.00MB by VFS (i/o unitsz: 32768KB), buffer 32MB x 6
read: 1024.00MB, time: 246ms, throughput: 4.07GB/s
sem_wait: 0us
[root@localhost utils]# 
```

But if I try to test with path of folder, it can not work.

```
[root@localhost utils]# ./nvme_test -f /usr/nvme1/casia/shaowei/nvmetest/PG_11_201809051/25019/
shaowei nvme_strom_ioctl rc:-1
shaowei uarg.ndisks:0
STROM_IOCTL__CHECK_FILE('/usr/nvme1/casia/shaowei/nvmetest/PG_11_201809051/25019/') --> -1: Invalid argument
[root@localhost utils]# 
```


I think the environment about SSD-TO-GPU is ok. My question is why it can not work with path of folder ,so does PG-Strom V2.3? 
Should I config the device "/proc/nvme_strom"?

**Comment by shaowei** [comment]
I found that I am using PG-Storm 2.3,but in my machine nvme_storm version is 3.0-3.el7. Should I install an other version nvme_strom.

> [root@localhost ~]# modinfo nvme_strom
> filename:       /lib/modules/3.10.0-1127.19.1.el7.x86_64/extra/nvme_strom.ko.xz
> version:        3.0-3.el7
> license:        BSD
> description:    SSD-to-GPU Direct SQL Module
> author:         KaiGai Kohei <kaigai@heterodb.com>
> retpoline:      Y
> rhelversion:    7.8
> depends:        
> vermagic:       3.10.0-1127.19.1.el7.x86_64 SMP mod_unload modversions 
> parm:           verbose:Enables debug messages (1=on, 2=verbose) (int)
> parm:           stat_enabled:Enables run-time statistics (int)
> parm:           p2p_dma_max_depth:Max number of concurrent P2P DMA requests per NVME device
> parm:           p2p_dma_max_unitsz:Max length of single DMA request in kB
> parm:           fast_ssd_mode:Use SSD2GPU Direct even if clean page caches exist (int)
> parm:           license:License validation status
> [root@localhost ~]# 

By the way, I try to  find source code of nvme_strom，but I just found https://github.com/kaigai/nvme-kmod. There is not any infomation about version with it. Confused.

**Comment by kaigai** [comment]
The latest version of kernel module and related are:
- heterodb-extra-3.1-1.el7.x86_64.rpm
- heterodb-kmod-3.1-1.el7.x86_64.rpm

Please don't use such older version.

> By the way, I try to find source code of nvme_strom，but I just found https://github.com/kaigai/nvme-kmod. There is not any infomation about version with it. Confused.

That is my sandbox when I started to develop the nvme_strom kernel module 5 years before.
Of course, its APIs are already invalid and not make sense in the recent days.

**Comment by Jiwangreal** [comment]
> The latest version of kernel module and related are:
> 
> * heterodb-extra-3.1-1.el7.x86_64.rpm
> * heterodb-kmod-3.1-1.el7.x86_64.rpm
> 
> Please don't use such older version.
> 
> > By the way, I try to find source code of nvme_strom，but I just found https://github.com/kaigai/nvme-kmod. There is not any infomation about version with it. Confused.
> 
> That is my sandbox when I started to develop the nvme_strom kernel module 5 years before. Of course, its APIs are already invalid and not make sense in the recent days.

hi,when I try to install heterodb-kmod-3.2-1.el7.x86_64.rpm in CentOS7, there is a error： ERROR: fstatat(4, nvme_strom.ko.xz): No such file or directory。

Pls help me, how to solve the problem?thanks befor!!

**Comment by Jiwangreal** [comment]
> > The latest version of kernel module and related are:
> > 
> > * heterodb-extra-3.1-1.el7.x86_64.rpm
> > * heterodb-kmod-3.1-1.el7.x86_64.rpm
> > 
> > Please don't use such older version.
> > > By the way, I try to find source code of nvme_strom，but I just found https://github.com/kaigai/nvme-kmod. There is not any infomation about version with it. Confused.
> > 
> > 
> > That is my sandbox when I started to develop the nvme_strom kernel module 5 years before. Of course, its APIs are already invalid and not make sense in the recent days.
> 
> hi,when I try to install heterodb-kmod-3.2-1.el7.x86_64.rpm in CentOS7, there is a error： ERROR: fstatat(4, nvme_strom.ko.xz): No such file or directory。
> 
> Pls help me, how to solve the problem?thanks befor!!

hi，after restart PG，it shows:
2022-01-10 15:54:29.451 CST [9138] LOG:  00000: HeteroDB Extra module loaded [api_version=20211018,cufile=off,nvme_strom=off

but os has installed nvme_strom
[postgres@node2 ~]$ modinfo nvme_strom
filename:       /lib/modules/3.10.0-1160.45.1.el7.x86_64/extra/nvme_strom.ko

how to sole this problem?

**Comment by kaigai** [comment]
Does your system load the `nvme_strom` module onto the kernel space?
If not, try `sudo modprobe nvme_strom`. Then, it creates the `/proc/nvme-strom` pseudo file entry.

**Comment by Jiwangreal** [comment]
> Does your system load the `nvme_strom` module onto the kernel space? If not, try `sudo modprobe nvme_strom`. Then, it creates the `/proc/nvme-strom` pseudo file entry.

Hi, After I loaded the nvme_strom module, there dispalys :
[root@node2 src]# modprobe nvme_strom
modprobe: ERROR: could not insert 'nvme_strom': Unknown symbol in module, or unknown parameter (see dmesg)

[root@node2 src]# dmesg |tail -2
[53544.945541] nvme-strom: extra symbol "nvme_alloc_request" at [nvme_core] must be inbox driver
[53791.288731] nvme-strom: extra symbol "nvme_alloc_request" at [nvme_core] must be inbox driver

My env is CentOS7(3.10.0-1160.45.1.el7.x86_64)，How to solve this? This question is whether about  MLNX_OFED_LINUX?

Rencently, I have uninstalled MLNX_OFED_LINUX everything and not want to use this.

I see you code of usr\src\debug\heterodb-extra-3.2-1\extra\misc.c, access("/proc/nvme-strom", F_OK) shouble be created by command modprobe nvme_strom.

**Comment by kaigai** [comment]
> Rencently, I have uninstalled MLNX_OFED_LINUX everything and not want to use this.

I guess the kernel module was not uninstalled correctly.
Could you check which module provides `nvme` kernel module.
This dmesg indicates that mellanox's nvme driver is loaded to the kernel space.

If `nvme` driver is installed under the `/lib/modules/<kernel version>/extra`.

**Comment by Jiwangreal** [comment]
Yes, I change another kernel to install nvme_strom and it works !Now, restarting PG can see :
2022-01-11 14:54:44.008 CST [89165] LOG:  00000: HeteroDB Extra module loaded [api_version=20211018,cufile=off,nvme_strom=on]

but it can not support cufile, I do not see any dirver in /proc/driver/nvidia-fs/version after install gds-nvidia-fs-master or any nvidia-gds of nvidia-fs rpm, may be the kernel verserion must in Linux kernel between 4.15.0.x and 5.4.0.x？（My new kernel : 3.10.0-1160.49）

another problem is the following sql whether indicate using GPU director SQL?
nvme0n1         259:0    0   1.5T  0 disk /mnt/gds_test
postgres=# \db;
          List of tablespaces
    Name    |  Owner   |   Location
------------+----------+---------------
 my_nvme    | postgres | /mnt/gds_test

postgres=# explain (analyze,verbose,timing,costs,buffers) select count(*) from test2;
                                                                  QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=1256041.03..1256041.04 rows=1 width=8) (actual time=13915.365..13915.371 rows=1 loops=1)
   Output: pgstrom.sum((pgstrom.nrows()))
   Buffers: shared hit=1186793 read=47935
   ->  Custom Scan (GpuPreAgg) on public.test2  (cost=1256041.02..1256041.03 rows=1 width=8) (actual time=13915.302..13915.320 rows=1 loops=1)
         Output: (pgstrom.nrows())
         GPU Output: (pgstrom.nrows())
         GPU Setup: '1'::bigint
         Reduction: NoGroup
         Outer Scan: public.test2  (cost=4000.00..1240416.02 rows=100000008 width=0) (actual time=85.453..13764.897 rows=100000000 loops=1)
         **GPU Preference: None------------is it normal?**

Thanks for your patience from a  new PGer.

**Comment by kaigai** [comment]
Please check GDS requirement. It needs RHEL8.3 or later, and Mellanox driver built with GDS enabled.
The `nvme_strom` is an independent module to run GPU-Direct SQL on RHEL7.

> another problem is the following sql whether indicate using GPU director SQL?

Can you see the following log message (that is on my server) on starup?
If heterodb_extra module detects local nvme devices correctly, it shall show the closest GPU to be used for GPU-Direct SQL.
```
2022-01-11 17:24:48.907 JST [3754456] LOG:  PG-Strom: GPU0 NVIDIA A100-PCIE-40GB (108 SMs; 1410MHz, L2 40960kB), RAM 39.59GB (5120bits, 1.16GHz), PCI-E Bar1 64GB, CC 8.0
2022-01-11 17:24:48.912 JST [3754456] LOG:  - nvme4n1 (Corsair MP600 CORE; 0000:c6:00.0) --> GPU0
2022-01-11 17:24:48.912 JST [3754456] LOG:  - nvme0n1 (INTEL SSDPF2KX038TZ; 0000:c1:00.0) --> GPU0
2022-01-11 17:24:48.912 JST [3754456] LOG:  - nvme2n1 (INTEL SSDPF2KX038TZ; 0000:c3:00.0) --> GPU0
2022-01-11 17:24:48.912 JST [3754456] LOG:  - nvme3n1 (INTEL SSDPF2KX038TZ; 0000:c4:00.0) --> GPU0
2022-01-11 17:24:48.912 JST [3754456] LOG:  - nvme1n1 (INTEL SSDPF2KX038TZ; 0000:c2:00.0) --> GPU0
```

**Comment by Jiwangreal** [comment]
Do you have a plan to support related curfile API to  speed SQL up on GPU?

There is no any curfile  code Implementation in PG-Strom.
/*
 * cufile.c
 */
extern bool		cuFileDriverLoaded(void);
extern void		pgstrom_init_cufile(void);

**Comment by kaigai** [comment]
Right now, it is sufficient to support.

**Comment by Jiwangreal** [comment]
> 

OK。But we can not find any cuFile code body, only have code declaration？where is it?

Could you list some code body, eg: pgstrom_init_cufile();

**Comment by Jiwangreal** [comment]
> Please check GDS requirement. It needs RHEL8.3 or later, and Mellanox driver built with GDS enabled. The `nvme_strom` is an independent module to run GPU-Direct SQL on RHEL7.
> 
> > another problem is the following sql whether indicate using GPU director SQL?
> 
> Can you see the following log message (that is on my server) on starup? If heterodb_extra module detects local nvme devices correctly, it shall show the closest GPU to be used for GPU-Direct SQL.
> 
> ```
> 2022-01-11 17:24:48.907 JST [3754456] LOG:  PG-Strom: GPU0 NVIDIA A100-PCIE-40GB (108 SMs; 1410MHz, L2 40960kB), RAM 39.59GB (5120bits, 1.16GHz), PCI-E Bar1 64GB, CC 8.0
> 2022-01-11 17:24:48.912 JST [3754456] LOG:  - nvme4n1 (Corsair MP600 CORE; 0000:c6:00.0) --> GPU0
> 2022-01-11 17:24:48.912 JST [3754456] LOG:  - nvme0n1 (INTEL SSDPF2KX038TZ; 0000:c1:00.0) --> GPU0
> 2022-01-11 17:24:48.912 JST [3754456] LOG:  - nvme2n1 (INTEL SSDPF2KX038TZ; 0000:c3:00.0) --> GPU0
> 2022-01-11 17:24:48.912 JST [3754456] LOG:  - nvme3n1 (INTEL SSDPF2KX038TZ; 0000:c4:00.0) --> GPU0
> 2022-01-11 17:24:48.912 JST [3754456] LOG:  - nvme1n1 (INTEL SSDPF2KX038TZ; 0000:c2:00.0) --> GPU0
> ```

OK，I got it, thanks.

**Comment by H-xudong** [comment]
> Please check GDS requirement. It needs RHEL8.3 or later, and Mellanox driver built with GDS enabled. The `nvme_strom` is an independent module to run GPU-Direct SQL on RHEL7.
> 
> > another problem is the following sql whether indicate using GPU director SQL?
> 
> Can you see the following log message (that is on my server) on starup? If heterodb_extra module detects local nvme devices correctly, it shall show the closest GPU to be used for GPU-Direct SQL.
> 
> ```
> 2022-01-11 17:24:48.907 JST [3754456] LOG:  PG-Strom: GPU0 NVIDIA A100-PCIE-40GB (108 SMs; 1410MHz, L2 40960kB), RAM 39.59GB (5120bits, 1.16GHz), PCI-E Bar1 64GB, CC 8.0
> 2022-01-11 17:24:48.912 JST [3754456] LOG:  - nvme4n1 (Corsair MP600 CORE; 0000:c6:00.0) --> GPU0
> 2022-01-11 17:24:48.912 JST [3754456] LOG:  - nvme0n1 (INTEL SSDPF2KX038TZ; 0000:c1:00.0) --> GPU0
> 2022-01-11 17:24:48.912 JST [3754456] LOG:  - nvme2n1 (INTEL SSDPF2KX038TZ; 0000:c3:00.0) --> GPU0
> 2022-01-11 17:24:48.912 JST [3754456] LOG:  - nvme3n1 (INTEL SSDPF2KX038TZ; 0000:c4:00.0) --> GPU0
> 2022-01-11 17:24:48.912 JST [3754456] LOG:  - nvme1n1 (INTEL SSDPF2KX038TZ; 0000:c2:00.0) --> GPU0
> ```

hi, my OS version is Centos7, and i installed nvme-strom module according to offical documents, everyting seems ok, even i restarted pg can see log message like the above you list, but the question is that:
postgres=# set pg_strom.
pg_strom.cpu_fallback
pg_strom.debug_cuda_enable_coredump_on_exception
pg_strom.debug_jit_compile_options
pg_strom.enable_brin
pg_strom.enabled
pg_strom.enable_gpucache
pg_strom.enable_gpugistindex
pg_strom.enable_gpuhashjoin
pg_strom.enable_gpunestloop
pg_strom.enable_gpupreagg
pg_strom.enable_gpuscan
pg_strom.enable_partitionwise_gpujoin
pg_strom.enable_partitionwise_gpupreagg
pg_strom.gpudirect_enabled
pg_strom.gpudirect_threshold
pg_strom.gpu_dma_cost
pg_strom.gpu_operator_cost
pg_strom.gpupreagg_reduction_threshold
pg_strom.gpu_setup_cost
pg_strom.hll_registers_bits
pg_strom.max_async_tasks
pg_strom.pullup_outer_join
pg_strom.pullup_outer_scan
pg_strom.reuse_cuda_context

when i want to set "pg_strom.nvme_strom_enabled" and "pg_strom.nvme_strom_threshold", i couldn't find them, and when i execute SQL, i find the GDS  Function not triggered ！ thanks for your reply!

**Comment by kaigai** [comment]
Sorry, these parameters were renamed, when PG-Strom got support of GPU-Direct Storage by NVIDIA, not only HeteroDB's nvme_strom kmod.
`pg_strom.nvme_strom_enabled` --> `pg_strom.gpudirect_enabled`
`pg_strom.nvme_strom_threshold` --> `pg_strom.gpudirect_threshold`

**Comment by H-xudong** [comment]
> Sorry, these parameters were renamed, when PG-Strom got support of GPU-Direct Storage by NVIDIA, not only HeteroDB's nvme_strom kmod. `pg_strom.nvme_strom_enabled` --> `pg_strom.gpudirect_enabled` `pg_strom.nvme_strom_threshold` --> `pg_strom.gpudirect_threshold`

sir,  The parameters you say i have set up, my query plan like this:
postgres=# explain (analyze,verbose,timing,costs,buffers) select * from test4 where c2 = c4;
                                                                QUERY PLAN                         
                                       
---------------------------------------------------------------------------------------------------
---------------------------------------
 Custom Scan (GpuScan) on public.test4  (cost=10934.49..124014.67 rows=50055 width=68) (actual time
=2145.609..2157.370 rows=1018 loops=1)
   Output: id, c1, c2, c3, c4, c5, c6, info, crt_time
   GPU Projection: test4.id, test4.c1, test4.c2, test4.c3, test4.c4, test4.c5, test4.c6, test4.info
, test4.crt_time
   GPU Filter: (test4.c2 = test4.c4)
   Rows Removed by GPU Filter: 998982
   GPU Preference: None
   Kernel Source: /home/wangji/pg14installdir/data/pgsql_tmp/pgsql_tmp_strom_13938.0.gpu
   Kernel Binary: /home/wangji/pg14installdir/data/pgsql_tmp/pgsql_tmp_strom_13938.1.ptx
   Buffers: shared hit=1 read=117776
 Planning:
   Buffers: shared hit=69 read=1
 Planning Time: 1.456 ms
 Execution Time: 2213.637 ms
(13 rows)

-----------------------------
This is different from the official documents, miss  ' NVMe-Strom: enabled' words in query plan. so i want to  be verified whether the gds function is be triggered, i have used gdb to track the source code ,but i found in function 'ExecInitGpuScan', 
---------
if ((pds_src->kds.format == KDS_FORMAT_BLOCK &&
		 pds_src->nblocks_uncached > 0) ||
		(pds_src->kds.format == KDS_FORMAT_ARROW &&
		 pds_src->iovec != NULL))
		gscan->with_nvme_strom = true;
-------------
this if conditional sentence is not real, the result is gscan->with_nvme_strom = false; and  
----------
if (gscan->with_nvme_strom)
	{
		gpuMemCopyFromSSD(m_kds_src, pds_src);
	}
------------
led to the pguMemCopyFromSSD not be called

Thank you for answering my questions, Hope for your reply, thanks!

**Comment by kaigai** [comment]
Is table size too small?

The `pg_strom.gpudirect_threshold` is consigured according to the system memory size.
It looks the `test4` table has just 70 blocks (8kB * 70 = 560kB).

**Comment by H-xudong** [comment]
> Is table size too small?
> 
> The `pg_strom.gpudirect_threshold` is consigured according to the system memory size. It looks the `test4` table has just 70 blocks (8kB * 70 = 560kB).

sir, last night i create one 100million size of table , successfully, i used the function of GDS, But strangely, I wanted to test it again this morning and found that it reported an error, 
`ERROR:  failed on gpuMemAllocIOMap: CUDA_ERROR_MAP_FAILED - mapping of buffer object failed
DETAIL:  GPU kernel location: gpupreagg.c:5804 [gpupreagg_process_reduction_task]`

Then I changed the size of the table and created a small table of 30million, try it again, and i successful use the  GDS, Through comparative experiments, it is found that GDS can  improve performance very well.
 postgres=# explain (analyze,verbose,timing,costs,buffers) select count(*) from test6;
                                                                QUERY PLAN                                                       
          
---------------------------------------------------------------------------------------------------------------------------------
----------
 Aggregate  (cost=256155.92..256155.93 rows=1 width=8) (actual time=1540.294..1540.298 rows=1 loops=1)
   Output: pgstrom.sum((pgstrom.nrows()))
   Buffers: shared hit=370383
   ->  Custom Scan (GpuPreAgg) on public.test6  (cost=256155.91..256155.92 rows=1 width=8) (actual time=1540.269..1540.277 rows=1
 loops=1)
         Output: (pgstrom.nrows())
         GPU Output: (pgstrom.nrows())
         GPU Setup: '1'::bigint
         Reduction: NoGroup
         Outer Scan: public.test6  (cost=4000.00..251468.40 rows=30000052 width=0) (actual time=265.846..1400.430 rows=30000000 l
oops=1)
         GPU Preference: GPU0 (Tesla T4)
         GPUDirect SQL: enabled
         Kernel Source: /home/wangji/pg14installdir/data/pgsql_tmp/pgsql_tmp_strom_95949.14.gpu
         Kernel Binary: /home/wangji/pg14installdir/data/pgsql_tmp/pgsql_tmp_strom_95949.15.ptx
         Buffers: shared hit=370383
 Planning Time: 0.281 ms
 Execution Time: 1702.870 ms
(16 rows)

My question is, what is the trigger condition of GDS? The table is too large or too small all can not to trigger it, i am a new PGer,

Looking forward to your reply!

**Comment by kaigai** [comment]
IIRC, Tesla T4 does not have enough amount of PCI-E Bar1 address space (just 256MB).
(It should be disabled by the system, but does not detect it...)

Please use any of Tesla P40, P100, V100, A40 (not confirmed), or A100.
They have enough amount of PCI-E Bar1 memory to map its device memory on physical address space of the host system.

https://github.com/heterodb/pg-strom/wiki/100:-FAQ#what-gpu-supports-gpu-direct-sql

For example, my A100 system shows...
```
$ nvidia-smi -q | less
==============NVSMI LOG==============

Timestamp                                 : Fri Jul  1 12:05:53 2022
Driver Version                            : 515.43.04
CUDA Version                              : 11.7

Attached GPUs                             : 1
GPU 00000000:41:00.0
    Product Name                          : NVIDIA A100-PCIE-40GB
    Product Brand                         : NVIDIA
    Product Architecture                  : Ampere
          :
    FB Memory Usage
        Total                             : 40960 MiB
        Reserved                          : 569 MiB
        Used                              : 0 MiB
        Free                              : 40390 MiB
    BAR1 Memory Usage
        Total                             : 65536 MiB
        Used                              : 1 MiB
        Free                              : 65535 MiB
          :
```
It means BAR1 area has enough coverage to map entire device memory, but Tesla T4 does not.

Sorry, it is a hardware restriction by NVIDIA.

**Comment by H-xudong** [comment]
> 
thanks, i get it

**Comment by H-xudong** [comment]
sir, i have replaced my graphics card , use Tesla V100. There are still some problems, when i execute
`modprobe nvme_strom``pg_ctl restart` yes ,the restart pg log message is ok, `psql -h localhost` everything goes well
but when i `explain(...)select....;` problems occurred!
sometimes, QUEERY PLAN said `GPU Preference: None`  and sometimes QUEERY PLAN said `GPU Preference: GPU0 (Tesla V100-PCIE-32GB)` I know the later is normal

TO solve the problem, i  wrote a script`for ((i=1;i>0;)) ; do dmesg | grep -i nvme;sleep 1; done` i found when i execte `pg_ctl restart` the dmesg said `[ 1381.510772] nvme-strom: GPU-UUID: [GPU-d5f5a73a-a134-562e-76b7-acf66ae26e08] is not licensed
[ 1381.510772] nvme-strom: GPU-UUID: [GPU-d5f5a73a-a134-562e-76b7-acf66ae26e08] is not licensed` 
so what should i do? thanks, Looking forward to your reply!

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
