### ISSUE TITLE
Set gpu_operator_cost=0, but pg still choose the cpu hash join

### ISSUE THREAD

**Issue by Cerdore** [heterodb/pg-strom#544]
Hi, @kaigai !

I want to force the gpu join with pg-strom to test my implementation. I set gpu_operator_cost = 0, but PG still choose the cpu hash join when performing a two-table (arrow-fdw) join.
 
![image](https://user-images.githubusercontent.com/24353799/141128448-03f3a28b-9438-4d1d-9aba-a20bbce2d62d.png)

It's not clear to me why there is no option to operate on the GPU when cost = 0. Do you have any suggestions for **forcing the use of gpu join**?

Thank you in advance!

Best,
Cerdore

**Comment by kaigai** [comment]
Likely, it is considered that the inner-side of GpuJoin is too large to load GPU device memory.
(But Apache Arrow file size is 762MB, estimation might be too conservative??)

Please try to join a large table with small tables.

**Comment by Cerdore** [comment]
Thank you for your reply. It's rather late now, so I'm bothering you.

I would like to know which part of the estimated code determines whether it can be loaded into gpu. is it ExecGpuJoinEstimateDSM? But I don't understand that this can determine whether it can be loaded into gpu...

Just take a good rest and get back to me in your free time!

**Comment by Cerdore** [comment]
I found it in cost_gpujoin(). Thank you!

**Comment by Cerdore** [comment]
By the way, when I commented the bottom code in cost_gpujoin(), performing a two-table (arrow-fdw) join occurs error.
The tables are ar10 and ar11 which I post on this issue begin.

![image](https://user-images.githubusercontent.com/24353799/141684798-8d6332c5-d619-4c19-bfc9-d87c03b3f155.png)
I think this part could be optimized a bit more.

**Comment by kaigai** [comment]
It looks to me your /dev/shm (tmpfs) size is small, or some garbages comsume the ram disk.

**Comment by Cerdore** [comment]
I feel I have enough space. 

I execute `watch -n 0.2 df -h` during joining.

![image](https://user-images.githubusercontent.com/24353799/141688425-fbec7f8c-e8d2-4eaf-9946-31d219f47f3c.png)

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
