### ISSUE TITLE
Tablespace can not use nvme_optimal_gpu

### ISSUE THREAD

**Issue by lu-jialin** [heterodb/pg-strom#545]
Hi, the problem is about tablespace can not use nvme_optimal_gpu in **pg-strom 2.3**.

The postgresql.conf contains:

    shared_preload_libraries = '$libdir/pg_strom'
    max_worker_processes = 100 
    shared_buffers = 10GB
    work_mem = 1GB 
    max_parallel_workers=32
    max_parallel_workers_per_gather = 0

postgresql log shows:

     NVRTC 11.0 is successfully loaded.
     PG-Strom version 2.3 built for PostgreSQL 11
     PG-Strom: GPU0 Tesla P100-PCIE-16GB (3584 CUDA cores; 1328MHz, L2 4096kB), RAM 15.90GB (4096bits, 698MHz), CC 6.0 
       -  PCIe[0000:85]
           -  PCIe(0000:85:00.0)
               -  PCIe(0000:86:00.0) nvme0 (Dell Express Flash PM1725b 1.6TB AIC)
       -  PCIe[0000:d7]
           -  PCIe(0000:d7:00.0)
               -  PCIe(0000:d8:00.0) GPU0 (Tesla P100-PCIE-16GB)
       -  PCIe[0000:ae]
           -  PCIe(0000:ae:00.0)
               -  PCIe(0000:af:00.0) nvme1 (SSDPEDKE040T7L)
     GPU<->SSD Distance Matrix
                GPU0>>
         nvme1  (   6)  
         nvme0  (   6)  
     PG-Strom: commercial license is expired

Stack trace of planner  shows that in ```GetOptimalGpuForTablespace()```:

	entry = (vfs_nvme_status *) hash_search(vfs_nvme_htable,
											&tablespace_oid,
											HASH_ENTER,
											&found);

This statement always get a entry that ```entry->nvme_optimal_gpu = -1``` while the tablespace location is on a nvme device.

Since it was a block got from hash table, it is too hard to find where it was set. How can I make ```nvme_optimal_gpu``` enable?

Thanks.

**Comment by kaigai** [comment]
PG-Strom v2.3 is not latest. (I don't want to investigate this older version any more...)

Please use v3.2 with the latest heterodb-extra module.

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
