### ISSUE TITLE
Official Docker image for pg-storm

### ISSUE THREAD

**Issue by nyurik** [heterodb/pg-strom#548]
Would it be possible to add a Dockerfile(s) to this repository to demonstrate how to install pg-strom into an official Postgres docker images?  Both [PostgreSQL](https://github.com/docker-library/postgres) team and [PostGIS](https://github.com/postgis/docker-postgis) team maintain official docker images for different versions (the PostGIS docker images extend Postgres ones).  This will also simplify any automation testing and help new contributors get started faster -- having a docker dev environment will help people start coding much faster.

Lastly, @knowever  posted https://github.com/heterodb/pg-strom/issues/454#issuecomment-583848978 about building their docker image, so that might be used as a base?

(Thanks for an amazing and long overdue project!!!)

**Comment by murphye** [comment]
I have opened a Pull Request for this. https://github.com/heterodb/pg-strom/pull/575

It requires a Linux host. Windows + WSL 2 is not possible.

**Comment by murphye** [comment]
@nyurik If you get a chance to try it, please let me know how it works for you!

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
