### ISSUE TITLE
[question] gpudirect in google compute engine ?

### ISSUE THREAD

**Issue by changchichung** [heterodb/pg-strom#550]
May I run an instance with gpu support in google compute engine to use pg-strom ?
Does it support the gpudirect function ??

**Comment by kaigai** [comment]
Not tested yet.
Indeed, it allows to attach NVME device to GPU instances, but not as a persistent storage....

**Comment by changchichung** [comment]
so I guess that AWS has the same issue ?
is there any other way to test pg-strom before purchasing a GPU Server ?

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
