### ISSUE TITLE
pg2arrow doesn't build properly due to missing flag

### ISSUE THREAD

**Issue by davidgoldelocks** [heterodb/pg-strom#553]
I am attempting to build the pg2arrow tool independently.

Looking at the source, it depends on the `__PG2ARROW__` flag. However, the Makefile is no longer setting that. Looks like it was lost as part of this commit: https://github.com/heterodb/pg-strom/commit/3917ddec306d21625c78dbaa929b3b239a3313b4

Manually adding `-D__PG2ARROW__=1` seems to work.

As a side note, it would be nice to document that the libpq env vars (such as PGPASSWORD) are supported. It would also be nice to be able to feed in a full `postgres://` connection url instead of setting individual components.

**Comment by kaigai** [comment]
Thanks for your report. Exactly, it was my oversight.
fccc5ff0e1efcdf821ec636767b20e3f5a4be98b fixed this issue.

> As a side note, it would be nice to document that the libpq env vars (such as PGPASSWORD) are supported. It would also be nice to be able to feed in a full postgres:// connection url instead of setting individual components.

Thanks for the requirement. I'll do this.

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
