### ISSUE TITLE
[feature] Radeon Open Compute support using HIP

### ISSUE THREAD

**Issue by erkinalp** [heterodb/pg-strom#555]
Short description: HIP is the AMD equivalent to CUDA.
Difficulty: projected to be easy using mechanical code translation using hipifying tools, needs testing

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.

**Comment by erkinalp** [comment]
See #588
