### ISSUE TITLE
Quesion about compling or linking

### ISSUE THREAD

**Issue by Cerdore** [heterodb/pg-strom#558]
Hello, I have a question about your code.

I found that both _codegen.c_ and _aggfunc.c_ call the function `pg_numeric_from_varlena` declared as `PUBLIC_FUNCTION`, but I didn't find that you created the link to the source file _cuda_numericu.cu_ containing the function when you created the dynamic library. I think by the rules of the makefile, the cu file, c file are compiled separately and no link is created.

I'm curious how they _codegen.c_ and _aggfunc.c_ find the function `pg_numeric_from_varlena` of _cuda_numericu.cu_. Could you please explain?

Looking forward to your reply

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
