### ISSUE TITLE
Trying to Using cuda-gdb attach cuda driver API, but Access Failure

### ISSUE THREAD

**Issue by H-xudong** [heterodb/pg-strom#562]
kai, I have modified the Makefile about pg-strom by adding -g -G, Compiled successful, and i have created extension pg-strom; 
 when i used cuda-gdb follow the postgres process , set breakpoints in `cuMemcpyHtoDAsync`  `cuMemPrefetchAsync` etc ,i found  use `s` can't step in the function the API.
Hoping for your reply, thanks

**Comment by kaigai** [comment]
Use `make PGSTROM_DEBUG=1` and `SET pg_strom.debug_jit_compile_options = on` prior to SQL execution.

**Comment by xu-kaichun** [comment]
Sir kaigai:
I did as you said.Unfortunately,it did not work.
Did I miss something?

[xukc@host12 ~]$ cuda-gdb -p 23330
NVIDIA (R) CUDA Debugger
11.5 release
Portions Copyright (C) 2007-2021 NVIDIA Corporation
GNU gdb (GDB) 10.1

Attaching to process 23330

0x00007f5f5b6520c3 in __epoll_wait_nocancel () from /lib64/libc.so.6
[New Thread 0x7f5f54cde600 (LWP 23561)]
[Thread 0x7f5f54cde600 (LWP 23561) exited]
Timed out waiting for the CUDA API to initialize.
(cuda-gdb) b kern_gpuscan_main_block
Function "kern_gpuscan_main_block" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (kern_gpuscan_main_block) pending.
(cuda-gdb) c
Continuing.
[New Thread 0x7f209d05c700 (LWP 23632)]
[New Thread 0x7f2097fff700 (LWP 23633)]

Thread 1 "postgres" received signal SIGUSR1, User defined signal 1.
0x00007f5f5c03dee0 in __open_nocancel () from /lib64/libpthread.so.0
(cuda-gdb) c
Continuing.

Thread 3 "cuda-EvtHandlr" received signal SIGUSR1, User defined signal 1.
[Switching to Thread 0x7f209d05c700 (LWP 23632)]
0x00007f5f5b646ddd in poll () from /lib64/libc.so.6
(cuda-gdb) c
Continuing.
[New Thread 0x7f20977fe700 (LWP 23693)]
[New Thread 0x7f2096ffd700 (LWP 23694)]
[New Thread 0x7f2091fff700 (LWP 23695)]
[New Thread 0x7f20917fe700 (LWP 23696)]
[New Thread 0x7f2090ffd700 (LWP 23697)]
[Thread 0x7f2090ffd700 (LWP 23697) exited]
[Thread 0x7f20917fe700 (LWP 23696) exited]
[Thread 0x7f2091fff700 (LWP 23695) exited]
[Thread 0x7f2096ffd700 (LWP 23694) exited]
[Thread 0x7f20977fe700 (LWP 23693) exited]
[Thread 0x7f2097fff700 (LWP 23633) exited]

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
