### ISSUE TITLE
fast_ssd_mode of NVME_STROM did not work

### ISSUE THREAD

**Issue by xu-kaichun** [heterodb/pg-strom#563]
こんにちは
I have changed the value of fast_ssd_mode.but program flow dosen't goes to branch gpuMemCopyFromSSD but cuMemcpyHtoDAsync.
Looking forward to your answer。

---

[root@host12 parameters]# cat /sys/module/nvme_strom/parameters/fast_ssd_mode 
1

---
step in __gpuscan_process_task by gdb
2482            if (gscan->with_nvme_strom)
(gdb) 
2486            else if (pds_src->kds.format == KDS_FORMAT_BLOCK)
(gdb) 
2488                    rc = cuMemcpyHtoDAsync(m_kds_src,
(gdb)

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
