### ISSUE TITLE
Migrate arrow_fdw to Table Access Method Interface and levirage Arrow Dataset API 

### ISSUE THREAD

**Issue by igor-suhorukov** [heterodb/pg-strom#566]
More tight PostgreSQL new API integration required to improve data access efficiency.  [Table Access Method Interface](https://www.postgresql.org/docs/current/tableam.html) looks like right way for it. It also allow to use indexed and other PG features on top of Arrow based table.
Additional usage of Arrow Dataset API allow map ARROW_IPC, PARQUET, ORC, CSV data scanner as part of new foundation for data processing in PostgreSQL for columnar data source on top of Apache Arrow

**Comment by kaigai** [comment]
Right now, it is not fun for me. Thanks for your idea.
