### ISSUE TITLE
Want detailed error information in arrow_fdw.

### ISSUE THREAD

**Issue by sakaik** [heterodb/pg-strom#576]
When using arrow_fdw to CREATE FOREIGN SCHEMA, we couldn't know where the error occurred. It's more useful to display it.

i.g)
```
=# CREATE FOREIGN TABLE arrow_adsb2 (
(#    c01    text,
(#    c02    varchar(10),
(#    c03    bigint,
(#    c04    text
(# ) SERVER arrow_fdw OPTIONS (file '/home/data/my_arrow_file.arrow');

ERROR:  arrow file '/home/arrow_data/flight20221125.arrow' on behalf of the foreign table 'arrow_adsb2' has incompatible schema definition
```

If the error message includes " in c02 varchar(10)", I think it a very kind message.

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
