### ISSUE TITLE
ERROR: Bug? unexpected expression: {FUNCEXPR :funcid 20597 :funcresulttype

### ISSUE THREAD

**Issue by shaunstoltz** [heterodb/pg-strom#582]
When executing a query as below with and avg in it, get this error:

postgis=# SELECT fxpair, avg(c) FROM fxmf GROUP BY fxpair;
ERROR: Bug? unexpected expression: {FUNCEXPR :funcid 20597 :funcresulttype 1022 :funcretset false :funcvariadic false :funcformat 0 :funccollid 0 :inputcollid 0 :args ({FUNCEXPR :funcid 20594 :funcresulttype 20 :funcretset false :funcvariadic false :funcformat 0 :funccollid 0 :inputcollid 0 :args ({NULLTEST :arg {VAR :varno 1 :varattno 6 :vartype 701 :vartypmod -1 :varcollid 0 :varlevelsup 0 :varnosyn 1 :varattnosyn 6 :location 19} :nulltesttype 1 :argisrow false :location 0}) :location -1} {FUNCEXPR :funcid 20629 :funcresulttype 701 :funcretset false :funcvariadic false :funcformat 0 :funccollid 0 :inputcollid 0 :args ({VAR :varno 1 :varattno 6 :vartype 701 :vartypmod -1 :varcollid 0 :varlevelsup 0 :varnosyn 1 :varattnosyn 6 :location 19}) :location -1}) :location -1}
CONTEXT: while executing command on 192.168.3.35:5434

Table is:
CREATE TABLE fxmf (
fxpair text,
numdate bigint,
o float,
h float,
l float,
c float,
v int,
PRIMARY KEY (fxpair, numdate)
);

SELECT create_distributed_table('fxmf', 'fxpair');

postgis=# SELECT * FROM citus_version();
citus_version
Citus 11.2.0 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4), 64-bit
(1 row)

postgis=# SELECT version();
version
PostgreSQL 15.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-16), 64-bit
(1 row)

**Comment by PenguinLQ** [comment]
I'm encountering the same error with avg when trying to run Query1 of tpc-h benchmark.
Postgresql version is 13 and pg-strom version is 3.4

tpch2-10=# select
tpch2-10-#     l_returnflag,
tpch2-10-#     l_linestatus,
tpch2-10-#     sum(l_quantity) as sum_qty,
tpch2-10-#     sum(l_extendedprice) as sum_base_price,
tpch2-10-#     sum(l_extendedprice * (1 - l_discount)) as sum_disc_price,
tpch2-10-#     sum(l_extendedprice * (1 - l_discount) * (1 + l_tax)) as sum_charge,
tpch2-10-#     avg(l_quantity) as avg_qty,
tpch2-10-#     avg(l_extendedprice) as avg_price,
tpch2-10-#     avg(l_discount) as avg_disc,
tpch2-10-#     count(*) as count_order
tpch2-10-# from
tpch2-10-#     lineitem
tpch2-10-# where
tpch2-10-#     l_shipdate <= date '1998-12-01' - interval '78' day
tpch2-10-# group by
tpch2-10-#     l_returnflag,
tpch2-10-#     l_linestatus
tpch2-10-# order by
tpch2-10-#     l_returnflag,
tpch2-10-#     l_linestatus;
ERROR:  Bug? unexpected expression: {FUNCEXPR :funcid 17543 :funcresulttype 1022 :funcretset false :funcvariadic false :funcformat 0 :funccollid 0 :inputcollid 0 :args ({FUNCEXPR :funcid 17540 :funcresulttype 20 :funcretset false :funcvariadic false :funcformat 0 :funccollid 0 :inputcollid 0 :args ({NULLTEST :arg {VAR :varno 1 :varattno 5 :vartype 1700 :vartypmod 983046 :varcollid 0 :varlevelsup 0 :varnosyn 1 :varattnosyn 5 :location 263} :nulltesttype 1 :argisrow false :location 0}) :location -1} {FUNCEXPR :funcid 17575 :funcresulttype 701 :funcretset false :funcvariadic false :funcformat 0 :funccollid 0 :inputcollid 0 :args ({FUNCEXPR :funcid 1746 :funcresulttype 701 :funcretset false :funcvariadic false :funcformat 1 :funccollid 0 :inputcollid 0 :args ({VAR :varno 1 :varattno 5 :vartype 1700 :vartypmod 983046 :varcollid 0 :varlevelsup 0 :varnosyn 1 :varattnosyn 5 :location 263}) :location -1}) :location -1}) :location -1}



tpch2-10=# select * from pg_proc where oid=17543;
  oid  | proname | pronamespace | proowner | prolang | procost | prorows | provariadic | prosupport | prokind | prosecdef | proleakproof | proisstrict | proretset | provolatil
e | proparallel | pronargs | pronargdefaults | prorettype | proargtypes | proallargtypes | proargmodes | proargnames | proargdefaults | protrftypes |           prosrc
  |      probin      | proconfig | proacl
-------+---------+--------------+----------+---------+---------+---------+-------------+------------+---------+-----------+--------------+-------------+-----------+-----------
--+-------------+----------+-----------------+------------+-------------+----------------+-------------+-------------+----------------+-------------+--------------------------
--+------------------+-----------+--------
 17543 | pavg    |        17504 |       10 |      13 |       1 |       0 |           0 | -          | f       | f         | f            | t           | f         | v
  | s           |        2 |               0 |       1022 | 20 701      |                |             |             |                |             | pgstrom_partial_avg_float
8 | $libdir/pg_strom |           |
(1 row)

Seems  like pavg is not well supported by pg-strom?

**Comment by matrixji** [comment]
I got the same error with the latest master code + Pg15.

**Comment by H-xudong** [comment]
I got the same error +1

**Comment by matrixji** [comment]
INFO:
I use `sum(x)/count(x)` instead of `avg(x)`, to accomplish some SQLs in TPC-H test

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
