### ISSUE TITLE
PostgreSQL 15.2 server process was terminated by signal 6: Aborted

### ISSUE THREAD

**Issue by MattiL** [heterodb/pg-strom#583]
When executing an OLAP query, PostgreSQL 15.2 server crashed with the log line below.
pg_strom extension was created but no NVIDIA GPU was installed on the virtual machine that was running Red Hat Enterprise Linux 9 and PostgreSQL 15.2.

2023-03-14 15:13:38.761 EET [1921261] LOG:  starting PostgreSQL 15.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 11.3.1 20220421 (Red Hat 11.3.1-2), 64-bit
2023-03-14 15:13:38.762 EET [1921261] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-03-14 15:13:38.762 EET [1921261] LOG:  listening on IPv6 address "::", port 5432
2023-03-14 15:13:38.785 EET [1921261] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-03-14 15:13:38.810 EET [1921261] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-03-14 15:13:38.840 EET [1921268] LOG:  database system was shut down at 2023-03-14 15:13:38 EET
2023-03-14 15:13:38.842 EET [1921269] LOG:  CUDA Program Builder-1 with NVRTC version 12.1
2023-03-14 15:13:38.843 EET [1921270] LOG:  CUDA Program Builder-0 with NVRTC version 12.1
2023-03-14 15:13:38.876 EET [1921261] LOG:  database system is ready to accept connections
2023-03-14 15:13:50.651 EET [1921261] LOG:  server process (PID 1921300) was terminated by signal 6: Keskeytetty

**Comment by MattiL** [comment]
[root@rhel9 ~]# systemctl status -l postgresql-15
● postgresql-15.service - PostgreSQL 15 database server
     Loaded: loaded (/usr/lib/systemd/system/postgresql-15.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/postgresql-15.service.d
             └─pg_strom.conf
     Active: active (running) since Tue 2023-03-14 15:13:39 EET; 32min ago
       Docs: https://www.postgresql.org/docs/15/static/
    Process: 1921256 ExecStartPre=/usr/pgsql-15/bin/postgresql-15-check-db-dir ${PGDATA} (code=exited, status=0/SUCCESS)
   Main PID: 1921261 (postmaster)
      Tasks: 9 (limit: 48114)
     Memory: 798.5M
        CPU: 1.308s
     CGroup: /system.slice/postgresql-15.service
             ├─1921261 /usr/pgsql-15/bin/postmaster -D /var/lib/pgsql/15/data/
             ├─1921265 "postgres: logger "
             ├─1924117 "postgres: checkpointer "
             ├─1924118 "postgres: background writer "
             ├─1924141 "postgres: walwriter "
             ├─1924142 "postgres: autovacuum launcher "
             ├─1924143 "postgres: PG-Strom Program Builder-1 "
             ├─1924144 "postgres: PG-Strom Program Builder-0 "
             └─1924145 "postgres: logical replication launcher "

maalis 14 15:13:38 rhel9 systemd[1]: Stopped PostgreSQL 15 database server.
maalis 14 15:13:38 rhel9 systemd[1]: postgresql-15.service: Consumed 21.279s CPU time.
maalis 14 15:13:38 rhel9 systemd[1]: Starting PostgreSQL 15 database server...
maalis 14 15:13:38 rhel9 postmaster[1921261]: 2023-03-14 15:13:38.656 EET [1921261] LOG:  NVRTC 12.1 is successfully loaded.
maalis 14 15:13:38 rhel9 postmaster[1921261]: 2023-03-14 15:13:38.661 EET [1921261] LOG:  HeteroDB Extra module loaded [api_version=20221225,cufile=off,nvme_strom=off]
maalis 14 15:13:38 rhel9 postmaster[1921261]: 2023-03-14 15:13:38.661 EET [1921261] LOG:  PG-Strom version 3.4 built for PostgreSQL 15 (git: HEAD)
maalis 14 15:13:38 rhel9 postmaster[1921263]: gpuinfo:455  failed on nvmlInit: Driver Not Loaded
maalis 14 15:13:38 rhel9 postmaster[1921261]: 2023-03-14 15:13:38.761 EET [1921261] LOG:  redirecting log output to logging collector process
maalis 14 15:13:38 rhel9 postmaster[1921261]: 2023-03-14 15:13:38.761 EET [1921261] HINT:  Future log output will appear in directory "log".
maalis 14 15:13:39 rhel9 systemd[1]: Started PostgreSQL 15 database server.

**Comment by kaigai** [comment]
```
maalis 14 15:13:38 rhel9 postmaster[1921263]: gpuinfo:455 failed on nvmlInit: Driver Not Loaded
```

Is the CUDA driver installed successfully? Sub-program `gpuinfo` didn't load libnvml successfully.

And, we now under the active development of v5.x series.
Even though it is not available yet, it is not preferable to assign more hours to tackle v3.x series problems (it means more delay of v5.x series).

**Comment by MattiL** [comment]
No, I don't adhere to system requirements: I don't have a (CUDA-capable) GPU but the Red Hat Enterprise Linux version is right 9.1, kernel version is right 5.14.0-162.18.1.el9_1.x86_64, gcc is right 11.3.1, glibc is right 2.34 and clang is right 14.0.6.

**Comment by ytooyama** [comment]
CUDA-capable GPUs (Pascal or later) and CUDA are required as a minimum.
If you want to change the OS and CUDA version, you can install it with Ansible Playbook.

https://github.com/ytooyama/pgstrom-ansible

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
