### ISSUE TITLE
The aggregate function avg cannot be used

### ISSUE THREAD

**Issue by H-xudong** [heterodb/pg-strom#585]
postgres=# explain analyze select avg(age) from testz where grade > 40 group by grade;
ERROR:  Bug? unexpected expression: {FUNCEXPR :funcid 35404 :funcresulttype 1016 :funcretset false :funcvariadic false :funcformat 0 :funccollid 0 :inputcollid 0 :args ({FUNCEXPR :funcid 35402 :funcresulttype 20 :funcretset false :funcvariadic false :funcformat 0 :funccollid 0 :inputcollid 0 :args ({NULLTEST :arg {VAR :varno 1 :varattno 3 :vartype 23 :vartypmod -1 :varcollid 0 :varlevelsup 0 :varnosyn 1 :varattnosyn 3 :location 27} :nulltesttype 1 :argisrow false :location 0}) :location -1} {FUNCEXPR :funcid 35436 :funcresulttype 20 :funcretset false :funcvariadic false :funcformat 0 :funccollid 0 :inputcollid 0 :args ({FUNCEXPR :funcid 481 :funcresulttype 20 :funcretset false :funcvariadic false :funcformat 1 :funccollid 0 :inputcollid 0 :args ({VAR :varno 1 :varattno 3 :vartype 23 :vartypmod -1 :varcollid 0 :varlevelsup 0 :varnosyn 1 :varattnosyn 3 :location 27}) :location -1}) :location -1}) :location -1}

----------------------
Is it related to the pg-strom version or other reasons？

**Comment by kaigai** [comment]
Could you wait for the v5.0; that is currently under active development.
We want to focus on the new software rather than the end-less bug fixes on the complicated v3.x architecture.

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.

**Comment by ashwinstar** [comment]
> Could you wait for the v5.0; that is currently under active development.

Do we have approximate ETA for v5.0 GA?
