### ISSUE TITLE
Whether the aggregation functions are all completed on the GPU side？

### ISSUE THREAD

**Issue by H-xudong** [heterodb/pg-strom#586]
Excuse me, sir. Recently, I am testing the pg-strom AGG operator acceleration experiment. According to the introduction, Pre-agg only performs the group by operation, and the final operation of the aggregate function is completed on the CPU side. But I traced the code and found that the final result slot returned by the GPU side is the final result of the aggregation. The reference is as follows:

`PDS_fetch_tuple>>>KDS_fetch_tuple_slot`and **p *slot->tts_values** is the final result of sum

`postgres=# explain (analyze,verbose)select sum(age * grade) from testz;
                                                                QUERY PLAN                            
                                     
------------------------------------------------------------------------------------------------------
-------------------------------------
 Aggregate  (cost=165212.26..165212.27 rows=1 width=8) (actual time=2115.503..2115.507 rows=1 loops=1)
   Output: pgstrom.sum((pgstrom.psum(((age * grade))::bigint)))
   ->  Custom Scan (GpuPreAgg) on public.testz  (cost=165212.25..165212.26 rows=1 width=8) (actual tim
e=2115.472..2115.482 rows=1 loops=1)
         Output: (pgstrom.psum(((age * grade))::bigint))
         GPU Output: (pgstrom.psum(((age * grade))::bigint))
         GPU Setup: ((age * grade))::bigint
         Reduction: NoGroup
         Outer Scan: public.testz  (cost=4000.00..155837.24 rows=20000024 width=8) (actual time=333.46
6..1090.049 rows=20000000 loops=1)
         GPU Preference: GPU0 (Tesla V100-PCIE-32GB)
         GPUDirect SQL: enabled
         Kernel Source: /mnt/hxd_gds/pg_hxd_data/pgsql_tmp/pgsql_tmp_strom_3138072.30.gpu
         Kernel Binary: /mnt/hxd_gds/pg_hxd_data/pgsql_tmp/pgsql_tmp_strom_3138072.31.ptx
 Planning Time: 0.277 ms
 Execution Time: 2341.848 ms
(14 rows)`

sir,I want to confirm with you whether the AGG operator is all completed on the GPU side. What did the AGG operator at the top of the QUERY PLAN do on the CPU side? It feels like nothing has been done.
----------
pg version:14.4
pg-strom version:4.0

**Comment by kaigai** [comment]
No. As literal, GpuPreAgg runs partial aggregation on the GPU-side, then Agg node generates the final aggregation results.
(It shall not be changed on the upcoming v5.x)

This design well fits CPU-parallel query execution with GPU-acceleration.

**Comment by H-xudong** [comment]
> No. As literal, GpuPreAgg runs partial aggregation on the GPU-side, then Agg node generates the final aggregation results. (It shall not be changed on the upcoming v5.x)
> 
> This design well fits CPU-parallel query execution with GPU-acceleration.

What does partial aggregation mean? I test a SQL like this `select c4,sum(c4 * c5) from test3 group by c4 having c4 > 60;` i found **sum groupby and having** It seems to be all done in the GPU kernel function

**Comment by kaigai** [comment]
As you `EXPLAIN` result says, `GPU Output: (pgstrom.psum(((age * grade))::bigint))` is processed on the GPU by GpuPreAgg, then `pgstrom.sum((pgstrom.psum(((age * grade))::bigint)))` which takes result of the GPU output is processed on the CPU by Agg.
Even if Agg-node has Gather-node for CPU-parallel, this design is immutable.

**Comment by H-xudong** [comment]
> As you `EXPLAIN` result says, `GPU Output: (pgstrom.psum(((age * grade))::bigint))` is processed on the GPU by GpuPreAgg, then `pgstrom.sum((pgstrom.psum(((age * grade))::bigint)))` which takes result of the GPU output is processed on the CPU by Agg. Even if Agg-node has Gather-node for CPU-parallel, this design is immutable.

Dear author, I understand what you mean, but I want to know why the value returned by the AGG node from the customscan(preagg) function pointer is the sum value, not the pgstrom.psum value
`outerslot = fetch_input_tuple(aggstate);` p *outerslot->tts_values = 6
As far as I understand, pgstrom.psum outputs an intermediate result,like 
`postgres=# select pgstrom.psum(x1 * x2) from a1;
 psum 
------
    2
    4
(2 rows)

postgres=# select * from a1;
 x1 | x2 
----+----
  1 |  2
  2 |  2
(2 rows)`
thanks！

**Comment by kaigai** [comment]
In this query-plan, `psum()` returns the total sum of the input value, then `sum()` marges all the `psum()` results, however, this query-plan generates only 1 CustomScan(GpuPreAgg) instance because it uses no CPU parallel.

**Comment by kaigai** [comment]
Yes, right.

**Comment by H-xudong** [comment]
> Yes, right.
Thank you for bothering you so late!

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
