### ISSUE TITLE
[v5.0] パッケージ作成

### ISSUE THREAD

**Issue by kaigai** [heterodb/pg-strom#600]
- RPM Specファイルの作成
- RPM ホスティングサイトの選定
- Ubuntuパッケージの検討

**Comment by kaigai** [comment]
現状のSWDCでの配布は色々と辛すぎる。

Contributing to RPM Fusion
https://rpmfusion.org/Contributors

https://rpmfusion.org/Howto/NVIDIA

**Comment by ytooyama** [comment]
PostgreSQLコミュニティの方がspecファイルを作って触ってくれているようなので、例えばPostgreSQLのリポジトリーでパッケージ配布というのはどうでしょうか。

https://git.postgresql.org/gitweb/?p=pgrpms.git;a=commit;h=1c8fbe60bcd76cbee27ec7e0a8d6221622e393c9

**Comment by kaigai** [comment]
Non-freeのパッケージ配布がというのと、hotfixとか必要な時に、こちらではタイミングをコントロールできないのがですね…。

**Comment by kaigai** [comment]
`bd0fb53f5c2c8a082d226ed7709ac332a203833c` でパッケージは作成できるように。

```
$ make rpm PG_CONFIG=/usr/pgsql-15/bin/pg_config
```
