### ISSUE TITLE
(VTJ-JP)WARNING:  failed on stat('base/56061'): No such file or directory

### ISSUE THREAD

**Issue by sakaik** [heterodb/pg-strom#608]
## 事象概要
　デフォルト以外の場所のテーブルスペースに作成したテーブルへのアクセス時に以下のエラーが発生する。
　`WARNING:  failed on stat('base/56061'): No such file or directory` 
　このエラーは、当該テーブルへの1回目のアクセス時のみ発生しているように見える。

## 再現方法

- 新たなテーブルスペース用のフォルダを作成(shell)
```
mkdir /home/data
chown postgres:postgres /home/data
```

以下はPostgreSQL上での作業：
- 新たなテーブルスペースを利用したDBを作成。
- pg_strom有効化
```
CREATE TABLESPACE tbsp_test LOCATION '/home/data';
CREATE DATABASE db_test WITH TABLESPACE=tbsp_test;
\c db_test
CREATE EXTENSION pg_strom;
```

- テーブルとデータを作成
```
CREATE TABLE t (id int, val varchar(100));
INSERT INTO t 
  SELECT i, 'data'||pgstrom.random_int(1,0,100)
    FROM GENERATE_SERIES(1,100000) as i;
```

- クエリ実行と本件報告のエラーが発生
```
db_test=# SELECT * FROM t where id<100;
WARNING:  failed on stat('base/56061'): No such file or directory
```

- この '56061' のデータベースフォルダは
    - デフォルトの `/var/lib/pgsql/15/data/base/`下には存在せず
    - 今回作成したテーブルスペース `/home/data/PG_15_202209061` 下にのみ存在している

## target commit
　`df9fb675e49b7ffeeaeca6652cb766a049ea72d4`

**Comment by kaigai** [comment]
`31844063a91ea7dd56e2a536bf40db140e7a2d5f`

デフォルトのテーブルスペースを使用する場合、グローバル変数 `MyDatabaseTableSpace` の値を使用する必要が
あるのですが、`GetOptimalGpuForTablespace` の呼び出し元でテーブルスペースIDの補正を行っており、
デフォルトのテーブルスペースを使用すべしという判定にならなかったようです。

**Comment by sakaik** [comment]
`31844063a91ea7dd56e2a536bf40db140e7a2d5f` にて、エラーがでなくなったことを確認しました。
ありがとうございました！
