### ISSUE TITLE
SUM(<float4 column>) brings errors

### ISSUE THREAD

**Issue by 0-kaz** [heterodb/pg-strom#615]
コミット：4324e318d16e3637399ef07feac39c968c3f406d

```sql
SELECT a,SUM(f) FROM group_test_1 GROUP BY a;
ERROR:  Catalog curruption? partial function mismatch: s:psum(float4)
SELECT a,SUM(e) FROM group_test_1 GROUP BY a;
ERROR:  Catalog curruption? partial function mismatch: s:psum(float4)

```

**Comment by kaigai** [comment]
`d95639d0351cec72a26446588a7529aec4f94475` で修正しています。

gpu_preagg.c に記述したカタログの定義がおかしい（`psum(float4)`ではなく、float8で集計値を受け取る`psum(float8)`であるべきだった）のと、併せて、float2 -> float8 へのキャストがおかしかったのを直しました。
