### ISSUE TITLE
unrecognized path-node type

### ISSUE THREAD

**Issue by ma853529615** [heterodb/pg-strom#618]
Hi @kaigai . Thank you for your dedication to this wonderful project.
I met the the ERROR:  unrecognized path-node type: XXX when I execute the queries in the Join Order Benchmark which use the IMDB dataset. Sometimes it directly lead to the server close. Output:

> server closed the connection unexpectedly
>         This probably means the server terminated abnormally
>         before or while processing the request.
> The connection to the server was lost. Attempting reset: Failed.

I build the pg_strom 3.5 on the Postgresql 12.1. Other information:

> System: (Ubuntu 7.5.0-3ubuntu1~18.04
> CUDA：12.1

There are a large number of queries in the Join Order Benchmark cause that problem. Here are two examples:
Q0:
> SELECT COUNT(*) FROM title as t,
> kind_type as kt,
> info_type as it1,
> movie_info as mi1,
> cast_info as ci,
> role_type as rt,
> name as n,
> movie_keyword as mk,
> keyword as k,
> movie_companies as mc,
> company_type as ct,
> company_name as cn
> WHERE
> t.id = ci.movie_id
> AND t.id = mc.movie_id
> AND t.id = mi1.movie_id
> AND t.id = mk.movie_id
> AND mc.company_type_id = ct.id
> AND mc.company_id = cn.id
> AND k.id = mk.keyword_id
> AND mi1.info_type_id = it1.id
> AND t.kind_id = kt.id
> AND ci.person_id = n.id
> AND ci.role_id = rt.id
> AND (it1.id IN ('7'))
> AND (mi1.info in ('MET:','OFM:35 mm','PCS:Digital Intermediate','PFM:35 mm','PFM:Video','RAT:1.33 : 1','RAT:1.37 : 1'))
> AND (kt.kind in ('episode','movie','tv movie'))
> AND (rt.role in ('actor','actress'))
> AND (n.gender in ('f','m') OR n.gender IS NULL)
> AND (n.name_pcode_cf in ('A5362','J5252','R1632','R2632','W4525'))
> AND (t.production_year <= 2015)
> AND (t.production_year >= 1925)
> AND (cn.name in ('Fox Network','Independent Television (ITV)','Metro-Goldwyn-Mayer (MGM)','National Broadcasting Company (NBC)','Paramount Pictures','Shout! Factory','Sony Pictures Home Entertainment','Universal Pictures','Universal TV'))
> AND (ct.kind in ('distributors','production companies'))

Q13:

> SELECT COUNT(*)
> FROM title as t,
> movie_info as mi1,
> kind_type as kt,
> info_type as it1,
> info_type as it3,
> info_type as it4,
> movie_info_idx as mii1,
> movie_info_idx as mii2,
> movie_keyword as mk,
> keyword as k,
> aka_name as an,
> name as n,
> info_type as it5,
> person_info as pi1,
> cast_info as ci,
> role_type as rt
> WHERE
> t.id = mi1.movie_id
> AND t.id = ci.movie_id
> AND t.id = mii1.movie_id
> AND t.id = mii2.movie_id
> AND t.id = mk.movie_id
> AND mk.keyword_id = k.id
> AND mi1.info_type_id = it1.id
> AND mii1.info_type_id = it3.id
> AND mii2.info_type_id = it4.id
> AND t.kind_id = kt.id
> AND (kt.kind IN ('episode'))
> AND (t.production_year <= 1975)
> AND (t.production_year >= 1925)
> AND (mi1.info IN ('Mono'))
> AND (it1.id IN ('13','6','8'))
> AND it3.id = '100'
> AND it4.id = '101'
> AND (mii2.info ~ '^(?:[1-9]\d*|0)?(?:\.\d+)?$' AND mii2.info::float <= 7.0)
> AND (mii2.info ~ '^(?:[1-9]\d*|0)?(?:\.\d+)?$' AND 3.0 <= mii2.info::float)
> AND (mii1.info ~ '^(?:[1-9]\d*|0)?(?:\.\d+)?$' AND 0.0 <= mii1.info::float)
> AND (mii1.info ~ '^(?:[1-9]\d*|0)?(?:\.\d+)?$' AND mii1.info::float <= 10000.0)
> AND n.id = ci.person_id
> AND ci.person_id = pi1.person_id
> AND it5.id = pi1.info_type_id
> AND n.id = pi1.person_id
> AND n.id = an.person_id
> AND rt.id = ci.role_id
> AND (n.gender in ('m') OR n.gender IS NULL)
> AND (n.name_pcode_nf in ('A4163','B6563','D1316','F6521','F6523','F6524','J5216','J5262','P3616'))
> AND (ci.note IS NULL)
> AND (rt.role in ('actor'))
> AND (it5.id in ('32'))

**Comment by ma853529615** [comment]
There are the DDLs of imdb(aforementioned problem will show in these tables without any data):

> CREATE TABLE aka_name (
>     id integer NOT NULL PRIMARY KEY,
>     person_id integer NOT NULL,
>     name character varying,
>     imdb_index character varying(3),
>     name_pcode_cf character varying(11),
>     name_pcode_nf character varying(11),
>     surname_pcode character varying(11),
>     md5sum character varying(65)
> );
> 
> CREATE TABLE aka_title (
>     id integer NOT NULL PRIMARY KEY,
>     movie_id integer NOT NULL,
>     title character varying,
>     imdb_index character varying(4),
>     kind_id integer NOT NULL,
>     production_year integer,
>     phonetic_code character varying(5),
>     episode_of_id integer,
>     season_nr integer,
>     episode_nr integer,
>     note character varying(72),
>     md5sum character varying(32)
> );
> 
> CREATE TABLE cast_info (
>     id integer NOT NULL PRIMARY KEY,
>     person_id integer NOT NULL,
>     movie_id integer NOT NULL,
>     person_role_id integer,
>     note character varying,
>     nr_order integer,
>     role_id integer NOT NULL
> );
> 
> CREATE TABLE char_name (
>     id integer NOT NULL PRIMARY KEY,
>     name character varying NOT NULL,
>     imdb_index character varying(2),
>     imdb_id integer,
>     name_pcode_nf character varying(5),
>     surname_pcode character varying(5),
>     md5sum character varying(32)
> );
> 
> CREATE TABLE comp_cast_type (
>     id integer NOT NULL PRIMARY KEY,
>     kind character varying(32) NOT NULL
> );
> 
> CREATE TABLE company_name (
>     id integer NOT NULL PRIMARY KEY,
>     name character varying NOT NULL,
>     country_code character varying(6),
>     imdb_id integer,
>     name_pcode_nf character varying(5),
>     name_pcode_sf character varying(5),
>     md5sum character varying(32)
> );
> 
> CREATE TABLE company_type (
>     id integer NOT NULL PRIMARY KEY,
>     kind character varying(32)
> );
> 
> CREATE TABLE complete_cast (
>     id integer NOT NULL PRIMARY KEY,
>     movie_id integer,
>     subject_id integer NOT NULL,
>     status_id integer NOT NULL
> );
> 
> CREATE TABLE info_type (
>     id integer NOT NULL PRIMARY KEY,
>     info character varying(32) NOT NULL
> );
> 
> CREATE TABLE keyword (
>     id integer NOT NULL PRIMARY KEY,
>     keyword character varying NOT NULL,
>     phonetic_code character varying(5)
> );
> 
> CREATE TABLE kind_type (
>     id integer NOT NULL PRIMARY KEY,
>     kind character varying(15)
> );
> 
> CREATE TABLE link_type (
>     id integer NOT NULL PRIMARY KEY,
>     link character varying(32) NOT NULL
> );
> 
> CREATE TABLE movie_companies (
>     id integer NOT NULL PRIMARY KEY,
>     movie_id integer NOT NULL,
>     company_id integer NOT NULL,
>     company_type_id integer NOT NULL,
>     note character varying
> );
> 
> CREATE TABLE movie_info_idx (
>     id integer NOT NULL PRIMARY KEY,
>     movie_id integer NOT NULL,
>     info_type_id integer NOT NULL,
>     info character varying NOT NULL,
>     note character varying(1)
> );
> 
> CREATE TABLE movie_keyword (
>     id integer NOT NULL PRIMARY KEY,
>     movie_id integer NOT NULL,
>     keyword_id integer NOT NULL
> );
> 
> CREATE TABLE movie_link (
>     id integer NOT NULL PRIMARY KEY,
>     movie_id integer NOT NULL,
>     linked_movie_id integer NOT NULL,
>     link_type_id integer NOT NULL
> );
> 
> CREATE TABLE name (
>     id integer NOT NULL PRIMARY KEY,
>     name character varying NOT NULL,
>     imdb_index character varying(9),
>     imdb_id integer,
>     gender character varying(1),
>     name_pcode_cf character varying(5),
>     name_pcode_nf character varying(5),
>     surname_pcode character varying(5),
>     md5sum character varying(32)
> );
> 
> CREATE TABLE role_type (
>     id integer NOT NULL PRIMARY KEY,
>     role character varying(32) NOT NULL
> );
> 
> CREATE TABLE title (
>     id integer NOT NULL PRIMARY KEY,
>     title character varying NOT NULL,
>     imdb_index character varying(5),
>     kind_id integer NOT NULL,
>     production_year integer,
>     imdb_id integer,
>     phonetic_code character varying(5),
>     episode_of_id integer,
>     season_nr integer,
>     episode_nr integer,
>     series_years character varying(49),
>     md5sum character varying(32)
> );
> 
> CREATE TABLE movie_info (
>     id integer NOT NULL PRIMARY KEY,
>     movie_id integer NOT NULL,
>     info_type_id integer NOT NULL,
>     info character varying NOT NULL,
>     note character varying
> );
> 
> CREATE TABLE person_info (
>     id integer NOT NULL PRIMARY KEY,
>     person_id integer NOT NULL,
>     info_type_id integer NOT NULL,
>     info character varying NOT NULL,
>     note character varying
> );

**Comment by ma853529615** [comment]
And I have reproduced this error in pg_strom 5.0 build on pg 15.3.

**Comment by kaigai** [comment]
I found a problem that makes PostgreSQL backend crashed during reproduction of this issue.
It came from the logic GEOQ optimization when number of joined relations exceeds the threshold of GEOQ.

The commit `11587e787dad718e8d10f7c05ddee2d55cd830e1` fixed this problem.
And, can you still reproduce the problem you reported?

If so, could you give us the test dataset to reproduce the problem.

**Comment by ma853529615** [comment]
Thanks for your reply. I have run the new commit `11587e787dad718e8d10f7c05ddee2d55cd830e1`. These queries can successfully execute on an empty IMDb database with only tables defined and no data inserted. But after I import the data into these tables, PG still returns errors.

The interesting thing is that I run these queries in PG=12.1 with pg_strom=3.5, Close the GEOQ and open the cpu_fallback, all these queries running well.

**Comment by ma853529615** [comment]
The new error return by the PG=15.4 and pg_strom=commit `11587e7`: 
2023-09-09 22:38:58.034 CST [53527] LOG:  database system was shut down at 2023-08-22 17:56:00 CST
2023-09-09 22:38:58.040 CST [53496] LOG:  database system is ready to accept connections
2023-09-09 22:42:36.778 CST [53496] LOG:  background worker "parallel worker" (PID 57239) was terminated by signal 11: Segmentation fault
2023-09-09 22:42:36.778 CST [53496] DETAIL:  Failed process was running: SELECT COUNT(*) FROM title as t,
	kind_type as kt,
	info_type as it1,
	movie_info as mi1,
	cast_info as ci,
	role_type as rt,
	name as n,
	movie_keyword as mk,
	keyword as k,
	movie_companies as mc,
	company_type as ct,
	company_name as cn
	WHERE
	t.id = ci.movie_id
	AND t.id = mc.movie_id
	AND t.id = mi1.movie_id
	AND t.id = mk.movie_id
	AND mc.company_type_id = ct.id
	AND mc.company_id = cn.id
	AND k.id = mk.keyword_id
	AND mi1.info_type_id = it1.id
	AND t.kind_id = kt.id
	AND ci.person_id = n.id
	AND ci.role_id = rt.id
	AND (it1.id IN ('7'))
	AND (mi1.info in ('MET:','OFM:35 mm','PCS:Digital Intermediate','PFM:35 mm','PFM:Video','RAT:1.33 : 1','RAT:1.37 : 1'))
	AND (kt.kind in ('episode','movie','tv movie'))
	AND (rt.role in ('actor','actress'))
	AND (n.gender in ('f','m') OR n.gender IS NULL)
	AND (n.name_pcode_cf in ('A5362','J5252','R1632','R2632','W4525'))
	AND (t.production_year <= 2015)
	AND (t.production_year >= 1925)
	AND (cn.name in ('Fox Network','Independent Television (ITV)','Metro-Goldwyn-Mayer (MGM)','National Broadcasting
2023-09-09 22:42:36.778 CST [53496] LOG:  terminating any other active server processes
2023-09-09 22:42:36.792 CST [57286] FATAL:  the database system is in recovery mode

**Comment by ma853529615** [comment]
The dataset to reproduce the error: [imdb.tgz]((http://homepages.cwi.nl/~boncz/job/imdb.tgz))
You need to create the tables by running the command in the file: schematext.sql 
And import the data in the file: import.sql

**Comment by ma853529615** [comment]
The dataset to reproduce the error: [imdb.tgz]((http://homepages.cwi.nl/~boncz/job/imdb.tgz))
You need to create the tables by running the command in the file: schematext.sql 
And import the data in the file: import.sql

**Comment by kaigai** [comment]
This crash was caused by CPU-fallback routines not implemented yet.

Ths commit `5402d34dd3eddb7a4310dfe1bdc804d1da2f33bd` fixes the problem around CPU-fallback.
It looks the dataset contains long text (probably > 2kB), thus PostgreSQL stores these long text using
TOAST mechanism (long text is separated to multiple chunks, then saved in a shadow table).
GPU cannot access these shadow table, thus GPU-code of PG-Strom returns an error of CPU-fallback
request.
After that, host code of PG-Strom runs the query by CPU, if `pg_strom.cpu_fallback` is `on` or `notice`.
(Of course, it has no performance benefit, but avoid the error.)

**Comment by ma853529615** [comment]
Thanks for your help. In addition, How can I use the GDS feature in pg_strom? I have tried to connect to the email address shown on your company's website, but didn't get reply.

**Comment by kaigai** [comment]
Sorry, I found your request from the contact message this morning.
Please check the license file I sent back.

Best regards,

**Comment by ma853529615** [comment]
> Sorry, I found your request from the contact message this morning. Please check the license file I sent back.
> 
> Best regards,

I’m sorry, I didn't find that.  I have resent the requested email. And I would be grateful if you could recheck that or you can directly send the license to my other address majunhua123@outlook.com
