### ISSUE TITLE
[Error Bug] SUM(<money column>) brings errors

### ISSUE THREAD

**Issue by qwebug** [heterodb/pg-strom#624]
#### Describe:

Using SUM Function to compute MONEY type value will report an error, when pg\_strom.enabled is turned on. 
However the result is correct, when pg\_strom.enabled is turned off.

Sql:

```sql
CREATE TABLE IF NOT EXISTS t1(c0 money , c1 money);
INSERT INTO t1(c0, c1) VALUES(1, 1);
CREATE SCHEMA extensions;
CREATE EXTENSION pg_strom WITH SCHEMA extensions;
set pg_strom.enabled=on;
SELECT SUM(t1.c1) FROM t1;
```

Result:

```bash
ERROR:  Catalog corruption? 'psum(money)' was not found
```

Sql:

```sql
set pg_strom.enabled=off;
SELECT SUM(t1.c1) FROM t1;
```

Result:

```sql
  sum  
-------
 $1.00
```

##### commit: c420da11d4b2339552dc0d9995c0d9b68941b68e

postgres version: 15.3

CUDA Version: 12.0.1

NVIDIA Driver Version: 535.86.05   &#x20;

**Comment by kaigai** [comment]
`4ac6d95339494f901b93acb384186415dfe63c1b` may fix this problem.

Thanks for your report.

**Comment by qwebug** [comment]
This problem is fixed, after my verification.
Thanks for your work.
