### ISSUE TITLE
[Logic Bug] SELECT <column> FROM JOIN tables ON (CAST(<decimal> AS MONEY)) Brings Logic Bug

### ISSUE THREAD

**Issue by qwebug** [heterodb/pg-strom#628]
### Describe:

&#x20;SELECT table1\<column> FROM table1 RIGHT OUTER JOIN table2 ON (CAST(\<decimal> AS MONEY) NOT IN CAST(\<decimal> AS MONEY)) brings different results,  when turn on and off pg\_strom.enabled.

#### SQL < pg\_strom.enabled ON >:

```sql
CREATE TABLE t1(c0 INT);
CREATE TABLE t2(LIKE t1);
INSERT INTO t2(c0) VALUES(1);
INSERT INTO t1(c0) VALUES(1);
CREATE SCHEMA extensions;
CREATE EXTENSION pg_strom WITH SCHEMA extensions;
set pg_strom.enabled=on;
SELECT t1.c0 FROM t1 RIGHT OUTER JOIN t2 ON ((CAST(0.1 AS MONEY)) NOT IN (CAST(0.1 AS MONEY)));
```

Result:

```bash
 c0 
----
(0 rows)
```

#### SQL < pg\_strom.enabled OFF >:

```sql
set pg_strom.enabled=off;
SELECT t1.c0 FROM t1 RIGHT OUTER JOIN t2 ON ((CAST(0.1 AS MONEY)) NOT IN (CAST(0.1 AS MONEY)));
```

Result:

```bash
 c0 
----
   
(1 row)
```

Futhermore, if change RIGHT OUTER JOIN to LEFT OUTER JOIN or INNER JOIN, errors also occur while pg\_strom.enabled is turned on.

### Environment:

Pg-strom Version: commit 4ac6d95339494f901b93acb384186415dfe63c1b

PostgreSQL Version: 15.3 on x86\_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit

CUDA Version: 12.0.1

NVIDIA Driver Version: 535.86.05

**Comment by kaigai** [comment]
`48b2ca888608ced4cd0844800b2b77fd8eb0fe5a` should fix this problem.

It came from the two independent bugs.
1. GpuNestLoop didn't pick up NULL-tuple even if the current outer-row has no matched inner-rows.
2. ExecLoadVarsHeapTuple() didn't fill up kvars-slot by NULL, even if NULL-tuple was supplied, so previous values were remained at the GpuProjection stage.

Thanks for your reports.

**Comment by qwebug** [comment]
This problem is fixed, after my verification.
Thanks for your work.
