### ISSUE TITLE
[Logic Bug] "SELECT <column> FROM table LEFT OUTER JOIN table ON (<column> IS DISTINCT FROM(CAST(1.0E1 AS MONEY))) WHERE (<column>) IS NULL " Brings Errors

### ISSUE THREAD

**Issue by qwebug** [heterodb/pg-strom#630]
#### Describe:

SELECT \<column> FROM table LEFT OUTER JOIN table ON (\<column> IS DISTINCT FROM(CAST(1.0E1 AS MONEY))) WHERE (\<column>) IS NULL  brings different results, when turn on and off pg\_strom.enabled.

#### ***Sql:***

```sql
CREATE TABLE t0(c0 money , c1 boolean);
CREATE TABLE t1(LIKE t0);
INSERT INTO t0(c0, c1) VALUES((1)::MONEY, TRUE);
INSERT INTO t1(c0, c1) VALUES((1)::MONEY, TRUE);
CREATE SCHEMA extensions;
CREATE EXTENSION pg_strom WITH SCHEMA extensions;
set pg_strom.enabled=on;
SELECT SUM(t1.c0) FROM t1 LEFT OUTER JOIN t0 ON ((t0.c0)IS DISTINCT FROM(CAST(1.0E1 AS MONEY))) WHERE (t0.c1) IS NULL;
```

#### Result:

```bash
  sum  
-------
 $1.00
(1 row)
```

Sql:

```sql
set pg_strom.enabled=off;
SELECT SUM(t1.c0) FROM t1 LEFT OUTER JOIN t0 ON ((t0.c0)IS DISTINCT FROM(CAST(1.0E1 AS MONEY))) WHERE (t0.c1) IS NULL;
```

Result:

```sql
 sum 
-----
    
(1 row)
```

### Environment:

Pg-strom Version: commit b1a487ba2fb6946ba41289a6719ef1769e9c7c39

PostgreSQL Version: 15.3 on x86\_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit

CUDA Version: 12.0.1

NVIDIA Driver Version: 535.86.05

**Comment by kaigai** [comment]
`decd56acd3d4fef2ba09177919bc88c32c10731b` should fix this problem.
It came from a combined problems; 1. wrong OUTER JOIN handling and CPU fallback, and 2. wrong DISTINCT FROM implementation at the device code.

This was too corner case. Thanks for your report.

**Comment by qwebug** [comment]
This problem is fixed, after my verification.
Thanks for your work.
