### ISSUE TITLE
[Crash Bug] A Sepcial SQL Causes Crash ( SELECT * FROM (SELECT <column> AS f1, <column> AS f2 FROM table) AS table WHERE((f2) IN (f2, 1)) AND (NOT (f1 = ALL (SELECT <column> FROM table))) )

### ISSUE THREAD

**Issue by qwebug** [heterodb/pg-strom#632]
#### Describe:

Using a special sql as follow will cause crash, when pg\_strom.enabled is turned on.

However it is able to output result, when pg\_strom.enabled is turned off.

#### ***Sql:***

```sql
create table t0 (c1 float, c2 decimal(40, 20));
CREATE SCHEMA extensions;
CREATE EXTENSION pg_strom WITH SCHEMA extensions;
insert into t0 values (1,0.1);
set pg_strom.enabled=on;
SELECT * FROM
        (SELECT c2 AS f1,
                c1 AS f2
         FROM t0) AS t3
      WHERE((f2) IN (f2, 1))
        AND (NOT (f1 = ALL
                    (SELECT c2
                     FROM t0)));
```

#### Result:

```bash
server closed the connection unexpectedly
This probably means the server terminated abnormally before or while processing the request.
error: connection to server was lost
```

Sql:

```sql
set pg_strom.enabled=off;
SELECT * FROM
        (SELECT c2 AS f1,
                c1 AS f2
         FROM t0) AS t3
      WHERE((f2) IN (f2, 1))
        AND (NOT (f1 = ALL
                    (SELECT c2
                     FROM t0)));
```

Result:

```sql
 f22 | f23 
-----+-----
(0 rows)
```

### Environment:

Pg-strom Version: commit b1a487ba2fb6946ba41289a6719ef1769e9c7c39

PostgreSQL Version: 15.3 on x86\_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit

CUDA Version: 12.0.1

NVIDIA Driver Version: 535.86.05

**Comment by kaigai** [comment]
I can reproduce the problem at the `decd56acd3d4fef2ba09177919bc88c32c10731b`, and crashed at the same location that was reported at #631.
`a4f25fea03dd1d281957d5f0e082f7ea81f40246` should already fixed.

**Comment by qwebug** [comment]
This problem is fixed, after my verification.
Thanks for your work.
