### ISSUE TITLE
[Error Bug] SELECT AVG(decimal) FROM table GROUP BY <column> Brings Errors

### ISSUE THREAD

**Issue by qwebug** [heterodb/pg-strom#633]
#### Describe:

Using SELECT AVG(decimal) FROM table GROUP BY \<column> will report an error, when pg\_strom.enabled is turned on.

However it is able to output result, when pg\_strom.enabled is turned off.

#### ***Sql:***

```sql
CREATE TABLE t0(c0 INT );
INSERT INTO t0(c0) VALUES(1);
CREATE SCHEMA extensions;
CREATE EXTENSION pg_strom WITH SCHEMA extensions;
SET pg_strom.enabled=on;
SELECT AVG(0.1) FROM t0 GROUP BY t0.c0;
```

#### Result:

```bash
ERROR:  Catalog corruption? 'avg_num(bytea)' was not found
```

Sql:

```sql
SET pg_strom.enabled=off;
SELECT AVG(0.1) FROM t0 GROUP BY t0.c0;
```

Result:

```sql
          avg           
------------------------
 0.10000000000000000000
(1 row)
```

### Environment:

Pg-strom Version: commit b1a487ba2fb6946ba41289a6719ef1769e9c7c39

PostgreSQL Version: 15.3 on x86\_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit

CUDA Version: 12.0.1

NVIDIA Driver Version: 535.86.05

**Comment by kaigai** [comment]
The commit `b7c5b25eee1f6929e6eb616d5f4e40fca5d844f6` changed SQL definitions.
Please drop the extension once, then `CREATE EXTENSION pg_strom` again.

At `a4f25fea03dd1d281957d5f0e082f7ea81f40246` (the latest), I could not reproduce the problem.

**Comment by qwebug** [comment]
This problem is fixed, after my verification.
Thanks for your work.
