### ISSUE TITLE
[Crash Bug] A Sepcial SQL Cause Crash ( SELECT MIN(<column>) FROM table LEFT OUTER JOIN (SELECT <column> FROM table) AS sub0 ON (<column> > 0) GROUP BY (<column>) HAVING BOOL_AND(TRUE);  )

### ISSUE THREAD

**Issue by qwebug** [heterodb/pg-strom#634]
#### Describe:

Using a special sql as follow will cause crash, when pg\_strom.enabled is turned on.

However it is able to output result, when pg\_strom.enabled is turned off.

#### ***Sql:***

```sql
CREATE TABLE t1(c0 int);
CREATE TABLE t2(LIKE t1);
INSERT INTO t1(c0) VALUES(1);
INSERT INTO t2(c0) VALUES(1);
CREATE SCHEMA extensions;
CREATE EXTENSION pg_strom WITH SCHEMA extensions;
set pg_strom.enabled=on;
SELECT MIN(t2.c0)
FROM t2
LEFT OUTER JOIN
    (SELECT c0 FROM t1) AS sub0 
        ON (t2.c0 > 0) 
GROUP BY (t2.c0)
HAVING BOOL_AND(TRUE);
```

#### Result:

```bash
server closed the connection unexpectedly
This probably means the server terminated abnormally before or while processing the request.
error: connection to server was lost
```

Sql:

```sql
set pg_strom.enabled=off;
SELECT MIN(t2.c0)
FROM t2
LEFT OUTER JOIN
    (SELECT c0 FROM t1) AS sub0 
        ON (t2.c0 > 0) 
GROUP BY (t2.c0)
HAVING BOOL_AND(TRUE);
```

Result:

```sql
 min 
-----
   1
(1 row)
```

### Environment:

Pg-strom Version: commit b1a487ba2fb6946ba41289a6719ef1769e9c7c39

PostgreSQL Version: 15.3 on x86\_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit

CUDA Version: 12.0.1

NVIDIA Driver Version: 535.86.05

**Comment by kaigai** [comment]
`c9da89bc84b6c77dd82b757eba8cafc5bce91d58` should fix this problem.
I could not reproduce the problem at the latest revision, but prior to this commit made a server crash.

This commit fixes the wrong status check around HAVING clause.

**Comment by qwebug** [comment]
This problem is fixed, after my verification.
Thanks for your work.
