### ISSUE TITLE
[Error Bug] SELECT MIN(<column>) FROM table GROUP BY <column> HAVING CAST((MIN('1')) AS BOOLEAN) Brings Errors

### ISSUE THREAD

**Issue by qwebug** [heterodb/pg-strom#635]
#### Describe:

Using SELECT MIN(\<column>) FROM table GROUP BY \<column>  HAVING CAST((MIN('1')) AS BOOLEAN) will report an error, when pg\_strom.enabled is turned on.

However it is able to output result, when pg\_strom.enabled is turned off.

#### ***Sql:***

```sql
CREATE TABLE t0(c0 int , c1 int );
INSERT INTO t0(c0, c1) VALUES(1, 1);
CREATE SCHEMA extensions;
CREATE EXTENSION pg_strom WITH SCHEMA extensions;
set pg_strom.enabled=on;
SELECT MIN(c0) FROM t0 GROUP BY t0.c0 HAVING CAST((MIN('1')) AS BOOLEAN);
```

#### Result:

```bash
ERROR:  cache lookup failed for type 0
```

Sql:

```sql
set pg_strom.enabled=off;
SELECT MIN(c0) FROM t0 GROUP BY t0.c0 HAVING CAST((MIN('1')) AS BOOLEAN);
```

Result:

```sql
 min 
-----
   1
(1 row)
```

### Environment:

Pg-strom Version: commit b1a487ba2fb6946ba41289a6719ef1769e9c7c39

PostgreSQL Version: 15.3 on x86\_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit

CUDA Version: 12.0.1

NVIDIA Driver Version: 535.86.05

**Comment by kaigai** [comment]
I could not reproduce the problem at the latest revision.
Likely, the commit `c9da89bc84b6c77dd82b757eba8cafc5bce91d58` should fixed the problem.

**Comment by qwebug** [comment]
This problem is fixed, after my verification.
Thanks for your work.
