### ISSUE TITLE
[Error Bug] SELECT MAX(<column>) FROM table GROUP BY <column> HAVING <column> < MIN(<column>) Brings Errors

### ISSUE THREAD

**Issue by qwebug** [heterodb/pg-strom#636]
#### Describe:

Using SELECT MAX(\<column>) FROM table GROUP BY \<column> HAVING \<column> < MIN(\<column>) will report an error, when pg\_strom.enabled is turned on.

However it is able to output result, when pg\_strom.enabled is turned off.

#### ***Sql:***

```sql
CREATE TABLE t0(c0 INT , c1 INT  PRIMARY KEY );
INSERT INTO t0(c1, c0) VALUES(1, 1);
CREATE SCHEMA extensions;
CREATE EXTENSION pg_strom WITH SCHEMA extensions;
set pg_strom.enabled=on;
SELECT MAX(c0) FROM t0 GROUP BY t0.c1 HAVING t0.c0<MIN(t0.c0);
```

#### Result:

```bash
ERROR:  Bug? referenced variable is grouping-key nor its dependent key: {VAR :varno 1 :varattno 1 :vartype 23 :vartypmod -1 :varcollid 0 :varlevelsup 0 :varnosyn 1 :varattnosyn 1 :location 45}
```

Sql:

```sql
set pg_strom.enabled=off;
SELECT MAX(c0) FROM t0 GROUP BY t0.c1 HAVING t0.c0<MIN(t0.c0);
```

Result:

```sql
 max 
-----
(0 rows)
```

### Environment:

Pg-strom Version: commit b1a487ba2fb6946ba41289a6719ef1769e9c7c39

PostgreSQL Version: 15.3 on x86\_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit

CUDA Version: 12.0.1

NVIDIA Driver Version: 535.86.05

**Comment by kaigai** [comment]
```
SELECT MAX(c0) FROM t0 GROUP BY t0.c1 HAVING t0.c0<MIN(t0.c0);
```

I'm not certain how this query should work, because `t0.c0` is not a grouping-key, thus it shall not be appear at the post-group-by phase.
Right now, I have no idea about right direction of this issue. So, let me move the discussion to the pgsql-hackers.

**Comment by kaigai** [comment]
https://www.postgresql.org/message-id/181d12be-302e-c05b-7320-3e700ae9a554%40postgresfriends.org

Hmm... I was missing this point.

**Comment by kaigai** [comment]
`6552e69f2ad521832eaefd7edd4a8ac808ec7cf1` fixes this problem.

This change allows to reference non-grouping-key columns in HAVING clause, if PostgreSQL allows the statement.

**Comment by qwebug** [comment]
This problem is fixed, after my verification.
Thanks for your work.
