### ISSUE TITLE
[Logic Bug]  SELECT MIN(1) FROM table GROUP BY <column> HAVING NOT (MIN(1))::BOOLEAN Brings Errors

### ISSUE THREAD

**Issue by qwebug** [heterodb/pg-strom#638]
#### Describe:

&#x20;Using SELECT MIN(1) FROM table GROUP BY \<column> HAVING NOT (MIN(1))::BOOLEAN and set enable_seqscan=0 brings different results, when turn on and off pg\_strom.enabled.

#### ***Sql:***

```sql
CREATE TABLE t1(c0 int) USING heap;
SET enable_seqscan=0;
INSERT INTO t1(c0) VALUES(1);
CREATE SCHEMA extensions;
CREATE EXTENSION pg_strom WITH SCHEMA extensions;
set pg_strom.enabled=on;
SELECT MIN(1) FROM t1 GROUP BY t1.c0 HAVING NOT (MIN(1))::BOOLEAN;
```

#### Result:

```bash
 min |  
-----+--
(0 rows)
```

Sql:

```sql
set pg_strom.enabled=off;
SELECT MIN(1) FROM t1 GROUP BY t1.c0 HAVING NOT (MIN(1))::BOOLEAN;
```

Result:

```sql
 min 
-----
(0 rows)
```

### Environment:

Pg-strom Version: commit b1a487ba2fb6946ba41289a6719ef1769e9c7c39

PostgreSQL Version: 15.3 on x86\_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit

CUDA Version: 12.0.1

NVIDIA Driver Version: 535.86.05

**Comment by kaigai** [comment]
I could not reproduce the problem at the latest commit, but prior to the `e7556e3f2d25e44598924329e1d46f42de7fa540` could reproduce it. I believe it is identical problem to #639, and already fixed.

**Comment by qwebug** [comment]
This problem is fixed, after my verification.
Thanks for your work.
