### ISSUE TITLE
[Logic Bug]  A Sepcial SQL Brings Errors ( SELECT MIN(<column>) FROM table LEFT OUTER JOIN (SELECT <column> FROM table) AS sub0 ON (<column> > 0) GROUP BY (<column>) HAVING TRUE; )

### ISSUE THREAD

**Issue by qwebug** [heterodb/pg-strom#639]
#### Describe:

&#x20;Using a special sql as follow brings different results, when turn on and off pg\_strom.enabled.

#### ***Sql:***

```sql
CREATE TABLE t1(c0 int);
CREATE TABLE t2(LIKE t1);
INSERT INTO t1(c0) VALUES(1);
INSERT INTO t2(c0) VALUES(1);
CREATE SCHEMA extensions;
CREATE EXTENSION pg_strom WITH SCHEMA extensions;
set pg_strom.enabled=on;
SELECT MIN(t2.c0)
FROM t2
LEFT OUTER JOIN
    (SELECT c0 FROM t1) AS sub0 
        ON t2.c0 > 0 
GROUP BY (t2.c0)
HAVING TRUE;
```

#### Result:

```bash
 min |   
-----+---
   1 | 1
(1 row)
```

Sql:

```sql
set pg_strom.enabled=off;
SELECT MIN(t2.c0)
FROM t2
LEFT OUTER JOIN
    (SELECT c0 FROM t1) AS sub0 
        ON t2.c0 > 0 
GROUP BY (t2.c0)
HAVING TRUE;
```

Result:

```sql
 min 
-----
   1
(1 row)
```

### Environment:

Pg-strom Version: commit b1a487ba2fb6946ba41289a6719ef1769e9c7c39

PostgreSQL Version: 15.3 on x86\_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit

CUDA Version: 12.0.1

NVIDIA Driver Version: 535.86.05

**Comment by kaigai** [comment]
Thanks for your report.
`e7556e3f2d25e44598924329e1d46f42de7fa540` should fix the problem.

PG-Strom didn't keep the `resjunk` flag of unreferenced grouping-keys at the post-optimization process.

**Comment by qwebug** [comment]
This problem is fixed, after my verification.
Thanks for your work.
