### ISSUE TITLE
[ERROR Bug] A Sepcial SQL Brings  Errors ( SELECT ((<column> BETWEEN SYMMETRIC <integer> AND <integer>)OR((<decimal>::MONEY) IN (CAST(<decimal> AS MONEY), CAST(<decimal> AS MONEY)))) FROM <table> WHERE (<column>) BETWEEN SYMMETRIC (<integer>) AND (<column>) )

### ISSUE THREAD

**Issue by qwebug** [heterodb/pg-strom#645]
#### Describe:

&#x20;Using SELECT ((\<column> BETWEEN SYMMETRIC \<integer> AND \<integer>)OR((\<decimal>::MONEY) IN (CAST(\<decimal> AS MONEY), CAST(\<decimal> AS MONEY)))) FROM \<table> WHERE (\<column>) BETWEEN SYMMETRIC (\<integer>) AND (\<column>) brings  error, when turn on and off pg\_strom.enabled.

However it is able to output result, when pg\_strom.enabled is turned off.

#### ***Sql:***

```sql
CREATE TEMP TABLE IF NOT EXISTS t1(c0 int);
CREATE TABLE IF NOT EXISTS t3(LIKE t1);
INSERT INTO t1(c0) VALUES(1);
INSERT INTO t3(c0) VALUES(1);
CREATE SCHEMA extensions;
CREATE EXTENSION pg_strom WITH SCHEMA extensions;
set pg_strom.enabled=on;
SELECT (((t1.c0) BETWEEN SYMMETRIC 0 AND 1)OR(((0.1)::MONEY) IN (CAST(0.1 AS MONEY), CAST(0.0 AS MONEY)))) FROM t1, t3 WHERE (t1.c0) BETWEEN SYMMETRIC (0) AND (t3.c0);
```

#### ***Result:***

```bash
ERROR:  unrecognized node type: 231
```

#### ***Sql:***

```sql
set pg_strom.enabled=off;
SELECT (((t1.c0) BETWEEN SYMMETRIC 0 AND 1)OR(((0.1)::MONEY) IN (CAST(0.1 AS MONEY), CAST(0.0 AS MONEY)))) FROM t1, t3 WHERE (t1.c0) BETWEEN SYMMETRIC (0) AND (t3.c0);
```

#### ***Result:***

```bash
 ?column? 
----------
 t
(1 row)
```

### Environment:

Pg-strom Version: commit b959fef3547bb9050d8159bb2d8cd4aa4dc918d5

PostgreSQL Version: 15.3 on x86\_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit

CUDA Version: 12.0.1

NVIDIA Driver Version: 535.86.05

**Comment by kaigai** [comment]
`a64cc156a47d2632016f1cd64cfb7cb6b22facc2` will fix this problem.
It come from a wrong checks of device supported expression. In the result, it wrongly transform the arguments of array constructor to device executable opcodes.

**Comment by qwebug** [comment]
This problem is fixed, after my verification.
Thanks for your work.
