### ISSUE TITLE
[GPU ERROR Bug] A Sepcial SQL Brings  Errors ( SELECT ('<interval>'::int4range), <column>::INT FROM <table> WHERE (<column>!=<column>) )

### ISSUE THREAD

**Issue by qwebug** [heterodb/pg-strom#646]
#### Describe:

&#x20;Using SELECT ('\<interval>'::int4range), \<column>::INT FROM \<table> WHERE (\<column>!=\<column>) brings GPU error, when turn on and off pg\_strom.enabled.

However it is able to output result, when pg\_strom.enabled is turned off.

#### ***Sql:***

```sql
CREATE TABLE t1(c0 CHAR, c1 DECIMAL);
CREATE TABLE t2(LIKE t1);
CREATE TABLE t3(LIKE t1);
INSERT INTO t3(c0, c1) VALUES(B'1', 0.5);
INSERT INTO t2(c0, c1) VALUES(B'1', 0.7);
INSERT INTO t1(c0) VALUES(B'1');
SET SESSION enable_sort=DEFAULT;
CREATE SCHEMA extensions;
CREATE EXTENSION pg_strom WITH SCHEMA extensions;
set pg_strom.enabled=on;
SELECT ('[0,1)'::int4range), (t1.c1)::INT FROM t1, t2, t3 WHERE ((t3.c1)!=(t2.c1));
```

#### ***Result:***

```bash
ERROR:  gpu_service.c:1823  failed on cuEventSynchronize: CUDA_ERROR_ASSERT
HINT:  device at GPU-0, function at gpuservHandleGpuTaskExec
```

#### ***Sql:***

```sql
set pg_strom.enabled=off;
SELECT ('[0,1)'::int4range), (t1.c1)::INT FROM t1, t2, t3 WHERE ((t3.c1)!=(t2.c1));
```

#### ***Result:***

```bash
 int4range | c1 
-----------+----
 [0,1)     | 
(1 row)
```

### Environment:

Pg-strom Version: commit b959fef3547bb9050d8159bb2d8cd4aa4dc918d5

PostgreSQL Version: 15.3 on x86\_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit

CUDA Version: 12.0.1

NVIDIA Driver Version: 535.86.05

**Comment by kaigai** [comment]
incorrect numeric --> int type case at GPU code.
`142464a23aacd7ab9734dd2b5be31acd06634529` fixed this problem.

**Comment by qwebug** [comment]
This problem is fixed, after my verification.
Thanks for your work.
