### ISSUE TITLE
Question about GPU_Cache

### ISSUE THREAD

**Issue by ma853529615** [heterodb/pg-strom#657]
I have found an interesting thing in the GPU_Cache feature.

A query's latency with different setting:
pg_strom=off: 7800ms,
pg_strom=on: 20000ms,
pg_strom=on & cache the main fact table: 7800ms.

But, when I repeat the execution with pg_strom, the query latency is decreased to 4900ms. 
I didn't find the same phenomenon when pg_strom is off, and with no cached but pg_strom is on.

How could that happen? Is there any tech made for this improvement? Could you please explain it intuitively? Thanks.

**Comment by ma853529615** [comment]
@kaigai

**Comment by kaigai** [comment]
even though I don't know your workload details, the second query execution involves cache redo log synchronization before query execution.
GpuCache applies redo logs that are not loaded to GPU before execution of analytic queries.
