### ISSUE TITLE
(VTJ-JP) ライセンスファイルに記載されていないGPUがPG-Strom GPU Serviceによって使われてしまう

### ISSUE THREAD

**Issue by ytooyama** [heterodb/pg-strom#661]
## 再現方法

- ライセンスファイルのGPU行をすべてコメントアウト
- PostgreSQLサービスを再起動
- nvidia-smiを実行
  - PG-Strom GPU Service プロセスがGPUの数だけ起動されていることが確認できる
- クエリを実行
- コメントアウトしているのにPG-Strom GPU Service のプロセスの数だけGPUが使われる

## 問題となりうること

GPUを複数実装しており色々な用途でGPUコンピューティングをしているような環境で、想定していないGPUをPG-Stromに利用される可能性があります。

**Comment by kaigai** [comment]
これは`GPU_UUID`行をコメントアウトしても意味はありません。
（`----` より下の行は、人間が読めるように書いているだけなので）

特定のGPUを使わないようにするには、環境変数 `CUDA_VISIBLE_DEVICES` を使ってください。
