### ISSUE TITLE
What is the minimum supported version of Postgres required

### ISSUE THREAD

**Issue by JoshInnis** [heterodb/pg-strom#665]
Hello,

In the documentation it is listed:
```
PostgreSQL
    PG-Strom v3.0 requires PostgreSQL v11 or later.
```

However, pg_strom.h has this line:
```
#if PG_VERSION_NUM < 150000
#error Base PostgreSQL version must be v15 or later
#endif
#define PG_MAJOR_VERSION (PG_VERSION_NUM / 100)
#define PG_MINOR_VERSION (PG_VERSION_NUM % 100)
```

I looked in the branches and tags, but I am unclear if there is a tag that supports previous versions. Could you please help me understand if I must have PG15+ or can I use an older version of Postgres?

**Comment by kaigai** [comment]
Due to our man power, documentation updates is delayed.
Sorry for this inconvenience.

**Comment by kaigai** [comment]
Please use PostgreSQL v15. A known issue is reported at PG16.

**Comment by JoshInnis** [comment]
Thank You!
