### ISSUE TITLE
[ERROR Bug] A Sepcial SQL Brings Errors ( SELECT <columns> FROM <table> FULL OUTER JOIN <table> ON <columns> IN <columns> WHERE (<columns>) IN (<MONEY>)) ISNULL )

### ISSUE THREAD

**Issue by qwebug** [heterodb/pg-strom#680]
#### Describe:

Using SELECT \<columns> FROM \<table> FULL OUTER JOIN \<table> ON \<columns> IN \<columns> WHERE (\<columns>) IN (\<MONEY>)) ISNULL brings error, when turn on and off pg\_strom.enabled.

However it is able to output result, when pg\_strom.enabled is turned off.

#### ***Sql:***

```sql
CREATE TABLE t0(c0 money, c1 BIT, c2 inet);
CREATE TABLE IF NOT EXISTS t1(LIKE t0);
INSERT INTO t1(c2, c0) VALUES('45.143.62.35', (1.0)::MONEY);
INSERT INTO t0(c1, c0, c2) VALUES('B1', CAST(0.5 AS MONEY), '83.157.203.154');
CREATE SCHEMA extensions;
CREATE EXTENSION pg_strom WITH SCHEMA extensions;
set pg_strom.enabled=on;
SELECT t1.c1, t0.c2 FROM t1 FULL OUTER JOIN t0 ON (t0.c2) IN (t1.c2) WHERE ((t0.c0) IN ((0.1)::MONEY)) ISNULL;
```

#### ***Result:***

```bash
ERROR:  could not format inet value: Address family not supported by protocol
```

#### ***Sql:***

```sql
set pg_strom.enabled=off;
SELECT t1.c1, t0.c2 FROM t1 FULL OUTER JOIN t0 ON (t0.c2) IN (t1.c2) WHERE ((t0.c0) IN ((0.1)::MONEY)) ISNULL;
```

#### ***Result:***

```bash
 c1 | c2 
----+----
    | 
(1 row)
```

### Environment:

Pg-strom Version: commit 9765660eba4fab7e4e9378c667e6bd565da83ffd

PostgreSQL Version: 15.3 on x86\_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit

CUDA Version: 12.0.1

NVIDIA Driver Version: 535.86.05

**Comment by kaigai** [comment]
Fixed at `45138d736b63e9edf0370d4ce97334ade9c89747`.
Thanks for your report.
