### ISSUE TITLE
There is a typo in the release notes v5

### ISSUE THREAD

**Issue by ytooyama** [heterodb/pg-strom#694]
path:
https://heterodb.github.io/pg-strom/ja/release_v5.0/
&
https://heterodb.github.io/pg-strom/release_v5.0/

change to:
`%s/Coalesced Mmoery Access/Coalesced Memory Access/g`

**Comment by kaigai** [comment]
`85df27d3fd4fd07aa02a04004354b7ec945a7eb2` で修正
