### ISSUE TITLE
arrow_fdw: writable 'true'を設定しているにも関わらずファイルオープンに失敗

### ISSUE THREAD

**Issue by 0-kaz** [heterodb/pg-strom#704]
arrow_fdwを用いてCREATE FOREIGN TABLEする際、writable 'true'オプションを指定している場合には、新規にarrowファイルが作成される仕様であるが、No such file or directoryエラーが生じる。

```sql
CREATE FOREIGN TABLE ft_2 (id int)
SERVER arrow_fdw
OPTIONS (file '/tmp/test_arrow_write_ft_1.arrow', writable 'true');
```

エラーメッセージ
```
ERROR:  arrow_fdw: unable to access '/tmp/test_arrow_write_ft_1.arrow': No such file or directory
```

**Comment by 0-kaz** [comment]
> arrow_fdwを用いてCREATE FOREIGN TABLEする際、writable 'true'オプションを指定している場合には、新規にarrowファイルが作成される仕様

上記認識違いでしたらその旨返信お願いします（そのままクローズします）

**Comment by kaigai** [comment]
あ、すいません。こちらは v5.0 で削除した機能です。

FDW介したArrowへの書込み自体がレアであるにも関わらず、トランザクション管理で無駄に実装が複雑になりますので。。。

**Comment by 0-kaz** [comment]
承知しました。
