### ISSUE TITLE
[VTJ-JP]インストールガイドのCentOS 8

### ISSUE THREAD

**Issue by ytooyama** [heterodb/pg-strom#721]
CentOS 8向けのCUDAはもはやリリースされていないため、インストールガイドのCentOS 8の記述を全て削除する必要がありそうです。

**Comment by kaigai** [comment]
`e7252c65cac240b6441831af07859f961b2c75dd` にて記述を修正しました。

**Comment by ytooyama** [comment]
良いと思います。
