### ISSUE TITLE
FATAL: incorrect gpuinfo -md format

### ISSUE THREAD

**Issue by alefcs23** [heterodb/pg-strom#725]
i've been having trouble starting database using a RTX 2060
everything installs fine but when starting database i get the error:
FATAL: incorrect gpuinfo -md format
can someone please help me?

**Comment by kaigai** [comment]
The internal command `gpuinfo` has not been no longer used.
I guess you used older version (v3.x series). Please update it to the latest one.

**Comment by alefcs23** [comment]
> The internal command `gpuinfo` has not been no longer used. I guess you used older version (v3.x series). Please update it to the latest one.

will the latest work with postgres 13 or do i have to update the whole database altogether?
