### ISSUE TITLE
[VTJ-JP]PG-Strom 5.0はPostgreSQL 15以降をサポートしているのに、サポートしていないPG12,13,14向けのテストがあり、PG16向けがない

### ISSUE THREAD

**Issue by ytooyama** [heterodb/pg-strom#735]
表題通りです。対応していないtest/12,test/13,test/14は、deadcodeにいれるとかするといいのかなと思います。

**Comment by kaigai** [comment]
PG16向けはいま作ってもらっていますー

**Comment by kaigai** [comment]
`76ef75e58fc25eac35f79315e0916b93fe58535d` で古いファイルを deadcode に移動してあります。
シンボリックリンクで参照したりはないはず。

**Comment by ytooyama** [comment]
確認しました。
