### ISSUE TITLE
fallback時のメッセージからインストール先パスを除外できるか？

### ISSUE THREAD

**Issue by 0-kaz** [heterodb/pg-strom#737]
リグレッションテストにて、CPU fallbackを意図的に発生させてメッセージを確認しているのですが、このメッセージに表示するファイル名にインストール先が含まれているため、インストール先による失敗が生じてしまいます。

```sql
-ERROR:  (xpu_textlib.h:56) CPU fallback due to text datum is compressed or external [xpu_text_is_valid]
+ERROR:  (/home/onishi/pgbin152/share/pos:56) CPU fallback due to text datum is compressed or external [xpu_text_is_valid]
```

**Comment by kaigai** [comment]
ありゃ。これはマズいですね。
実質的には basename(__FILE__) だけで十分なので、直してみます。

**Comment by kaigai** [comment]
`09eac008fc2856a8dc3053350cb0af45c6c94c35` これでどうでしょうか？

すいません、体調よろしくなく元気がないので、手元環境で試すまではやってません。

**Comment by 0-kaz** [comment]
ご対応ありがとうございました。basenameで表示されるようになったことを確認しました。
変更いただいたコードに対応したPRを出しております。よろしくお願い致します。
