### ISSUE TITLE
what could be causing the dependencies to fail?

### ISSUE THREAD

**Issue by alefcs23** [heterodb/pg-strom#741]
git archive --format=tar.gz \
            --prefix=pg_strom-5.0.4/ \
            -o pg_strom-5.0.4.tar.gz 863ac4832c692d28d6421aa75376ca6f7a003d22 \
            LICENSE Makefile Makefile.common \
            src arrow-tools test/ssbm
cp -f pg_strom-5.0.4.tar.gz /home/suporte/rpmbuild/SOURCES || exit 1
git show --format=raw 863ac4832c692d28d6421aa75376ca6f7a003d22:files/systemd-pg_strom.conf > \
        /home/suporte/rpmbuild/SOURCES/systemd-pg_strom.conf || exit 1
(git show --format=raw 863ac4832c692d28d6421aa75376ca6f7a003d22:files/pg_strom.spec.in |        \
        sed -e "s/@@STROM_VERSION@@/5.0/g"              \
            -e "s/@@STROM_RELEASE@@/4/g"                \
            -e "s/@@STROM_TARBALL@@/pg_strom-5.0.4/g"   \
            -e "s/@@PGSTROM_GITHASH@@/863ac4832c692d28d6421aa75376ca6f7a003d22/g"               \
            -e "s/@@PGSQL_VERSION@@/16/g";\
 git show --format=raw 863ac4832c692d28d6421aa75376ca6f7a003d22:CHANGELOG) > /home/suporte/rpmbuild/SPECS/pg_strom-PG16.spec
rpmbuild -ba /home/suporte/rpmbuild/SPECS/pg_strom-PG16.spec --undefine=_debugsource_packages
error: Failed build dependencies:
        postgresql16 is needed by pg_strom-PG16-5.0-4.x86_64
        postgresql16-devel is needed by pg_strom-PG16-5.0-4.x86_64
make: *** [Makefile:68: rpm-pg_strom] Error 11

**Comment by kaigai** [comment]
If you want to build PG-Strom towards the current system, change directory to `src`, or use `make -C src -j 8`.
