### ISSUE TITLE
wrong varnullingrelsエラー

### ISSUE THREAD

**Issue by 0-kaz** [heterodb/pg-strom#757]
#630 をPG16で確認したところ、タイトルのエラーが生じています。

再現クエリ
```sql
DROP TABLE IF EXISTS t0;
DROP TABLE IF EXISTS t1;
CREATE TABLE t0(c0 money , c1 boolean);
CREATE TABLE t1(LIKE t0);
INSERT INTO t0(c0, c1) VALUES((1)::MONEY, TRUE);
INSERT INTO t1(c0, c1) VALUES((1)::MONEY, TRUE);
EXPLAIN(costs off, verbose)
SELECT SUM(t1.c0) FROM t1 LEFT OUTER JOIN t0 ON ((t0.c0)IS DISTINCT FROM(CAST(1.0E1 AS MONEY))) WHERE (t0.c1) IS NULL;
```

エラーメッセージ
```
ERROR:  wrong varnullingrels (b 3) (expected (b)) for Var 2/2
```

メッセージで検索してみると、16.2のリリースノートがヒットしたので、バージョン違いの影響と思われます。

https://www.postgresql.org/docs/release/16.2/

**Comment by kaigai** [comment]
`equal()`関数で一致不一致を見てる部分かな。

#754 の修正が終わったら見てみます。

**Comment by kaigai** [comment]
`9aa91515e75c36365e3ce4ba8bc48fe5d17c2c60` で修正しました。

あと、`heterodb-extra` のアップデートもお願いします（これは本件と直接の関係はないですが）

**Comment by 0-kaz** [comment]
解消確認できました。クローズします。
heterodb-extraはアップデート済みです。
