### ISSUE TITLE
[GPU Logic Bug] SELECT <column> FROM <table> GROUP BY <column> Brings GPU Logic Bug

### ISSUE THREAD

**Issue by qwebug** [heterodb/pg-strom#789]
### Describe:

&#x20;SELECT \<column> FROM \<table> GROUP BY \<column> brings different results, when using CPU-only configurations and GPU-used configurations.

#### SQL with CPU-only Config:

```sql
CREATE TABLE t0(c0 REAL PRIMARY KEY UNIQUE) USING heap;
CREATE TABLE t2(LIKE t0);
SET jit_above_cost=DEFAULT;
SET enable_seqscan=0;
INSERT INTO t2(c0) VALUES(9.3), (0.6), (0.7);
CREATE SCHEMA extensions;
CREATE EXTENSION pg_strom WITH SCHEMA extensions;
SET pg_strom.enabled=off;
SELECT t2.c0 FROM t2 GROUP BY t2.c0;
```

#### ***Result:***

```bash
 c0  
-----
 0.6
 0.7
 9.3
(3 rows)
```

#### SQL with GPU-used Config:

```sql
BEGIN;
SET LOCAL pg_strom.enabled=on; 
SET LOCAL pg_strom.enable_gpuscan=on; 
SET LOCAL pg_strom.enable_gpuhashjoin=on; 
SET LOCAL pg_strom.enable_gpujoin=on; 
SET LOCAL pg_strom.enable_gpupreagg=on; 
SELECT t2.c0 FROM t2 GROUP BY t2.c0;
COMMIT;
```

#### ***Result:***

```bash
 c0  
-----
 9.3
 0.6
 0.7
(3 rows)
```

### Environment:

Pg-strom Version: commit b1f04e4042a8990ee9b21263f08365982b5495b5

PostgreSQL Version: 15.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-20), 64-bit

CUDA Version: 12.2

NVIDIA Driver Version: 535.171.04

**Comment by kaigai** [comment]
This is not a bug but by design.

As introduced at #781, PostgreSQL does not guarantee the order of results.
So, the above output difference is reasonable.
