### ISSUE TITLE
Java liquibase throws max_num_rows consumes too much GPU device memory

### ISSUE THREAD

**Issue by IOhacker** [heterodb/pg-strom#796]
When running Java Application with Liquinase library I got this message:

 Reason: liquibase.exception.DatabaseException: ERROR: gpucache: max_num_rows = 10485760 consumes too much GPU device memory (main: 585.00MB, extra: 33.20GB), so we recommend to reduce 'max_num_rows' configuration [Failed SQL: (0) ALTER TABLE public.m_import_document ADD CONSTRAINT "FK_m_import_m_document" FOREIGN KEY (document_id) REFERENCES public.m_document (id) ON UPDATE RESTRICT ON DELETE RESTRICT]

How can I fix it?

[postgres@titan ~]$ psql -U postgres
psql (16.3)
Type "help" for help.

postgres=# select * from pgstrom.gpucache_info ;
 database_oid | database_name | table_oid | table_name | signature | phase | rowid_num_used | rowid_num_free | gpu_main_sz | gpu_main_nitems | gpu_extra_sz | gpu_extra_usage | gpu_extra_dead | redo_write_ts | re
do_write_nitems | redo_write_pos | redo_read_nitems | redo_read_pos | redo_sync_pos | config_options 
--------------+---------------+-----------+------------+-----------+-------+----------------+----------------+-------------+-----------------+--------------+-----------------+----------------+---------------+---
----------------+----------------+------------------+---------------+---------------+----------------
(0 rows)

postgres=# create trigger row_sync after insert or update or delete on dpoints_even for row
   execute function pgstrom.gpucache_sync_trigger('max_num_rows=10000,redo_buffer_size=100m');
ERROR:  relation "dpoints_even" does not exist
postgres=#

[root@titan data]# nvidia-smi 
Tue Jun 25 02:48:43 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.42.02              Driver Version: 555.42.02      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060        Off |   00000000:01:00.0 Off |                  N/A |
| 30%   32C    P8             15W /  170W |     141MiB /  12288MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     94003      C   postgres: PG-Strom GPU Service                132MiB |
+-----------------------------------------------------------------------------------------+

postgres=# select * from pgstrom.gpu_device_info;
 gpu_id |                   att_name                   |                att_value                 |                                                                                                   att_desc     
                                                                                               
--------+----------------------------------------------+------------------------------------------+----------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
      0 | DEV_NAME                                     | NVIDIA GeForce RTX 3060                  | GPU Device Name
      0 | DEV_ID                                       | 0                                        | GPU Device ID
      0 | DEV_UUID                                     | GPU-02ba1b15-9001-4e51-4e4c-44350aa35f73 | GPU Device UUID
      0 | DEV_TOTAL_MEMSZ                              | 11.67GB                                  | GPU Total RAM Size
      0 | DEV_BAR1_MEMSZ                               | 256.00MB                                 | GPU PCI Bar1 Size
      0 | NUMA_NODE_ID                                 | -1                                       | GPU NUMA Node Id
      0 | MAX_THREADS_PER_BLOCK                        | 1024                                     | Maximum number of threads per block
      0 | MAX_BLOCK_DIM_X                              | 1024                                     | Maximum block dimension X
      0 | MAX_BLOCK_DIM_Y                              | 1024                                     | Maximum block dimension Y
      0 | MAX_BLOCK_DIM_Z                              | 64                                       | Maximum block dimension Z
      0 | MAX_GRID_DIM_X                               | 2147483647                               | Maximum grid dimension X
      0 | MAX_GRID_DIM_Y                               | 65535                                    | Maximum grid dimension Y
      0 | MAX_GRID_DIM_Z                               | 65535                                    | Maximum grid dimension Z
      0 | MAX_SHARED_MEMORY_PER_BLOCK                  | 48.00KB                                  | Maximum shared memory available per block in bytes
      0 | TOTAL_CONSTANT_MEMORY                        | 64.00KB                                  | Memory available on device for __constant__ variables in a CUDA C kernel in bytes
      0 | WARP_SIZE                                    | 32                                       | Warp size in threads
      0 | MAX_PITCH                                    | 2048.00MB                                | Maximum pitch in bytes allowed by memory copies
      0 | MAX_REGISTERS_PER_BLOCK                      | 65536                                    | Maximum number of 32-bit registers available per block
      0 | CLOCK_RATE                                   | 1777 MHz                                 | Typical clock frequency in kilohertz
      0 | TEXTURE_ALIGNMENT                            | 512                                      | Alignment requirement for textures
      0 | MULTIPROCESSOR_COUNT                         | 28                                       | Number of multiprocessors on device
      0 | KERNEL_EXEC_TIMEOUT                          | 0                                        | Specifies whether there is a run time limit on kernels
      0 | INTEGRATED                                   | 0                                        | Device is integrated with host memory
      0 | CAN_MAP_HOST_MEMORY                          | 1                                        | Device can map host memory into CUDA address space
      0 | COMPUTE_MODE                                 | Default                                  | Compute mode (See ::CUcomputemode for details)
      0 | MAXIMUM_TEXTURE1D_WIDTH                      | 131072                                   | Maximum 1D texture width
      0 | MAXIMUM_TEXTURE2D_WIDTH                      | 131072                                   | Maximum 2D texture width
      0 | MAXIMUM_TEXTURE2D_HEIGHT                     | 65536                                    | Maximum 2D texture height
      0 | MAXIMUM_TEXTURE3D_WIDTH                      | 16384                                    | Maximum 3D texture width
      0 | MAXIMUM_TEXTURE3D_HEIGHT                     | 16384                                    | Maximum 3D texture height
      0 | MAXIMUM_TEXTURE3D_DEPTH                      | 16384                                    | Maximum 3D texture depth
      0 | MAXIMUM_TEXTURE2D_LAYERED_WIDTH              | 32768                                    | Maximum 2D layered texture width
      0 | MAXIMUM_TEXTURE2D_LAYERED_HEIGHT             | 32768                                    | Maximum 2D layered texture height
      0 | MAXIMUM_TEXTURE2D_LAYERED_LAYERS             | 2048                                     | Maximum layers in a 2D layered texture
      0 | SURFACE_ALIGNMENT                            | 512                                      | Alignment requirement for surfaces
      0 | CONCURRENT_KERNELS                           | 1                                        | Device can possibly execute multiple kernels concurrently
      0 | ECC_ENABLED                                  | 0                                        | Device has ECC support enabled
      0 | PCI_BUS_ID                                   | 1                                        | PCI bus ID of the device
      0 | PCI_DEVICE_ID                                | 0                                        | PCI device ID of the device
      0 | TCC_DRIVER                                   | 0                                        | Device is using TCC driver model
      0 | MEMORY_CLOCK_RATE                            | 7.50 GHz                                 | Peak memory clock frequency in kilohertz
      0 | GLOBAL_MEMORY_BUS_WIDTH                      | True                                     | Global memory bus width in bits
      0 | L2_CACHE_SIZE                                | 2304.00KB                                | Size of L2 cache in bytes
      0 | MAX_THREADS_PER_MULTIPROCESSOR               | 1536                                     | Maximum resident threads per multiprocessor
      0 | ASYNC_ENGINE_COUNT                           | 2                                        | Number of asynchronous engines
      0 | UNIFIED_ADDRESSING                           | 1                                        | Device shares a unified address space with the host
      0 | MAXIMUM_TEXTURE1D_LAYERED_WIDTH              | 32768                                    | Maximum 1D layered texture width
      0 | MAXIMUM_TEXTURE1D_LAYERED_LAYERS             | 2048                                     | Maximum layers in a 1D layered texture

Regards

**Comment by IOhacker** [comment]
Either running SQL sentence give me the same error

fineract_default=# ALTER TABLE public.m_import_document ADD CONSTRAINT "FK_m_import_m_document" FOREIGN KEY (document_id) REFERENCES public.m_document (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ERROR:  gpucache: max_num_rows = 10485760 consumes too much GPU device memory (main: 585.00MB, extra: 33.20GB), so we recommend to reduce 'max_num_rows' configuration
fineract_default=# 


2024-06-27 17:11:03.893 CST [10488] ERROR:  gpucache: max_num_rows = 10485760 consumes too much GPU device memory (main: 585.00MB, extra: 33.20GB), so we recommend to reduce 'max_num_rows' configuration
2024-06-27 17:11:03.893 CST [10488] STATEMENT:  ALTER TABLE public.m_import_document ADD CONSTRAINT "FK_m_import_m_document" FOREIGN KEY (document_id) REFERENCES public.m_document (id) ON UPDATE RESTRICT ON DELETE RESTRICT;

Any clue?

**Comment by IOhacker** [comment]
I have read the documentation, but I am unable to find the right way to  reduce 'max_num_rows' configuration. Anyone can point which is the documentation that I can read/use to achive it?

**Comment by kaigai** [comment]
This is the configuration to reduce `max_num_rows` of the GPU-Cache configuration.
(You can give a configuration string on the trigger function)
https://heterodb.github.io/pg-strom/gpucache/#gpu-cache-customize

**Comment by IOhacker** [comment]
Hi Kaigai,

Thank you. That configuration is at table level? Or it can be configured at
database/schema level?

Regards

Victor.

**Comment by kaigai** [comment]
It is a table-level configuration, because GPU-Cache is a per-table object.

**Comment by IOhacker** [comment]
Thank you for your help! I will try, and let you know.

Best regards

Victor

**Comment by IOhacker** [comment]
Hello,

I have followed the suggested documentation but it seems that the changes
are not being taken because I got the same message, even with the created
trigger. Let me show what I am doing and what are the errors I am facing.

***@***.*** ~]$ psql -U postgres
psql (16.3)
Type "help" for help.

postgres=# \c fineract_default
You are now connected to database "fineract_default" as user "postgres".
fineract_default=# create trigger row_sync after insert or UPDATE or DELETE
on public.m_document for row
   execute function pgstrom.gpucache_sync_trigger('max_num_rows=10000');
CREATE TRIGGER
fineract_default=# create trigger row_sync after insert or UPDATE or DELETE
on public.m_import_document for row
   execute function pgstrom.gpucache_sync_trigger('max_num_rows=10000');

CREATE TRIGGER
fineract_default=# \dS public.m_import_document
                                   Table "public.m_import_document"
    Column     |            Type             | Collation | Nullable |
      Default
---------------+-----------------------------+-----------+----------+----------------------------------
 id            | bigint                      |           | not null |
generated by default as identity
 document_id   | integer                     |           | not null |
 import_time   | timestamp without time zone |           | not null |
 end_time      | timestamp without time zone |           |          |
 entity_type   | smallint                    |           | not null |
 completed     | boolean                     |           |          | false
 total_records | bigint                      |           |          | 0
 success_count | bigint                      |           |          | 0
 failure_count | bigint                      |           |          | 0
 createdby_id  | bigint                      |           |          |
Indexes:
    "m_import_document_pkey" PRIMARY KEY, btree (id)
    "FK_m_import_m_appuser" btree (createdby_id)
    "import_document_id" btree (document_id)
Foreign-key constraints:
    "FK_m_import_m_appuser" FOREIGN KEY (createdby_id) REFERENCES
m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT
Triggers:
    row_sync AFTER INSERT OR DELETE OR UPDATE ON m_import_document FOR EACH
ROW EXECUTE FUNCTION pgstrom.gpucache_sync_trigger('max_num_rows=10000')

fineract_default=# \dS public.m_document
                                       Table "public.m_document"
       Column       |          Type           | Collation | Nullable |
        Default
--------------------+-------------------------+-----------+----------+----------------------------------
 id                 | integer                 |           | not null |
generated by default as identity
 parent_entity_type | character varying(50)   |           | not null |
 parent_entity_id   | integer                 |           | not null | 0
 name               | character varying(250)  |           | not null |
 file_name          | character varying(250)  |           | not null |
 size               | integer                 |           |          | 0
 type               | character varying(500)  |           |          |
 description        | character varying(1000) |           |          |
 location           | character varying(500)  |           | not null |
'0'::character varying
 storage_type_enum  | smallint                |           |          |
Indexes:
    "m_document_pkey" PRIMARY KEY, btree (id)
Triggers:
    row_sync AFTER INSERT OR DELETE OR UPDATE ON m_document FOR EACH ROW
EXECUTE FUNCTION pgstrom.gpucache_sync_trigger('max_num_rows=10000')

fineract_default=# ALTER TABLE public.m_import_document ADD CONSTRAINT
"FK_m_import_m_document" FOREIGN KEY (document_id) REFERENCES
public.m_document (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ERROR:  gpucache: max_num_rows = 10485760 consumes too much GPU device
memory (main: 585.00MB, extra: 33.20GB), so we recommend to reduce
'max_num_rows' configuration
fineract_default=#

**Comment by kaigai** [comment]
Could you wait for a few days?
It looks the estimation of the extra buffer size (used for varlena variables) is too much, and 32GB restrictions are obsolete.
The logic should be updated.

**Comment by IOhacker** [comment]
Hello,

Yes I can wait. I am now testing and understanding the PG Strom and its
technical benefits.

Regards

Victor

**Comment by kaigai** [comment]
`5e7b418c07d963c1047bd57d1f4be5cb561e7da5` removed the length check.

A recent enhancement related to Large-Tables-GpuJoin replaced 32bit offset in
KDS buffer, by 64bit offset, therefore, we have no reason why extra buffer of
GpuCache is not limited to 32GB.

**Comment by IOhacker** [comment]
I am going to build it and test it now

**Comment by IOhacker** [comment]
Hello, 

I can confirm it is working. Just I have to reinstall it from source code and remove the triggers.

[root@titan ~]# docker ps
CONTAINER ID   IMAGE                     COMMAND                  CREATED         STATUS                            PORTS                                                 NAMES
4ab87addf50e   openmf/web-app:master     "/docker-entrypoint.…"   3 minutes ago   Up 3 minutes                      0.0.0.0:80->80/tcp, :::80->80/tcp                     mifosx_in_minutes-web-app-1
b6acb0b1ce28   apache/fineract:develop   "java -cp @/app/jib-…"   7 minutes ago   Up 3 minutes (health: starting)   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 8443/tcp   mifosx_in_minutes-fineract-server-1
[root@titan ~]# nvidia-smi
Tue Jul  2 12:06:26 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.42.02              Driver Version: 555.42.02      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060        Off |   00000000:01:00.0 Off |                  N/A |
| 30%   32C    P8             15W /  170W |     141MiB /  12288MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     10442      C   postgres: PG-Strom GPU Service                132MiB |
+-----------------------------------------------------------------------------------------+


Regards

Victor
