### ISSUE TITLE
make install doesn't work

### ISSUE THREAD

**Issue by kruemelinger-b** [heterodb/pg-strom#799]
I'm trying to install PG-Strom on OpneSUSE Leap 15.5

After cloning the repo, the make command works well. 

But make install doesn't.
I'm always getting the error:  make: *** No rule to make target 'install'.  Stop.

Is there anything wrong with the Makefile?

**Comment by kaigai** [comment]
Could you move to the `src` directory before kicking `make` command?

**Comment by kruemelinger-b** [comment]
thanks a lot! this worked for me.
