### ISSUE TITLE
[JP] nvidia-gdsもバージョンを指定するべき

### ISSUE THREAD

**Issue by ytooyama** [heterodb/pg-strom#803]
該当部分
https://heterodb.github.io/pg-strom/ja/install/#cuda-toolkit

現在のドキュメントはCUDAのインストールでは`cuda-toolkit-12-5`のようにバージョンを指定しているのにもかかわらず、`nvidia-gds`パッケージはバージョン指定していません。
これで何が起こるかというと、`dnf update`などを行うと、新しいバージョンの`nvidia-gds`パッケージが公開されればアップデートされますし、依存して`nvidia-gds`と同じバージョンの`cuda-toolkit`パッケージが追加インストールされて、複数のCUDAがインストールされた状態になり、環境としては不完全になります。

したがって次の場合は

```shell
dnf install cuda-toolkit-12-5
```

次のように同じバージョンを例示すべきです。

```shell
dnf install nvidia-gds-12-5
```

逆にバージョンを外してしまう方法も考えられますが、GPUによって対応するCUDAは異なると思いますので適切ではないとおもいます。NVIDIAもバージョン指定してインストールすることを推奨しているようです。

**Comment by kaigai** [comment]
修正しました。
この辺、もう少し丁寧にパッケージ間の依存関係とか、アップデートの処理とかしてもらえると助かるんですけどね。

**Comment by ytooyama** [comment]
確認しました。ありがとうございます。クローズします。
個人的にはメタパッケージ多すぎ問題をなんとかして欲しいです。
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#meta-packages

依存関係はspecファイルにちゃんと書いてもらうしかないかと。こちらで対応できることはなさそうですね。
