### ISSUE TITLE
[VTJ-JP]CUDAバージョンに関する説明

### ISSUE THREAD

**Issue by ytooyama** [heterodb/pg-strom#807]
NVIDIAのドキュメントによると、オープンベースのドライバーがGDSに必須になったのはCUDA 12.2.2からという説明があります。

- https://docs.nvidia.com/cuda/archive/12.2.2/cuda-installation-guide-linux/index.html#install-gpudirect-storage
  - Starting with CUDA toolkit 12.2.2, GDS kernel driver package nvidia-gds version 12.2.2-1 (provided by nvidia-fs-dkms 2.17.5-1) and above is only supported with the NVIDIA open kernel driver. Follow the instructions in Removing CUDA Toolkit and Driver to remove existing NVIDIA driver packages and then follow instructions in NVIDIA Open GPU Kernel Modules to install NVIDIA open kernel driver packages.

次のこちらのリンク先がCUDA 12.2.2になっています。

- http://heterodb.github.io/pg-strom/ja/install/#cuda-toolkit

以下のリンク先の方が適切のようにみえます。

- https://developer.nvidia.com/cuda-12-2-1-download-archive?target_os=Linux&target_arch=x86_64&Distribution=RHEL&target_version=8&target_type=rpm_local

Note:
古い世代のGPUを使う場合、PG-Strom 5.xではCUDA 12.2が最低要件になる。GDSの仕様変更もあるので、CUDA 12.2GAかCUDA 12.2Update 1が必要になる。NVIDIAのドキュメントが正しければ、12.2Update 2以降のバージョンはTuring世代以降のGPUとOpenドライバーが必要になる模様。

**Comment by kaigai** [comment]
こちらも直しました。
今からV100とかを新規でインストールする人って、まずいないとは思うのですけどね。。。

**Comment by ytooyama** [comment]
確認しました。クローズします。
古いGPUはあくまで既存案件か、まずはお試ししたい人が利用するのみだと思います。

**Comment by kaigai** [comment]
新規で相談が来たら、全力でL40Sあたりをお勧めします・・・。
