### ISSUE TITLE
[JP][docs-issue] GPUキャッシュドキュメントにPostgreSQL 15以前のバージョン固有の情報がある

### ISSUE THREAD

**Issue by ytooyama** [heterodb/pg-strom#810]
PG-Strom 5.xはもはやPostgreSQL 15以前をサポートしていないので、取り除く必要があります。

該当部分

https://heterodb.github.io/pg-strom/ja/gpucache/

- 設定のNote部分
- 「以下は、PostgreSQL v12以前でGPUキャッシュをdpointsテーブルに設定する例」のあたり

**Comment by kaigai** [comment]
ドキュメントなおしました。

**Comment by ytooyama** [comment]
修正を確認しました。
