### ISSUE TITLE
[GPU Logic Bug] SELECT COUNT(<number>) FROM <table> LEFT OUTER JOIN <table> ON <column> Brings GPU Logic Bug

### ISSUE THREAD

**Issue by qwebug** [heterodb/pg-strom#829]
### Describe:

&#x20;SELECT COUNT(\<number>) FROM \<table> LEFT OUTER JOIN \<table> ON \<column> brings different results, when using CPU-only configurations and GPU-used configurations.

#### SQL with CPU-only Config:

```sql
CREATE TABLE t0(c0 int4range, c1 boolean);
CREATE TABLE t3(LIKE t0);
CREATE TABLE t4(LIKE t0);
INSERT INTO t4(c0, c1) VALUES('[-3,-1)'::int4range, FALSE);
INSERT INTO t0(c0, c1) VALUES('[-2,5]'::int4range, TRUE);
INSERT INTO t3(c0) VALUES('(-4,6]'::int4range);
CREATE SCHEMA extensions;
CREATE EXTENSION pg_strom WITH SCHEMA extensions;
SET pg_strom.enabled=off;
SELECT COUNT(0) FROM t3, t4 LEFT OUTER JOIN t0 ON t4.c1;
```

#### ***Result:***

```bash
 count 
-------
     1
(1 row)
```

#### SQL with GPU-used Config:

```sql
SET pg_strom.enabled=on;
SELECT COUNT(0) FROM t3, t4 LEFT OUTER JOIN t0 ON t4.c1;
```

#### ***Result:***

```bash
 count 
-------
     0
(1 row)
```

### Environment:

Pg-strom Version: commit 9765660eba4fab7e4e9378c667e6bd565da83ffd

PostgreSQL Version: 15.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-20), 64-bit

CUDA Version: 12.2

NVIDIA Driver Version: 535.171.04

**Comment by kaigai** [comment]
`ff92fbbc52b3b3d7a517f5905024250939c6294f` should fix this problem.

`pgstrom.nrows(0)` (that is an alternative function for CPU fallback / RIGHT OUTER tuples) didn't return correct value, if binary form of the argument can be considered as `false` in boolean.
