### ISSUE TITLE
[VTJ-JP][Document]arrow_fdwの仮想列の説明での変数割りあて指定抜け

### ISSUE THREAD

**Issue by sakaik** [heterodb/pg-strom#853]
arrow_fdwの説明ページ
　https://heterodb.github.io/pg-strom/ja/arrow_fdw/#arrow_fdw
で、
『Arrow_Fdwでは、外部テーブルオプションpatternを使用する事でファイル名の一部を列として参照する事ができます。これを仮想列と呼び、以下のように設定します。』として紹介されているコマンド例で「 @{year} 」は入るべきところで抜けてしまっています。

誤：pattern 'f_lineorder__${shipping}.arrow');
正：pattern 'f_lineorder_@{year}_${shipping}.arrow');

![image](https://github.com/user-attachments/assets/a260bcbe-1802-45f7-b33b-d80165d17e80)

**Comment by kaigai** [comment]
ドキュメントを修正しました。
